--[[--------------------------------------------------
003_Horde_50to60.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 50 to Lvl 60
    1.04.1
        -- First Release
            Horde's Guide
            from level 50 to lever 60
    1.04.2
    	-- no changes in here for this revision
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_50to60 = {
-----------50-50 Azshara
	--[501] = {
	[5049] = {
		title = "50-50 Azshara",
		n = "50-50 Azshara",
		pID = 414, nID = 502,
		itemCount = 23,
		items = {
			[1] = { str = "50-50 Azshara" },
			[2] = { str = "01) Accept: #ACCEPT\"Stealing Knowledge\"# " },
			[3] = { str = "02) Go do:" },
			[4] = { str = "03) #DOQUEST\"Stealing Knowledge\"# (Done at the Ruins of Eldarath, 36.54)", x = 36, y = 54, zone = "Azshara" },
			[5] = { str = "04) #DOQUEST\"Seeping Corruption\"# (Tide Pools are at: 1=47.61, 2=47.51, 3=48.48, 4=47.46)", x = 47, y = 61, zone = "Azshara" },
			[6] = { str = "05) Once their done, turn in #TURNIN\"Stealing Knowledge\"# ..accept ALL 4 delivery quests." },
			[7] = { str = "06) Turn in #TURNIN\"Delivery to Archmage Xylem\"# (there is a teleporter at 28.50,#VIDEOSee Video#) ... accept #ACCEPT\"Xylem's Payment to Jediga\"# ", x = 28, y = 50, zone = "Azshara" },
			[8] = { str = "07) Then fly to Thunder Bluff.." },
			[9] = { str = "08) Turn in #TURNIN\"Delivery to Magatha\"# (on Elder Rise) ... accept #ACCEPT\"Magatha's Payment to Jediga\"# " },
			[10] = { str = "09) Hearth to Orgrimmar." },
			[11] = { str = "10) Go turn in #TURNIN\"Rise of the Silithid\"# ... accept #ACCEPT\"March of the Silithid\"# (at 56.46)", x = 56, y = 46, zone = "Azshara" },
			[12] = { str = "11) Turn in #TURNIN\"Delivery to Jes'rimon\"# (at 55.34) ... accept #ACCEPT\"Jes'rimon's Payment to Jediga\"# and #ACCEPT\"Bone-Bladed Weapons\"# ", x = 55, y = 34, zone = "Azshara" },
			[13] = { str = "12) Then turn in #TURNIN\"Ripple Delivery\"# (at 59.36)  (If you did the Hinterlands section)", x = 59, y = 36, zone = "Azshara" },
			[14] = { str = "13) Then I go get new #HUNTERhunter# spells/abilities ... #HUNTERaccept# #ACCEPT\"The Hunter's Charm\"# #HUNTER(if you're a Hunter).#" },
			[15] = { str = "14) Then go to The Undercity, head to the Apothecarium Quarter..." },
			[16] = { str = "15) Turn in #TURNIN\"Delivery to Andron Gant\"# ... accept #ACCEPT\"Andron's Payment to Jediga\"# " },
			[17] = { str = "16) Then turn in #TURNIN\"Seeping Corruption\"# and #TURNIN\"Return to Apothecary Zinge\"# ... accept #ACCEPT\"Vivian Lagrave\"# while you are there." },
			[18] = { str = "17) Then accept #ACCEPT\"Seeping Corruption\"# ... then turn it in (at the tauren right next to him) ..." },
			[19] = { str = "18) ... Then complete #TURNIN\"Seeping Corruption\"# for the final time." },
			[20] = { str = "19) Then accept #ACCEPT\"A Sample of Slime...\"# and #ACCEPT\"... and a Batch of Ooze\"# " },
			[21] = { str = "20) Then fly to Raventusj Village..." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------50-50 Hinterlands
	--[502] = {
	[5050] = {
		title = "50-50 Hinterlands",
		--n = "50-50 Hinterlands",
		--pID = 501, nID = 503,
		--itemCount = 20,
		items = {
			[1] = { str = "50-50 Hinterlands" },
			[2] = { str = "05) Accept: #ACCEPT\"Snapjaws, Mon!\"# #ACCEPT\"Gammerita, Mon!\"# (Elite) and #ACCEPT\"Lard Lost His Lunch\"# " },
			[3] = { str = "06) Go do in the following order:" },
			[4] = { str = "07) #DOQUEST\"Snapjaws, Mon!\"# along with #DOQUEST\"Gammerita, Mon!\"# and #DOQUEST\"Whiskey Slim's Lost Grog\"# " },
			[5] = { str = "08) #DOQUEST\"Cortello's Riddle\"# (at 80.46, little chest in the water, 14 slot bag along with 8800 XP)", x = 80, y = 46, zone = "The Hinterlands" },
			[6] = { str = "09) #DOQUEST\"Lard Lost His Lunch\"# (at 84.42)", x = 84, y = 42, zone = "The Hinterlands" },
			[7] = { str = "10) Then go turn in #TURNIN\"Snapjaws, Mon!\"# #TURNIN\"Gammerita, Mon!\"# and #TURNIN\"Lard Lost His Lunch\"# " },
			[8] = { str = "09) then go do #DOQUEST\"Sprinkle's Secret Ingredient\"# (at 41.60)", x = 41, y = 60, zone = "The Hinterlands" },
			[9] = { str = "10) then hearth to Orgrimmar." },
			[10] = { str = "11) Fly to Azshara." },
			[11] = { str = "12) turn in all 4 delivery quests." },
			[12] = { str = "13) Fly to XRs." },
			[13] = { str = "14) make XRs your home." },
			[14] = { str = "15) Fly to Ratchet." },
			[15] = { str = "16) pick up the \"#NPCStone Circle#\" at Liv Rizzlefix shop ... also accept #ACCEPT\"Volcanic Activity\"# while your there." },
			[16] = { str = "17) get on the boat to go to BB" },
			[17] = { str = "18) Fly to Stonard (swamp of sorrows).." },
			[18] = { str = "19) go into Blasted Lands..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

------------50-51 Blasted Lands
	--[503] = {
	[5051] = {
		title = "50-51 Blasted Lands",
		--n = "50-51 Blasted Lands",
		--pID = 502, nID = 504,
		--itemCount = 27,
		items = {
			[1] = { str = "50-51 Blasted Lands" },
			[2] = { str = "01) I then find all the items to complete these 5 quests:" },
			[3] = { str = "02) #DOQUEST\"A Boar's Vitality\"# " },
			[4] = { str = "03) #DOQUEST\"Snickerfang Jowls\"# " },
			[5] = { str = "04) #DOQUEST\"The Basilisk's Bite\"# " },
			[6] = { str = "05) #DOQUEST\"The Decisive Striker\"# " },
			[7] = { str = "06) #DOQUEST\"Vulture's Vigor\"# " },
			[8] = { str = "07) you need to find these many items to complete these quests:" },
			[9] = { str = "08) #NPCVulture Gizzards# x14" },
			[10] = { str = "09) #NPCBasilisk Brain# x11" },
			[11] = { str = "10) #NPCBlasted Boar Lungs# x6" },
			[12] = { str = "11) #NPCScorpok Pincers# x6" },
			[13] = { str = "12) #NPCSnickerfang Jowls# x5" },
			[14] = { str = "13) While I'm in Blasted Lands, I discover most of all the areas for XP." },
			[15] = { str = "14) If an \"#NPCImperfect Draenethyst Fragment\" drops turn in for this quest: #TURNIN\"Everything Counts In Large Amounts\"# " },
			[16] = { str = "15) NOTE: I have NEVER found a \"#NPCFlawless Draenethyst Sphere#\" for the quest #TURNIN\"To Serve Kum'isha\"# ..good luck on that." },
			[17] = { str = "16) Turn in all quests." },
			[18] = { str = "17) I turn in #TURNIN\"The Decisive Striker\"# in last for Ground Scorpok Assay (+50 to agility)" },
			[19] = { str = "18) then hearth to XRs." },
			[20] = { str = "19) Fly to Tanaris (GET A MITHRIL CASING for a later quest in Un'Goro!!!)" },
			[21] = { str = "20) turn in #TURNIN\"Sprinkle's Secret Ingredient\"# ... accept #ACCEPT\"Delivery for Marin\"# " },
			[22] = { str = "21) turn in #TURNIN\"March of the Silithid\"# ... accept #ACCEPT\"Bungle in the Jungle\"# " },
			[23] = { str = "22) turn in #TURNIN\"Delivery for Marin\"# ...accept #ACCEPT\"Noggenfogger Elixir\"# then turn it in." },
			[24] = { str = "23) go turn in #TURNIN\"The Stone Circle\"# (at 52.46 in Tanaris)", x = 52, y = 46, zone = "Tanaris" },
			[25] = { str = "24) then go into Un'Goro Crater..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------51-52 Un'Goro Crater
	--[504] = {
	[5152] = {
		title = "51-52 Un'Goro Crater",
		--n = "51-52 Un'Goro Crater",
		--pID = 503, nID = 505,
		--itemCount = 56,
		items = {
			[1] = { str = "51-52 Un'Goro Crater" },
			[2] = { str = "01) Go accept: #ACCEPT\"The Apes of Un'Goro\"# and #ACCEPT\"The Fare of Lar'korwi\"# (at 71.75)", x = 71, y = 75, zone = "Un'Goro Crater" },
			[3] = { str = "02) Go do #DOQUEST\"The Fare of Lar'korwi\"# (at 68.56)", x = 68, y = 56, zone = "Un'Goro Crater" },
			[4] = { str = "03) Then go start doing: #DOQUEST\"Super Sticky\"# (up north in the middle) until this item drops #NPCA Mangled Journal#" },
			[5] = { str = "04) Then go into Marshal's Refuge (43.10), accept ALL quests there:  #ACCEPT\"Chasing A-Me 01\"# #ACCEPT\"Shizzle's Flyer\"# #ACCEPT\"Lost!\"# #ACCEPT\"Beware of Pterrordax\"# #ACCEPT\"Roll the Bones\"# #ACCEPT\"Alien Ecology\"# #ACCEPT\"Expedition Salvation\"# #ACCEPT\"Larion and Muigin\"# ", x = 43, y = 10, zone = "Un'Goro Crater" },
			[6] = { str = "05) Turn in #TURNIN\"Williden's Journal\"# " },
			[7] = { str = "06) Get FP there, then go do the Ungoro Grind :) ..." },
			[8] = { str = "07) NOTE: don't worry about the ungoro dirt mounds, you'll find enough soil from mob drops.  Also I don't worry about the Bloodpetal Sprouts, as they are not turned in for any XP." },
			[9] = { str = "08) While questing, find 7 crystals of each color (red, blue, green, and yellow for the #DOQUEST\"Crystals of Power\"# quest)" },
			[10] = { str = "09) #DOQUEST\"Super Sticky\"# " },
			[11] = { str = "10) #DOQUEST\"The Apes of Un'Goro\"# along with #DOQUEST\"Chasing A-Me 01\"# (if you have a #NPCmithril casing# do the escort) (63.17)", x = 63, y = 17, zone = "Un'Goro Crater" },
			[12] = { str = "11) #DOQUEST\"Larion and Muigin\"# " },
			[13] = { str = "12) #DOQUEST\"Beware of Pterrordax\"# along with #DOQUEST\"Shizzle's Flyer\"# and.." },
			[14] = { str = "13) #DOQUEST\"Roll the Bones\"# " },
			[15] = { str = "14) #DOQUEST\"Expedition Salvation\"# (68.36 and 38.65)", x = 68, y = 36, zone = "Un'Goro Crater" },
			[16] = { str = "15) #DOQUEST\"... and a Batch of Ooze\"# (I make sure I get at least 30 ooze samples)" },
			[17] = { str = "16) Go turn in #TURNIN\"The Apes of Un'Goro\"# ... accept #ACCEPT\"The Mighty U'cha\"# " },
			[18] = { str = "17) Turn in #TURNIN\"The Fare of Lar'korwi\"# ... accept #ACCEPT\"The Scent of Lar'korwi\"# " },
			[19] = { str = "18) Then go do:" },
			[20] = { str = "19) #DOQUEST\"Bone-Bladed Weapons\"# along with #DOQUEST\"The Scent of Lar'korwi\"# " },
			[21] = { str = "20) #ACCEPT\"It's a Secret to Everybody\"# ... click on boat and then bag under water (at 63.68)", x = 63, y = 68, zone = "Un'Goro Crater" },
			[22] = { str = "21) Then turn in #TURNIN\"The Scent of Lar'korwi\"# ... accept #ACCEPT\"The Bait for Lar'korwi\"# (71.75)", x = 71, y = 75, zone = "Un'Goro Crater" },
			[23] = { str = "22) Then go do #DOQUEST\"Alien Ecology\"# along with #DOQUEST\"Bungle in the Jungle\"# (50.80)", x = 50, y = 80, zone = "Un'Goro Crater" },
			[24] = { str = "23) Go accept #ACCEPT\"Finding the Source\"# (at 30.50), then do it along with #DOQUEST\"Volcanic Activity\"# ", x = 30, y = 50, zone = "Un'Goro Crater" },
			[25] = { str = "24) The hotspot path for the quest #DOQUEST\"Finding the Source\"# starts at 51,42 and the hot spot is at 50,46  (#VIDEOSee Video on where to find the hotspot#)", x = 51, y = 42, zone = "Un'Goro Crater" },
			[26] = { str = "25) #DOQUEST\"Lost!\"# Make sure all quests are done before doing this (besides \"#NPCThe Mighty U'cha\"# and \"#NPCThe Bait for Lar'korwi\"# ), then..." },
			[27] = { str = "26) ...This leads back to Marshal's Refuge, Turn in ALL quests there, accept new ones (including all the Pylon quests in the cave)." },
			[28] = { str = "27) Then go do (in the following order):" },
			[29] = { str = "28) #DOQUEST\"The Northern Pylon\"# (at 56.13)", x = 56, y = 13, zone = "Un'Goro Crater" },
			[30] = { str = "29) #DOQUEST\"The Mighty U'cha\"# (cave at 63.13)", x = 63, y = 13, zone = "Un'Goro Crater" },
			[31] = { str = "30) #DOQUEST\"The Eastern Pylon\"# (at 77.50)", x = 77, y = 50, zone = "Un'Goro Crater" },
			[32] = { str = "31) #DOQUEST\"The Bait for Lar'korwi\"# (80.50).  Then turn it in along with #TURNIN\"The Mighty U'cha\"# (71.75)", x = 71, y = 75, zone = "Un'Goro Crater" },
			[33] = { str = "32) Go west killing oozes along the way.." },
			[34] = { str = "33) Turn in #TURNIN\"Finding the Source\"# ... accept #ACCEPT\"The New Springs\"# (30.50)", x = 30, y = 50, zone = "Un'Goro Crater" },
			[35] = { str = "34) #DOQUEST\"The Western Pylon\"# (at 23.58)", x = 23, y = 58, zone = "Un'Goro Crater" },
			[36] = { str = "35) Go back to Marshal's Refuge killing oozes along the way.." },
			[37] = { str = "36) Turn in quests. make sure you complete #DOQUEST\"Making Sense of It\"# (just talk to the gnome in the cave)" },
			[38] = { str = "37) Fly to Tanaris." },
			[39] = { str = "38) Turn in #TURNIN\"Super Sticky\"# and #TURNIN\"Bungle in the Jungle\"# ... I SKIP \"#NPCPawn Captures Queen\"# " },
			[40] = { str = "39) Then fly to Thunder Bluff." },
			[41] = { str = "40) Go to Elder Rise." },
			[42] = { str = "41) Accept #ACCEPT\"Un'goro Soil\"# .. then turn it in ... accept #ACCEPT\"Morrowgrain Research\"# .. then turn that in..." },
			[43] = { str = "42) ...but SKIP the next part (the part that says bring 10 Morrowgrain)" },
			[44] = { str = "43) Go get new spells/abilities." },
			[45] = { str = "44) Hearth to XRs." },
			[46] = { str = "45) Then fly to Ratchet.." },
			[47] = { str = "46) Turn in #TURNIN\"Volcanic Activity\"# and #TURNIN\"Marvon's Workshop\"# - I SKIP \"#NPCZapper Fuel\"# " },
			[48] = { str = "47) Get on the boat to go to BB.." },
			[49] = { str = "48) Turn in #TURNIN\"Whiskey Slim's Lost Grog\"# " },
			[50] = { str = "49) Also turn in #TURNIN\"Rescue OOX-17/TN!\"# (if you did it)" },
			[51] = { str = "50) Fly to Kargath (Badlands).." },
			[52] = { str = "51) Turn in #TURNIN\"Vivian Lagrave\"# " },
			[53] = { str = "52) Accept: #ACCEPT\"Dreadmaul Rock\"# and #ACCEPT\"The Rise of the Machines\"# " },
			[54] = { str = "53) Then fly to Burning Steppes..." },
			--[55] = { str = "." },
			--[56] = { str = "." },
		}
	},

-----------52-53 Burning Steppes
	--[505] = {
	[5253] = {
		title = "52-53 Burning Steppes",
		--n = "52-53 Burning Steppes",
		--pID = 504, nID = 506,
		--itemCount = 18,
		items = {
			[1] = { str = "52-53 Burning Steppes" },
			[2] = { str = "01) Accept: #ACCEPT\"Broodling Essence\"# and #ACCEPT\"Tablet of the Seven\"# " },
			[3] = { str = "02) Then go do:" },
			[4] = { str = "03) #DOQUEST\"Broodling Essence\"# (to the east) (also kill as many dragon whelps you see, their \"squishy\" mobs that die real fast)" },
			[5] = { str = "04) #DOQUEST\"Dreadmaul Rock\"# (79.45)... then #DOQUEST\"Krom'Grul\"# (Krom'Grul has 2 different spawn points, in either cave)", x = 79, y = 45, zone = "Burning Steppes" },
			[6] = { str = "05) #DOQUEST\"The Rise of the Machines\"# " },
			[7] = { str = "06) #DOQUEST\"Tablet of the Seven\"# (it's at 54.40)", x = 54, y = 40, zone = "Burning Steppes" },
			[8] = { str = "07) Go turn in #TURNIN\"Tablet of the Seven\"# and #TURNIN\"Broodling Essence\"# ... accept #ACCEPT\"Felnok Steelspring\"# " },
			[9] = { str = "08) Then fly to Kargath (Badlands)" },
			[10] = { str = "09) Turn in #TURNIN\"Krom'Grul\"# " },
			[11] = { str = "10) Turn in #TURNIN\"The Rise of the Machines\"# ... accept #ACCEPT\"The Rise of the Machines\"# part2" },
			[12] = { str = "11) Go turn in #TURNIN\"The Rise of the Machines\"# part2 (at 25.46 in Badlands)", x = 25, y = 46, zone = "Badlands" },
			[13] = { str = "12) Then hearth to XRs." },
			[14] = { str = "13) Then fly to Orgrimmar and make it your home." },
			[15] = { str = "14) Go turn in #TURNIN\"Bone-Bladed Weapons\"# (55.34)", x = 55, y = 34, zone = "Orgrimmar" },
			[16] = { str = "15) Fly Azshara..." },
			--[17] = { str = "." },
			--[18] = { str = "." },
		}
	},

--------------53-54 Azshara
	--[506] = {
	[5354] = {
		title = "53-54 Azshara",
		--n = "53-54 Azshara",
		--pID = 505, nID = 507,
		--itemCount = 28,
		items = {
			[1] = { str = "53-54 Azshara" },
			[2] = { str = "01) accept #ACCEPT\"Betrayed\"# " },
			[3] = { str = "02) go turn in #TURNIN\"The Hunter's Charm\"# (this is a hunter only quest, at 41.42) ... accept #ACCEPT\"Courser Antlers\"# " },
			[4] = { str = "03) go accept #ACCEPT\"Kim'jael Indeed!\"# (at 52.22 on top of the hill)", x = 52, y = 22, zone = "Azshara" },
			[5] = { str = "04) then go do:" },
			[6] = { str = "05) #DOQUEST\"Courser Antlers\"# " },
			[7] = { str = "06) #DOQUEST\"Betrayed\"# " },
			[8] = { str = "07) #DOQUEST\"Kim'jael Indeed!\"# " },
			[9] = { str = "08) NOTE: I grind away at bloodelfs for a while doing those 2 quests." },
			[10] = { str = "09) Once those 3 quests are done, go turn in #TURNIN\"Kim'jael Indeed!\"# ... accept #ACCEPT\"Kim'jael's \"Missing\" Equipment\"# " },
			[11] = { str = "10) turn in #TURNIN\"Courser Antlers\"# ... accept #ACCEPT\"Wavethrashing\"# " },
			[12] = { str = "11) then go do:" },
			[13] = { str = "12) #DOQUEST\"Kim'jael's \"Missing\" Equipment\"# " },
			[14] = { str = "13) #DOQUEST\"Wavethrashing\"# " },
			[15] = { str = "14) Once both are done, Hearth to Orgrimmar." },
			[16] = { str = "15) then Fly to Azshara.." },
			[17] = { str = "16) turn in #TURNIN\"Betrayed\"# ... accept #ACCEPT\"Betrayed\"# " },
			[18] = { str = "17) turn in #TURNIN\"Wavethrashing\"# ... i SKIP #NPC\"The Green Drake\"# " },
			[19] = { str = "18) turn in #TURNIN\"Kim'jael's \"Missing\" Equipment\"# " },
			[20] = { str = "19) At this point im usually about 3/4th the way to lvl 54, I grind my way to level 54 on BloodElfs." },
			[21] = { str = "20) I grind bloodelfs, cause their \"squishy\" mobs (mobs that have 30% fewer health/armor, than the average mob that level).  I used to grind satyrs on previous speed runs, but I was able to cut off almost a whole hour with the blood elfs." },
			[22] = { str = "21) OPTIONAL: Instead of the grinding you could go do BRD instance instead." },
			[23] = { str = "22) Once i hit 54 (or a few bars past it), i then hearth to Orgrimmar." },
			[24] = { str = "23) I then go turn in #TURNIN\"Bone-Bladed Weapons\"# and #TURNIN\"Betrayed\"# " },
			[25] = { str = "24) then fly to Splintertree Post (Ashenvale).." },
			[26] = { str = "25) then go into Felwood..." },
			--[27] = { str = "." },
			--[28] = { str = "." },
		}
	},

-----------54-54 Felwood
	--[507] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 506, nID = 508,
		--itemCount = 16,
		items = {
			[1] = { str = "54-54 Felwood" },
			[2] = { str = "01) Accept #ACCEPT\"Timbermaw Ally\"# (at 50.85) (??? TBC Quest?) Just talk to the NPC there he will give it to you.", x = 50, y = 85, zone = "Felwood" },
			[3] = { str = "02) Go accept #ACCEPT\"Forces of Jaedenar\"# and #ACCEPT\"Verifying the Corruption\"# (at the Emerald Sanctuary 51.82).", x = 51, y = 82, zone = "Felwood" },
			[4] = { str = "03) Go accept #ACCEPT\"Cleansing Felwood\"# (at 46.84)", x = 46, y = 84, zone = "Felwood" },
			[5] = { str = "04) I start killing oozes, I make sure I kill about 30/40 oozes here total for the quest #DOQUEST\"A Sample of Slime...\"# (40.68)", x = 40, y = 68, zone = "Felwood" },
			[6] = { str = "05) Then go complete #DOQUEST\"Forces of Jaedenar\"# (38.60)", x = 38, y = 60, zone = "Felwood" },
			[7] = { str = "06) Then go to BloodVenom Post. (34.52)", x = 34, y = 52, zone = "Felwood" },
			[8] = { str = "07) Accept: #ACCEPT\"A Husband's Last Battle\"# and #ACCEPT\"Wild Guardians\"# " },
			[9] = { str = "08) Get FP there." },
			[10] = { str = "09) Then go do in the following order:" },
			[11] = { str = "10) #DOQUEST\"Verifying the Corruption\"# (Elite) (41.41)", x = 41, y = 41, zone = "Felwood" },
			[12] = { str = "11) #DOQUEST\"Cleansing Felwood\"# (54.16)", x = 54, y = 16, zone = "Felwood" },
			[13] = { str = "12) Go accept #ACCEPT\"Deadwood of the North\"# (at 64.8) but DON'T do it now.", x = 64, y = 8, zone = "Felwood" },
			[14] = { str = "13) Grind your way through the cave to go to Winterspring..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------54-55 Winterspring
	--[508] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 507, nID = 509,
		--itemCount = 31,
		items = {
			[1] = { str = "54-55 Winterspring" },
			[2] = { str = "01) Exit the cave and accept #ACCEPT\"Winterfall Activity\"# right outside of it." },
			[3] = { str = "02) Go to Donova Snowden (at 31.45)", x = 31, y = 45, zone = "Winterspring" },
			[4] = { str = "03) Turn in #TURNIN\"The New Springs\"# and #TURNIN\"It's a Secret to Everybody\"# and accept #ACCEPT\"Strange Sources\"#" },
			[5] = { str = "04) NOTE: I SKIP \"#NPCThe Videre Elixir\"# and the rest of that chain." },
			[6] = { str = "05) Go to Everlook.. (61.38)", x = 61, y = 38, zone = "Winterspring" },
			[7] = { str = "06) Accept: #ACCEPT\"Are We There, Yeti?\"# #ACCEPT\"The Everlook Report\"# #ACCEPT\"Duke Nicholas Zverenhoff\"# #ACCEPT\"Sister Pamela\"# #ACCEPT\"Trouble in Winterspring\"#and #ACCEPT\"Ursius of the Shardtooth\"#" },
			[8] = { str = "07) Turn in #TURNIN\"Felnok Steelspring\"# ... accept #ACCEPT\"Chillwind Horns\"# " },
			[9] = { str = "08) Make Everlook your home." },
			[10] = { str = "09) Go do #DOQUEST\"Ursius of the Shardtooth\"#   (just keep grinding mobs on the hill north of everlook till #NPCUrsius# shows up)" },
			[11] = { str = "10) Then turn in #TURNIN\"Ursius of the Shardtooth\"# ... accept #ACCEPT\"Brumeran of the Chillwind\"# " },
			[12] = { str = "11) Go do #DOQUEST\"Brumeran of the Chillwind\"# (he patrols around 60.60, see map for complete patrol path)", x = 60, y = 60, zone = "Winterspring" },
			[13] = { str = "12) Then go Discover Darkwhisper Gorge (at 59.73) for the quest #DOQUEST\"Strange Sources\"# ", x = 59, y = 73, zone = "Winterspring" },
			[14] = { str = "13) Then hearth back to Everlook." },
			[15] = { str = "14) Turn in #TURNIN\"Brumeran of the Chillwind\"# ... SKIP \"#NPCShy-Rotam\"# " },
			[16] = { str = "15) Then go do the following quests (steps 17-20, in any order) to the west and some to the north. When you're at west remember to turn-in #TURNIN\"Trouble in Winterspring\"# and accept #ACCEPT\"Threat of the Winterfall\"#:" },
			[17] = { str = "16) #DOQUEST\"Are We There, Yeti?\"# " },
			[18] = { str = "17) #DOQUEST\"Threat of the Winterfall\"# you should find #NPCEmpty Firewater Flask# which starts #ACCEPT\"Winterfall Firewater\"# while doing this quest.  When the #NPC\"Winterfall Ritual Totem\"# item drops, save it and put it in your bank you will need it later." },
			[19] = { str = "18) #DOQUEST\"Wild Guardians\"# (the Ragged Owls are west of Everlook, and the Raging Owls are just north of Everlook)" },
			[20] = { str = "19) #DOQUEST\"Chillwind Horns\"# (you can find a larger concentration of chimaera around 66.29)", x = 66, y = 29, zone = "Winterspring" },
			[21] = { str = "20) Once #DOQUEST\"Threat of the Winterfall\"# and #DOQUEST\"Winterfall Firewater\"# is completed go turn them in along with #TURNIN\"Strange Sources\"# (at 31.45)... accept #ACCEPT\"Falling to Corruption\"# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "21) Once the rest of those quests are complete, go back to Everlook and turn in #TURNIN\"Are We There, Yeti?\"# ...accept #ACCEPT\"Are We There, Yeti?\"# part2.  Turn in #TURNIN\"Chillwind Horns\"# ... i SKIP \"#NPCReturn to Tinkee\"# " },
			[23] = { str = "22) Then go do:" },
			[24] = { str = "23) #DOQUEST\"Winterfall Activity\"# (67.37)", x = 67, y = 37, zone = "Winterspring" },
			[25] = { str = "24) #DOQUEST\"Are We There, Yeti?\"# (find 2 Pristine Yeti Horns) (66.43)", x = 66, y = 43, zone = "Winterspring" },
			[26] = { str = "25) Then hearth to Everlook and accept #ACCEPT\"A Strange One \"#" },
			[27] = { str = "26) Go turn in #TURNIN\"Are We There, Yeti?\"# ... accept #ACCEPT\"Are We There, Yeti?\"# part3" },
			[28] = { str = "27) go scare Legacki with the mechanical yeti for the quest #DOQUEST\"Are We There, Yeti?\"# part3" },
			[29] = { str = "28) Then fly to Felwood..." },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

-----------55-55 Felwood
	--[509] = {
	[5554] = {
		title = "55-55 Felwood",
		--n = "55-55 Felwood",
		--pID = 508, nID = 510,
		--itemCount = 31,
		items = {
			[1] = { str = "55-55 Felwood" },
			[2] = { str = "01) Turn in #TURNIN\"Wild Guardians\"# ... Accept #ACCEPT\"Wild Guardians\"# part2 and #ACCEPT\"Well of Corruption\"#" },
			[3] = { str = "02) Go turn in #TURNIN\"Cleansing Felwood\"# ... then get a cenarion beacon for the quest #DOQUEST\"Salve Via Hunting\"# (just talk to the NPC to get it) (46.83)", x = 46, y = 83, zone = "Felwood" },
			[4] = { str = "03) Go turn in #TURNIN\"Verifying the Corruption\"# and #TURNIN\"Forces of Jaedenar\"# ... accept #ACCEPT\"Collection of the Corrupt Water\"# (51.82)", x = 51, y = 82, zone = "Felwood" },
			[5] = { str = "04) Go do in the following order:" },
			[6] = { str = "05) Go do #DOQUEST\"A Husband's Last Battle\"# along with #DOQUEST\"Timbermaw Ally\"# (48.94)", x = 48, y = 94, zone = "Felwood" },
			[7] = { str = "06) Once they are done go turn in #TURNIN\"Timbermaw Ally\"# (at 50.85) ... accept #ACCEPT\"Speak to Nafien\"#", x = 50, y = 85, zone = "Winterspring" },
			[8] = { str = "07) Go do #DOQUEST\"Well of Corruption\"# (at 32.66).  Also make sure you collect 6 #NPCCorrupted Soul Shards# for the quest #DOQUEST\"Salve Via Hunting\"# ", x = 32, y = 66, zone = "Felwood" },
			[9] = { str = "08) #DOQUEST\"Collection of the Corrupt Water\"# (35.59)", x = 35, y = 59, zone = "Felwood" },
			[10] = { str = "09) Then go to Bloodvenom Post" },
			[11] = { str = "10) Turn in #TURNIN\"A Husband's Last Battle\"# and #TURNIN\"Well of Corruption\"# ... accept #ACCEPT\"Corrupted Sabers\"# " },
			[12] = { str = "11) Go turn in #TURNIN\"Salve Via Hunting\"# (the 6 Corrupted Soul Shards) (46.83)", x = 46, y = 83, zone = "Felwood" },
			[13] = { str = "12) Go turn in #TURNIN\"Collection of the Corrupt Water\"# ... I SKIP \"#NPCSeeking Spiritual Aid\"# (51.82) ", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "13) Go do #DOQUEST\"Corrupted Sabers\"# (32.66) then go turn it in.  (NOTE: when you turn it in, you have to talk to the cat first once you get to the NPC)", x = 32, y = 66, zone = "Felwood" },
			[15] = { str = "14) Then go up north and do:" },
			[16] = { str = "15) #DOQUEST\"Deadwood of the North\"# (61.9)  When the \"Deadwood Ritual Totem\" item drops, save it and put it in your bank when you get a chance, you will need it later.", x = 61, y = 9, zone = "Felwood" },
			[17] = { str = "16) #DOQUEST\"Falling to Corruption\"# (the cauldron at 60.5) (hint: I have my pet distract the mobs, while doing this quest)   ... then accept #ACCEPT\"Mystery Goo\"# ", x = 60, y = 5, zone = "Felwood" },
			[18] = { str = "17) Go turn in #TURNIN\"Deadwood of the North\"# (64.8) ... accept #ACCEPT\"Speak to Salfa\"# .  And turn in #TURNIN\"Speak to Nafien\"# ", x = 64, y = 8, zone = "Felwood" },
			[19] = { str = "18) Then run through the cave (you should be Unfriendly with Timbermaw, so they shouldn't attack you).." },
			[20] = { str = "19) Turn in #TURNIN\"Winterfall Activity\"# and #TURNIN\"Speak to Salfa\"# " },
			[21] = { str = "20) Then go turn in #TURNIN\"Mystery Goo\"# (at 31.45 in Winterspring) ... SKIP \"#NPCToxic Horrors\"# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "21) Then hearth to Everlook." },
			[23] = { str = "22) Fly to Orgrimmar and make it your home." },
			[24] = { str = "23) If you happen to see #NPCWarcaller Gorlach#, accept #ACCEPT\"A Call To Arms: The Plaguelands!\"# " },
			[25] = { str = "24) Fly to Thunder Bluff, then directly to Camp Mojache, Ferelas" },
			[26] = { str = "25) Turn in #TURNIN\"The Strength of Corruption\"# " },
			[27] = { str = "26) Then fly to Tanaris..." },
			[28] = { str = "27) Go scare #NPCSprinkle# with the mechanical yeti for the quest #DOQUEST\"Are We There, Yeti?\"# part3" },
			[29] = { str = "28) Then fly to Silithus" },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

------------55-55 Silithus
	--[510] = {
	[5555] = {
		title = "55-55 Silithus",
		--n = "55-55 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 25,
		items = {
			[1] = { str = "55-55 Silithus" },
			[2] = { str = "01) accept: #ACCEPT\"The Twilight Mystery\"# #ACCEPT\"Securing the Supply Lines\"# and #ACCEPT\"Deadly Desert Venom\"# " },
			[3] = { str = "02) go do: #DOQUEST\"Securing the Supply Lines\"# and #DOQUEST\"Deadly Desert Venom\"# (do these 2 quests northeast of Cenarion Hold)" },
			[4] = { str = "03) then turn them in and accept new quests." },
			[5] = { str = "04) then go do:" },
			[6] = { str = "05) #DOQUEST\"Stepping Up Security\"# " },
			[7] = { str = "06) #DOQUEST\"The Twilight Mystery\"# " },
			[8] = { str = "07) #DOQUEST\"Noggle's Last Hope\"# " },
			[9] = { str = "08) Once all three of those are done, go turn them in accept new ones." },
			[10] = { str = "09) go do:" },
			[11] = { str = "10) #DOQUEST\"Noggle's Lost Satchel\"# (it's at around 40.90)", x = 40, y = 90, zone = "Silithus" },
			[12] = { str = "11) NOTE: I skip #NPC\"Wanted - Deathclasp, Terror of the Sands\"# (Elite) cause it's too hard to solo at 55, but do it if you can find a group." },
			[13] = { str = "12) #DOQUEST\"The Deserter\"# (he's in the cave at 67.71) ... i SKIP #NPC\"The Twilight Lexicon\"# ", x = 67, y = 71, zone = "Silithus" },
			[14] = { str = "13) then i die on purpose, so i end up at Cenarion Hold." },
			[15] = { str = "14) turn in #TURNIN\"Noggle's Lost Satchel\"# " },
			[16] = { str = "15) then go to Marshal's Refuge in Un'Goro Crater." },
			[17] = { str = "16) go scare Quixxil with the mechanical yeti for the quest #DOQUEST\"Are We There, Yeti?\"# part3" },
			[18] = { str = "17) then hearth to Orgrimmar." },
			[19] = { str = "18) go to the Under City." },
			[20] = { str = "19) go complete #TURNIN\"A Sample of Slime...\"# and #TURNIN\"... and a Batch of Ooze\"# " },
			[21] = { str = "20) go accept #ACCEPT\"A Call To Arms: The Plaguelands!\"# " },
			[22] = { str = "21) make Under City your home." },
			[23] = { str = "22) go to the Bulwark... (which is a small village east of Tirisfal Glades)" },
			--[24] = { str = "." },
			--[25] = { str = "." },
		}
	},

-----------55-56 Western Plaguelands
	--[511] = {
	[5556] = {
		title = "55-56 Western Plaguelands",
		--n = "55-56 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 24,
		items = {
			[1] = { str = "55-56 Western Plaguelands" },
			[2] = { str = "01) Turn in #TURNIN\"A Call To Arms: The Plaguelands!\"# accept #ACCEPT\"Scarlet Diversions\"# ..." },
			[3] = { str = "02) ... (make sure you get a Flame in a Bottle first, before doing this quest, it's in the box)" },
			[4] = { str = "03) Turn in #TURNIN\"The Everlook Report\"# " },
			[5] = { str = "04) Accept and complete #DOQUEST\"Argent Dawn Commission\"# " },
			[6] = { str = "05) Accept #ACCEPT\"A Plague Upon Thee\"# " },
			[7] = { str = "06) Go into the Western Plaguelands (Felstone field at 37.56) and...", x = 37, y = 56, zone = "Western Plaguelands" },
			[8] = { str = "07) Accept #ACCEPT\"Better Late Than Never\"# (the lady in the house)" },
			[9] = { str = "08) Then go to the barn next door, and..." },
			[10] = { str = "09) Complete #DOQUEST\"Better Late Than Never\"# .. click on the chest again to accept #ACCEPT\"Better Late Than Never\"# again." },
			[11] = { str = "10) Go do #DOQUEST\"Scarlet Diversions\"# (burn the tent down, and plant the banner, 40.51)  ", x = 40, y = 51, zone = "Western Plaguelands" },
			[12] = { str = "11) Go back to the Bulwark..  (#VIDEONOTE:# Make sure you save all #NPCBone Fragments# you find, you will need 30 of them for a later #NPCquest#)" },
			[13] = { str = "12) Turn in #TURNIN\"Scarlet Diversions\"# ... accept #ACCEPT\"All Along the Watchtowers\"# (Elite) and #ACCEPT\"The Scourge Cauldrons\"# " },
			[14] = { str = "13) Turn in #TURNIN\"The Scourge Cauldrons\"# ... accept #ACCEPT\"Target: Felstone Field\"# " },
			[15] = { str = "14) Go complete the whole Cauldron quest chain, you need to kill the Cauldron Lord at each targeted field (listed below), grab their key and use it at the big cauldron in the middle of the field.  (Just keep going back and forth from The Bulwark to the next field completing each one, turning them in and then accepting and doing the next one)..." },
			[16] = { str = "15) #DOQUEST\"Target: Felstone Field\"# (37.56)", x = 37, y = 56, zone = "Western Plaguelands" },
			[17] = { str = "16) #DOQUEST\"Target: Dalson's Tears\"# (46.52).  #VIDEONOTE:#  While you are here, there is a small quest chain here that starts with a little Diary in the barn (47.50) called #TURNIN\"Mrs. Dalson's Diary\"# , just click that to complete the quest.  Now, after you did that, then you need to kill a #NPCWandering Skeleton# to get a key that opens the outhouse behind the barn. After you get the key and open the outhouse, it will release a #NPCFarmer Dalson#, a level 56 undead. Kill him, grab that key, and then run in the house (that is right next to the barn) and go up the stairs, there you will find a cabinet, open the cabinet with that key (For the quest #DOQUEST\"Locked Away\"# ) and finally it's over.  Easy 10200 XP!  Or was it?", x = 46, y = 52, zone = "Western Plaguelands" },
			[18] = { str = "17) #DOQUEST\"Target: Writhing Haunt\"# (53.65) (while you're there accept #ACCEPT\"The Wildlife Suffers Too\"# (at 53.64, the almost dead tauren in the hut)", x = 53, y = 65, zone = "Western Plaguelands" },
			[19] = { str = "18) #DOQUEST\"Target: Gahrron's Withering\"# (62.59)", x = 62, y = 59, zone = "Western Plaguelands" },
			[20] = { str = "19) Just keep going back and forth completing each one." },
			[21] = { str = "20) Then go accept and complete #DOQUEST\"Mission Accomplished!\"# " },
			[22] = { str = "21) Then head into Eastern Plaguelands..." },
			--[23] = { str = "." },
			--[24] = { str = "." },
		}
	},

-----------56-57 Eastern Plaguelands
	--[512] = {
	[5657] = {
		title = "56-57 Eastern Plaguelands",
		--n = "56-57 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 38,
		items = {
			[1] = { str = "56-57 Eastern Plaguelands" },
			[2] = { str = "01) Go accept: #ACCEPT\"Demon Dogs\"# #ACCEPT\"Blood Tinged Skies\"# and #ACCEPT\"Carrion Grubbage\"# (at 7.43)", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "02) Grind your way to (26.74) and accept: #ACCEPT\"To Kill With Purpose\"# and #ACCEPT\"Un-Life's Little Annoyances\"# .  NOTE: I SKIP \"#NPCThe Ranger Lord's Behest\"# ", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[4] = { str = "03) Go down in the crypt at The Undercroft (27.85) and accept #ACCEPT\"Hameya's Plea\"# (the scroll on the ground). (??? TBC Quest?)", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[5] = { str = "04) Grind your way to Darrowshire (36.90) while doing these quests:", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[6] = { str = "05) #DOQUEST\"Demon Dogs\"# " },
			[7] = { str = "06) #DOQUEST\"Blood Tinged Skies\"# " },
			[8] = { str = "07) #DOQUEST\"Carrion Grubbage\"# " },
			[9] = { str = "08) Then turn in #TURNIN\"Sister Pamela\"# ... accept and do #ACCEPT\"Pamela's Doll\"# (there's 3 parts of the doll)" },
			[10] = { str = "09) Turn in #TURNIN\"Pamela's Doll\"# ... accept #ACCEPT\"Auntie Marlene\"# and #ACCEPT\"Uncle Carlin\"# " },
			[11] = { str = "10) Then go complete #DOQUEST\"Blood Tinged Skies\"# " },
			[12] = { str = "11) Then make sure you kill 20 Plaguehound Runts for the quest #DOQUEST\"Demon Dogs\"# " },
			[13] = { str = "12) Then go to Light's Hope Chapel (at 81.60)", x = 81, y = 60, zone = "Eastern Plaguelands" },
			[14] = { str = "13) Accept: #ACCEPT\"Zaeldarr the Outcast\"# and #ACCEPT\"The Restless Souls\"# " },
			[15] = { str = "14) Turn in #TURNIN\"Duke Nicholas Zverenhoff\"# and #TURNIN\"Uncle Carlin\"# ... accept #ACCEPT\"Defenders of Darrowshire\"# " },
			[16] = { str = "15) Get FP there.  Then go do:" },
			[17] = { str = "16) #DOQUEST\"To Kill With Purpose\"# " },
			[18] = { str = "17) #DOQUEST\"Defenders of Darrowshire\"# " },
			[19] = { str = "18) #DOQUEST\"Hameya's Plea\"# (72.14) (??? TBC Quest?)", x = 72, y = 14, zone = "Eastern Plaguelands" },
			[20] = { str = "19) #DOQUEST\"Demon Dogs\"# " },
			[21] = { str = "20) #DOQUEST\"Carrion Grubbage\"# " },
			[22] = { str = "21) #DOQUEST\"Un-Life's Little Annoyances\"# " },
			[23] = { str = "22) #DOQUEST\"A Plague Upon Thee\"# (done at Plaguewood up north)" },
			[24] = { str = "23) #DOQUEST\"Augustus' Receipt Book\"# (get this quest in the hut at 13.34, the book is upstairs in the inn at 15.33)", x = 15, y = 33, zone = "Eastern Plaguelands" },
			[25] = { str = "24) #DOQUEST\"The Restless Souls\"# (#NPCEgan# is in the hut at 13.34) (The next part refers to Stratholme, which I skip)", x = 13, y = 34, zone = "Eastern Plaguelands" },
			[26] = { str = "25) Then go turn in: #TURNIN\"Augustus' Receipt Book\"# " },
			[27] = { str = "26) Grind your way through the cave (15.29) (watch out it is not easy) ", x = 15, y = 29, zone = "Eastern Plaguelands" },
			[28] = { str = "#VIDEONOTE:#  If the cave is too hard for you, another easy alternative is to take the Tower Gryphon ride from the Plaguewood Tower (22.32) to the Crown Guard tower (39.75), as long as the horde has control over the towers that is.  Then turn in #TURNIN\"Demon Dogs\"# #TURNIN\"Blood Tinged Skies\"# and #TURNIN\"Carrion Grubbage\"#   accept #ACCEPT\"Redemption\"#   ... Just talk to the guy to complete it ... I SKIP \"#NPCOf Forgotten Memories\"# (you can try it if you find a group)", x = 22, y = 32, zone = "Eastern Plaguelands" },
			[29] = { str = "27) Then go turn in: #TURNIN\"To Kill With Purpose\"# and #TURNIN\"Un-Life's Little Annoyances\"# (at 26.74)", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[30] = { str = "28) Then go do #DOQUEST\"Zaeldarr the Outcast\"# (27.85)", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[31] = { str = "29) Then go to the dirt mound behind the crypt and turn in #TURNIN\"Hameya's Plea\"# (??? TBC Quest?)" },
			[32] = { str = "30) Then turn in: #TURNIN\"Zaeldarr the Outcast\"# and #TURNIN\"Defenders of Darrowshire\"# at Light's Hope Chapel" },
			[33] = { str = "31) Hearth to Under City.." },
			[34] = { str = "32) Turn in #TURNIN\"Better Late Than Never\"# ... accept #ACCEPT\"The Jeremiah Blues\"# " },
			[35] = { str = "33) Turn in #TURNIN\"The Jeremiah Blues\"# (just right underneath the bank) ... accept #ACCEPT\"Good Luck Charm\"# " },
			[36] = { str = "34) Go back to the Bulwark..." },
			--[37] = { str = "." },
			--[38] = { str = "." },
		}
	},

-----------57-58 Western Plaguelands
	--[513] = {
	[5758] = {
		title = "57-58 Western Plaguelands",
		--n = "57-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 37,
		items = {
			[1] = { str = "57-58 Western Plaguelands" },
			[2] = { str = "01) Turn in #TURNIN\"A Plague Upon Thee\"# ... accept #ACCEPT\"A Plague Upon Thee\"# part2." },
			[3] = { str = "02) Go turn in #TURNIN\"Good Luck Charm\"# ...accept #ACCEPT\"Two Halves Become One\"# (the lady in the house at 37.56)", x = 37, y = 56, zone = "Western Plaguelands" },
			[4] = { str = "03) Do #DOQUEST\"Two Halves Become One\"# (#NPCJabbering ghouls# out in Felstone Field drop the item you need, once you get the item right-click it in your inventory), then go back to the lady in the house to turn it in." },
			[5] = { str = "04) Then do #DOQUEST\"A Plague Upon Thee\"# part2 ... accept #ACCEPT\"A Plague Upon Thee\"# part3 (this is all done at 48.31)  " },
			[6] = { str = "05) Then go accept #ACCEPT\"Unfinished Business\"# part1 (at 51.28), then do it. (the mobs for this quest are at 50.42 and 53.44)", x = 51, y = 28, zone = "Western Plaguelands" },
			[7] = { str = "06) Turn in #TURNIN\"Unfinished Business\"# part1 (back at 51.28) ... accept #ACCEPT\"Unfinished Business\"# part2, then go do it. The 2 mobs for this quest are at (57.37 and 54.24).", x = 55, y = 30, zone = "Western Plaguelands" },
			[8] = { str = "07) Turn in #TURNIN\"Unfinished Business\"# part2 (back at 51.28) ... accept #ACCEPT\"Unfinished Business\"# part3, then go do it. Need to go up in the tower (at 45.19) in a certain spot, watch out for Elites.", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "08) Then turn in #TURNIN\"Unfinished Business\"# part3" },
			[10] = { str = "09) Then go complete and turn in #TURNIN\"The Wildlife Suffers Too\"# ... accept  #ACCEPT\"The Wildlife Suffers Too\"# part2 (53.64)", x = 53, y = 64, zone = "Western Plaguelands" },
			[11] = { str = "10) Do #DOQUEST\"The Wildlife Suffers Too\"# part2, then turn it in ... accept #ACCEPT\"Glyphed Oaken Branch\"# " },
			[12] = { str = "11) Go turn in #TURNIN\"Auntie Marlene\"# (in the house at 49.78)  ...accept #ACCEPT\"A Strange Historian\"# ", x = 49, y = 78, zone = "Western Plaguelands" },
			[13] = { str = "12) Go get the ring for #DOQUEST\"A Strange Historian\"# (the ring is out in the graveyard)" },
			[14] = { str = "13) Go into Andorhal.." },
			[15] = { str = "14) Do #DOQUEST\"All Along the Watchtowers\"# while working your way to the inn (at 39.66)", x = 39, y = 66, zone = "Western Plaguelands" },
			[16] = { str = "15) Turn in #TURNIN\"A Strange Historian\"# (at #NPCChromie# up stairs in the inn at 39.68) ... accept #ACCEPT\"The Annals of Darrowshire\"# and #ACCEPT\"A Matter of Time\"# ", x = 39, y = 68, zone = "Western Plaguelands" },
			[17] = { str = "16) Then go do (while grinding away at mobs):" },
			[18] = { str = "17) #DOQUEST\"All Along the Watchtowers\"# (Elite) " },
			[19] = { str = "18) #DOQUEST\"A Matter of Time\"# (47.62)", x = 47, y = 62, zone = "Western Plaguelands" },
			[20] = { str = "19) #DOQUEST\"The Annals of Darrowshire\"# the book for this is in the building at (42.67), the actual Annals of Darrowshire book looks different from the others, it has a lighter tint on the top portion of the pages in the book, unlike the rest which has a darker tint on the top portion of the pages.", x = 42, y = 67, zone = "Western Plaguelands" },
			[21] = { str = "20) Go turn in #TURNIN\"A Matter of Time\"# and #TURNIN\"The Annals of Darrowshire\"# ... accept #ACCEPT\"Counting Out Time\"# and #ACCEPT\"Brother Carlin\"# " },
			[22] = { str = "21) Go do #DOQUEST\"Counting Out Time\"# then turn it in. (it's repeatable but you only get XP once from it)" },
			[23] = { str = "22) I then keep grinding away at mobs in Andorhal till i'm Friendly with the Argent Dawn, so im able to buy Enriched Manna Biscuits (which replenish mana faster from drinking). As soon as I hit friendly with AD, I then go back to the Bulwark.." },
			[24] = { str = "23) Turn in #TURNIN\"A Plague Upon Thee\"# part3" },
			[25] = { str = "24) Turn in #TURNIN\"All Along the Watchtowers\"# ... accept #ACCEPT\"Scholomance\"# " },
			[26] = { str = "25) Turn in #TURNIN\"Scholomance\"# at the undead guy right next to him ... accept #ACCEPT\"Skeletal Fragments\"# " },
			[27] = { str = "26) Stock up on #NPCEnriched Manna Biscuits# (which replenishes mana faster from drinking)" },
			[28] = { str = "27) I then go back to Andorhal, and grind all the way to level 58 while doing #DOQUEST\"Skeletal Fragments\"# quest." },
			[29] = { str = "28) As soon as I hit 58 and #DOQUEST\"Skeletal Fragments\"# is done and you also have 30 #NPCBone Fragments# (please note, if you are far off from the 30 bone fragments, then you can just skip it), then go back to the Bulwark and turn in #TURNIN\"Skeletal Fragments\"# .. I SKIP \"#NPCMold Rhymes With...\"# " },
			[30] = { str = "29) I turn in any scourge stones, I have." },
			[31] = { str = "30) I then stock up on #NPCEnriched Manna Biscuits# (about 600? :D)" },
			[32] = { str = "31) then go get on the zeppelin to go to Orgrimmar. (while waiting, make heavy runecloth bandages)" },
			[33] = { str = "32) Once in Orgrimmar i get new spells/abilites." },
			[34] = { str = "33) bank 2/3rd of my manna biscuits." },
			[35] = { str = "34) then fly to Winterspring..." },
			--[36] = { str = "." },
			--[37] = { str = "." },
		}
	},

------------58-60 Winterspring
	--[514] = {
	[5860] = {
		title = "58-60 Winterspring",
		--n = "58-60 Winterspring",
		--pID = 513, nID = 514,
		--itemCount = 32,
		items = {
			[1] = { str = "58-60 Winterspring" },
			[2] = { str = "01) First thing i do here is stable my pet." },
			[3] = { str = "02) then make Everlook your home." },
			[4] = { str = "03) turn in #TURNIN\"Are We There, Yeti?\"# part3" },
			[5] = { str = "04) accept: #ACCEPT\"Luck Be With You\"# (Elite) and #ACCEPT\"Ursius of the Shardtooth\"# (Elite)" },
			[6] = { str = "05) then go tame a Winterspring Screecher (for Claw Rank8) (head south to do this)" },
			[7] = { str = "06) then use that pet to do #DOQUEST\"Luck Be With You\"# (just use your pet to distract the giants while picking up the Frostmaul Shards)" },
			[8] = { str = "07) then hearth to Everlook." },
			[9] = { str = "08) go do #DOQUEST\"Ursius of the Shardtooth\"# (Elite) (just keep grinding mobs on the hill north of everlook till Ursius shows up)" },
			[10] = { str = "09) go turn in #TURNIN\"Luck Be With You\"# (if it's done yet) and #TURNIN\"Ursius of the Shardtooth\"# ... accept #ACCEPT\"Brumeran of the Chillwind\"# (Elite)" },
			[11] = { str = "10) then go south and do:" },
			[12] = { str = "11) #DOQUEST\"Brumeran of the Chillwind\"# (Elite)" },
			[13] = { str = "12) #DOQUEST\"Luck Be With You\"# (Elite) (if you still need to finish it up)" },
			[14] = { str = "13) #DOQUEST\"Wild Guardians\"# part2 (i grind away at owls at the Owl Wing Thicket for a few hours, before leaving here)" },
			[15] = { str = "14) then when im a few bars away from 59, i go back up to Everlook (DONT hearth).." },
			[16] = { str = "15) turn in #TURNIN\"Luck Be With You\"# and #TURNIN\"Brumeran of the Chillwind\"# ... i SKIP #NPC\"Shy-Rotam\"# (Elite)" },
			[17] = { str = "16) Fly to Bloodvenom Post (Felwood).." },
			[18] = { str = "17) turn in #TURNIN\"Wild Guardians\"# part2 ... accept #ACCEPT\"Wild Guardians\"# part3" },
			[19] = { str = "18) then hearth back to Everlook." },
			[20] = { str = "19) Then go down to the Owl Wing Thicket and do #DOQUEST\"Wild Guardians\"# part3" },
			[21] = { str = "20) I keep grinding away at Owls till im about 59 and a half, then..." },
			[22] = { str = "21) I die on purpose, so i end up at Everlook (don’t hearth)" },
			[23] = { str = "22) then Fly to Bloodvenom Post (Felwood).." },
			[24] = { str = "23) turn in #TURNIN\"Wild Guardians\"# part3 and #TURNIN\"Guarding Secrets\"# ... accept #ACCEPT\"Guarding Secrets\"# part2" },
			[25] = { str = "24) I then fly to XRs, then to Thunderbluff, go to Elder Rise.." },
			[26] = { str = "25) turn in #TURNIN\"Guarding Secrets\"# part2 and #TURNIN\"Glyphed Oaken Branch\"# (both at Nara Wildmane)" },
			[27] = { str = "26) Hearth back to Everlook." },
			[28] = { str = "27) At this point im usually about 3/4 way to 60." },
			[29] = { str = "28) I then go back down to the Owl Wing Thicket and Grind to 60.  (See End Game Credits)" },
			[30] = { str = "." },
			[31] = { str = "." },
			[32] = { str = "CONGRATULATION, you're lvl60 now!"},
			[33] = { str = "." },
			--[34] = { str = "." },
		}
	},
}
