--[[--------------------------------------------------
003_Horde_50to60.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 50 to Lvl 60
    1.04.1
        -- First Release
            Horde's Guide
            from level 50 to lever 60
    1.04.2
    	-- no changes in here for this revision
    1.04.3
	    -- Cleanup in text, changed formatting of coords
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_50to60 = {
-----------50-50 Azshara
	--[501] = {
	[5049] = {
		title = "50-50 Azshara",
		n = "50-50 Azshara",
		pID = 414, nID = 502,
		itemCount = 23,
		items = {
			[1] = { str = "50-50 Azshara" },
			[2] = { str = "Accept: #GETStealing Knowledge# " },
			[3] = { str = "Go do:" },
			[4] = { str = "#DOStealing Knowledge# Done at the Ruins of Eldarath, #COORD[36,54]#", x = 36, y = 54, zone = "Azshara" },
			[5] = { str = "#DOSeeping Corruption# Tide Pools are at: 1=#COORD[47,61]#, 2=#COORD[47,51]#, 3=#COORD[48,48]#, 4=#COORD[47,46]#", x = 47, y = 61, zone = "Azshara" },
			[6] = { str = "Once their done, turn in #INStealing Knowledge# ..accept ALL 4 delivery quests." },
			[7] = { str = "Turn in #INDelivery to Archmage Xylem#, there is a teleporter at #COORD[28,50]#,#VIDEOSee Video# ... accept #GETXylem's Payment to Jediga# ", x = 28, y = 50, zone = "Azshara" },
			[8] = { str = "Then fly to Thunder Bluff.." },
			[9] = { str = "Turn in #INDelivery to Magatha# (on Elder Rise) ... accept #GETMagatha's Payment to Jediga# " },
			[10] = { str = "Hearth to Orgrimmar." },
			[11] = { str = "Go turn in #INRise of the Silithid# ... accept #GETMarch of the Silithid# at #COORD[56,46]#", x = 56, y = 46, zone = "Azshara" },
			[12] = { str = "Turn in #INDelivery to Jes'rimon# at #COORD[55,34]# ... accept #GETJes'rimon's Payment to Jediga# and #GETBone-Bladed Weapons# ", x = 55, y = 34, zone = "Azshara" },
			[13] = { str = "Then turn in #INRipple Delivery# at #COORD[59,36]#  (If you did the Hinterlands section)", x = 59, y = 36, zone = "Azshara" },
		--L- Remove Ripple Delivery as the quest cannot be accepet at given level
			[14] = { str = "Then go to The Undercity, head to the Apothecarium Quarter..." },
			[15] = { str = "Turn in #INDelivery to Andron Gant# ... accept #GETAndron's Payment to Jediga# " },
			[16] = { str = "Then turn in #INSeeping Corruption# and #INReturn to Apothecary Zinge# ... accept #GETVivian Lagrave# while you are there." },
			[17] = { str = "Then accept #GETSeeping Corruption# ... then turn it in (at the tauren right next to him) ..." },
			[18] = { str = "... Then complete #INSeeping Corruption# for the final time." },
			[19] = { str = "Then accept #GETA Sample of Slime...# and #GET... and a Batch of Ooze# " },
			[20] = { str = "Then fly to Raventusj Village..." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------50-50 Hinterlands
	--[502] = {
	[5050] = {
		title = "50-50 Hinterlands",
		--n = "50-50 Hinterlands",
		--pID = 501, nID = 503,
		--itemCount = 20,
		items = {
			[1] = { str = "50-50 Hinterlands" },
			[2] = { str = "Accept: #GETSnapjaws, Mon!# #GETGammerita, Mon!# (Elite) and #GETLard Lost His Lunch# " },
			[3] = { str = "Go do in the following order:" },
			[4] = { str = "#DOSnapjaws, Mon!# along with #DOGammerita, Mon!# and #DOWhiskey Slim's Lost Grog# " },
			[5] = { str = "#DOCortello's Riddle# at #COORD[80,46]#, little chest in the water, 14 slot bag along with 8800 XP", x = 80, y = 46, zone = "The Hinterlands" },
			[6] = { str = "#DOLard Lost His Lunch# at #COORD[84,42]#", x = 84, y = 42, zone = "The Hinterlands" },
			[7] = { str = "Then go turn in #INSnapjaws, Mon!# #INGammerita, Mon!# and #INLard Lost His Lunch# " },
			[8] = { str = "Then go do #DOSprinkle's Secret Ingredient# at #COORD[41,60]#", x = 41, y = 60, zone = "The Hinterlands" },
			[9] = { str = "Then hearth to Orgrimmar." },
			[10] = { str = "Fly to Azshara." },
			[11] = { str = "Turn in all 4 delivery quests." },
			[12] = { str = "Fly to XRs." },
			[13] = { str = "Make XRs your home." },
			[14] = { str = "Fly to Ratchet." },
			[15] = { str = "Pick up the #NPCStone Circle# at Liv Rizzlefix shop ... also accept #GETVolcanic Activity# while your there." },
			[16] = { str = "Get on the boat to go to BB" },
			[17] = { str = "Fly to Stonard (swamp of sorrows).." },
			[18] = { str = "Go into Blasted Lands..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

------------50-51 Blasted Lands
	--[503] = {
	[5051] = {
		title = "50-51 Blasted Lands",
		--n = "50-51 Blasted Lands",
		--pID = 502, nID = 504,
		--itemCount = 27,
		items = {
			[1] = { str = "50-51 Blasted Lands" },
			[2] = { str = "I then find all the items to complete these 5 quests:" },
			[3] = { str = "#DOA Boar's Vitality# " },
			[4] = { str = "#DOSnickerfang Jowls# " },
			[5] = { str = "#DOThe Basilisk's Bite# " },
			[6] = { str = "#DOThe Decisive Striker# " },
			[7] = { str = "#DOVulture's Vigor# " },
			[8] = { str = "You need to find these many items to complete these quests:" },
			[9] = { str = "#NPCVulture Gizzards# x14" },
			[10] = { str = "#NPCBasilisk Brain# x11" },
			[11] = { str = "#NPCBlasted Boar Lungs# x6" },
			[12] = { str = "#NPCScorpok Pincers# x6" },
			[13] = { str = "#NPCSnickerfang Jowls# x5" },
			[14] = { str = "While I'm in Blasted Lands, I discover most of all the areas for XP." },
			[15] = { str = "If an #NPCImperfect Draenethyst Fragment drops turn in for this quest: #INEverything Counts In Large Amounts# " },
			[16] = { str = "NOTE: I have NEVER found a #NPCFlawless Draenethyst Sphere# for the quest #INTo Serve Kum'isha# ..good luck on that." },
			[17] = { str = "Turn in all quests." },
			[18] = { str = "I turn in #INThe Decisive Striker# in last for Ground Scorpok Assay (+50 to agility)" },
			[19] = { str = "Then hearth to XRs." },
			[20] = { str = "Fly to Tanaris (GET A MITHRIL CASING for a later quest in Un'Goro!!!)" },
			[21] = { str = "Turn in #INSprinkle's Secret Ingredient# ... accept #GETDelivery for Marin# " },
			[22] = { str = "Turn in #INMarch of the Silithid# ... accept #GETBungle in the Jungle# " },
			[23] = { str = "Turn in #INDelivery for Marin# ...accept #GETNoggenfogger Elixir# then turn it in." },
			[24] = { str = "Go turn in #INThe Stone Circle# at #COORD[52,46]# in Tanaris", x = 52, y = 46, zone = "Tanaris" },
			[25] = { str = "Then go into Un'Goro Crater..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------51-52 Un'Goro Crater
	--[504] = {
	[5152] = {
		title = "51-52 Un'Goro Crater",
		--n = "51-52 Un'Goro Crater",
		--pID = 503, nID = 505,
		--itemCount = 56,
		items = {
			[1] = { str = "51-52 Un'Goro Crater" },
			[2] = { str = "Go accept: #GETThe Apes of Un'Goro# and #GETThe Fare of Lar'korwi# at #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[3] = { str = "Go do #DOThe Fare of Lar'korwi# at #COORD[68,56]#", x = 68, y = 56, zone = "Un'Goro Crater" },
			[4] = { str = "Then go start doing: #DOSuper Sticky# (up north in the middle) until this item drops #NPCA Mangled Journal#" },
			[5] = { str = "Then go into Marshal's Refuge #COORD[43,10]#, accept ALL quests there:  #GETChasing A-Me 01# #GETShizzle's Flyer# #GETLost!# #GETBeware of Pterrordax# #GETRoll the Bones# #GETAlien Ecology# #GETExpedition Salvation# #GETLarion and Muigin# ", x = 43, y = 10, zone = "Un'Goro Crater" },
			[6] = { str = "Turn in #INWilliden's Journal# " },
			[7] = { str = "Get FP there, then go do the Ungoro Grind :) ..." },
			[8] = { str = "NOTE: don't worry about the ungoro dirt mounds, you'll find enough soil from mob drops.  Also I don't worry about the Bloodpetal Sprouts, as they are not turned in for any XP." },
			[9] = { str = "While questing, find 7 crystals of each color (red, blue, green, and yellow for the #DOCrystals of Power# quest)" },
			[10] = { str = "#DOSuper Sticky# " },
			[11] = { str = "#DOThe Apes of Un'Goro# along with #DOChasing A-Me 01# (if you have a #NPCmithril casing# do the escort) #COORD[63,17]#", x = 63, y = 17, zone = "Un'Goro Crater" },
			[12] = { str = "#DOLarion and Muigin# " },
			[13] = { str = "#DOBeware of Pterrordax# along with #DOShizzle's Flyer# and.." },
			[14] = { str = "#DORoll the Bones# " },
			[15] = { str = "#DOExpedition Salvation# #COORD[68,36]# and #COORD[38,65]#", x = 68, y = 36, zone = "Un'Goro Crater" },
			[16] = { str = "#DO... and a Batch of Ooze# (I make sure I get at least 30 ooze samples)" },
			[17] = { str = "Go turn in #INThe Apes of Un'Goro# ... accept #GETThe Mighty U'cha# " },
			[18] = { str = "Turn in #INThe Fare of Lar'korwi# ... accept #GETThe Scent of Lar'korwi# " },
			[19] = { str = "Then go do:" },
			[20] = { str = "#DOBone-Bladed Weapons# along with #DOThe Scent of Lar'korwi# " },
			[21] = { str = "#GETIt's a Secret to Everybody# ... click on boat and then bag under water at #COORD[63,68]#", x = 63, y = 68, zone = "Un'Goro Crater" },
			[22] = { str = "Then turn in #INThe Scent of Lar'korwi# ... accept #GETThe Bait for Lar'korwi# #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[23] = { str = "Then go do #DOAlien Ecology# along with #DOBungle in the Jungle# #COORD[50,80]#", x = 50, y = 80, zone = "Un'Goro Crater" },
			[24] = { str = "Go accept #GETFinding the Source# at #COORD[30,50]#, then do it along with #DOVolcanic Activity# ", x = 30, y = 50, zone = "Un'Goro Crater" },
			[25] = { str = "The hotspot path for the quest #DOFinding the Source# starts at #COORD[51,42]# and the hot spot is at #COORD[50,46]#  (#VIDEOSee Video on where to find the hotspot#)", x = 51, y = 42, zone = "Un'Goro Crater" },
			[26] = { str = "#DOLost!# Make sure all quests are done before doing this (besides #NPCThe Mighty U'cha# and #NPCThe Bait for Lar'korwi# ), then..." },
			[27] = { str = "...This leads back to Marshal's Refuge, Turn in ALL quests there, accept new ones (including all the Pylon quests in the cave)." },
			[28] = { str = "Then go do (in the following order):" },
			[29] = { str = "#DOThe Northern Pylon# at #COORD[56,13]#", x = 56, y = 13, zone = "Un'Goro Crater" },
			[30] = { str = "#DOThe Mighty U'cha# cave at #COORD[63,13]#", x = 63, y = 13, zone = "Un'Goro Crater" },
			[31] = { str = "#DOThe Eastern Pylon# at #COORD[77,50]#", x = 77, y = 50, zone = "Un'Goro Crater" },
			[32] = { str = "#DOThe Bait for Lar'korwi# #COORD[80,50]#.  Then turn it in along with #INThe Mighty U'cha# #COORD[71,75]#", x = 71, y = 75, zone = "Un'Goro Crater" },
			[33] = { str = "Go west killing oozes along the way.." },
			[34] = { str = "Turn in #INFinding the Source# ... accept #GETThe New Springs# #COORD[30,50]#", x = 30, y = 50, zone = "Un'Goro Crater" },
			[35] = { str = "#DOThe Western Pylon# at #COORD[23,58]#", x = 23, y = 58, zone = "Un'Goro Crater" },
			[36] = { str = "Go back to Marshal's Refuge killing oozes along the way.." },
			[37] = { str = "Turn in quests. make sure you complete #DOMaking Sense of It# (just talk to the gnome in the cave)" },
			[38] = { str = "Fly to Tanaris." },
			[39] = { str = "Turn in #INSuper Sticky# and #INBungle in the Jungle# ... I SKIP #NPCPawn Captures Queen# " },
			[40] = { str = "Then fly to Thunder Bluff." },
			[41] = { str = "Go to Elder Rise." },
			[42] = { str = "Accept #GETUn'goro Soil# .. then turn it in ... accept #GETMorrowgrain Research# .. then turn that in..." },
			[43] = { str = "...but SKIP the next part (the part that says bring 10 Morrowgrain)" },
			[44] = { str = "Go get new spells/abilities." },
			[45] = { str = "Hearth to XRs." },
			[46] = { str = "Then fly to Ratchet.." },
			[47] = { str = "Turn in #INVolcanic Activity# and #INMarvon's Workshop# - I SKIP #NPCZapper Fuel# " },
			[48] = { str = "Get on the boat to go to BB.." },
			[49] = { str = "Turn in #INWhiskey Slim's Lost Grog# " },
			[50] = { str = "Also turn in #INRescue OOX-17/TN!# (if you did it)" },
			[51] = { str = "Fly to Kargath (Badlands).." },
			[52] = { str = "Turn in #INVivian Lagrave# " },
			[53] = { str = "Accept: #GETDreadmaul Rock# and #GETThe Rise of the Machines# " },
			[54] = { str = "Then fly to Burning Steppes..." },
			--[55] = { str = "." },
			--[56] = { str = "." },
		}
	},

-----------52-53 Burning Steppes
	--[505] = {
	[5253] = {
		title = "52-53 Burning Steppes",
		--n = "52-53 Burning Steppes",
		--pID = 504, nID = 506,
		--itemCount = 18,
		items = {
			[1] = { str = "52-53 Burning Steppes" },
			[2] = { str = "Accept: #GETBroodling Essence# and #GETTablet of the Seven# " },
			[3] = { str = "Then go do:" },
			[4] = { str = "#DOBroodling Essence# (to the east) (also kill as many dragon whelps you see, their squishy mobs that die real fast)" },
			[5] = { str = "#DODreadmaul Rock# #COORD[79,45]#... then #DOKrom'Grul# (Krom'Grul has 2 different spawn points, in either cave)", x = 79, y = 45, zone = "Burning Steppes" },
			[6] = { str = "#DOThe Rise of the Machines# " },
			[7] = { str = "#DOTablet of the Seven# it's at #COORD[54,40]#", x = 54, y = 40, zone = "Burning Steppes" },
			[8] = { str = "Go turn in #INTablet of the Seven# and #INBroodling Essence# ... accept #GETFelnok Steelspring# " },
			[9] = { str = "Then fly to Kargath (Badlands)" },
			[10] = { str = "Turn in #INKrom'Grul# " },
			[11] = { str = "Turn in #INThe Rise of the Machines# ... accept #GETThe Rise of the Machines# part2" },
			[12] = { str = "Go turn in #INThe Rise of the Machines# part2 at #COORD[25,46]# in Badlands", x = 25, y = 46, zone = "Badlands" },
			[13] = { str = "Then hearth to XRs." },
			[14] = { str = "Then fly to Orgrimmar and make it your home." },
			[15] = { str = "Go turn in #INBone-Bladed Weapons# #COORD[55,34]#", x = 55, y = 34, zone = "Orgrimmar" },
			[16] = { str = "Fly Azshara..." },
			--[17] = { str = "." },
			--[18] = { str = "." },
		}
	},

--------------53-54 Azshara
	--[506] = {
	[5354] = {
		title = "53-54 Azshara",
		--n = "53-54 Azshara",
		--pID = 505, nID = 507,
		--itemCount = 28,
		items = {
			[1] = { str = "53-54 Azshara" },
			[2] = { str = "Accept #GETBetrayed# " },
			[3] = { str = "Go turn in #INThe Hunter's Charm#, this is a hunter only quest, at #COORD[41,42]# ... accept #GETCourser Antlers# " },
			[4] = { str = "Go accept #GETKim'jael Indeed!# at #COORD[52,22]# on top of the hill", x = 52, y = 22, zone = "Azshara" },
			[5] = { str = "Then go do:" },
			[6] = { str = "#DOCourser Antlers# " },
			[7] = { str = "#DOBetrayed# " },
			[8] = { str = "#DOKim'jael Indeed!# " },
			[9] = { str = "NOTE: I grind away at bloodelfs for a while doing those 2 quests." },
			[10] = { str = "Once those 3 quests are done, go turn in #INKim'jael Indeed!# ... accept #GETKim'jael's Missing Equipment# " },
			[11] = { str = "Turn in #INCourser Antlers# ... accept #GETWavethrashing# " },
			[12] = { str = "Then go do:" },
			[13] = { str = "#DOKim'jael's Missing Equipment# " },
			[14] = { str = "#DOWavethrashing# " },
			[15] = { str = "Once both are done, Hearth to Orgrimmar." },
			[16] = { str = "Then Fly to Azshara.." },
			[17] = { str = "Turn in #INBetrayed# ... accept #GETBetrayed# " },
			[18] = { str = "Turn in #INWavethrashing# ... i SKIP #NPCThe Green Drake# " },
			[19] = { str = "Turn in #INKim'jael's Missing Equipment# " },
			[20] = { str = "At this point im usually about 3/4th the way to lvl 54, I grind my way to level 54 on BloodElfs." },
			[21] = { str = "I grind bloodelfs, cause their squishy mobs (mobs that have 30% fewer health/armor, than the average mob that level).  I used to grind satyrs on previous speed runs, but I was able to cut off almost a whole hour with the blood elfs." },
			[22] = { str = "OPTIONAL: Instead of the grinding you could go do BRD instance instead." },
			[23] = { str = "Once i hit 54 (or a few bars past it), i then hearth to Orgrimmar." },
			[24] = { str = "I then go turn in #INBone-Bladed Weapons# and #INBetrayed# " },
			[25] = { str = "Then fly to Splintertree Post (Ashenvale).." },
			[26] = { str = "Then go into Felwood..." },
			--[27] = { str = "." },
			--[28] = { str = "." },
		}
	},

-----------54-54 Felwood
	--[507] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 506, nID = 508,
		--itemCount = 16,
		items = {
			[1] = { str = "54-54 Felwood" },
			[2] = { str = "Accept #GETTimbermaw Ally# at #COORD[50,85]# (??? TBC Quest?) Just talk to the NPC there he will give it to you.", x = 50, y = 85, zone = "Felwood" },
			[3] = { str = "Go accept #GETForces of Jaedenar# and #GETVerifying the Corruption# at the Emerald Sanctuary #COORD[51,82]#.", x = 51, y = 82, zone = "Felwood" },
			[4] = { str = "Go accept #GETCleansing Felwood# at #COORD[46,84]#", x = 46, y = 84, zone = "Felwood" },
			[5] = { str = "I start killing oozes, I make sure I kill about 30/40 oozes here total for the quest #DOA Sample of Slime...# #COORD[40,68]#", x = 40, y = 68, zone = "Felwood" },
			[6] = { str = "Then go complete #DOForces of Jaedenar# #COORD[38,60]#", x = 38, y = 60, zone = "Felwood" },
			[7] = { str = "Then go to BloodVenom Post. #COORD[34,52]#", x = 34, y = 52, zone = "Felwood" },
			[8] = { str = "Accept: #GETA Husband's Last Battle# and #GETWild Guardians# " },
			[9] = { str = "Get FP there." },
			[10] = { str = "Then go do in the following order:" },
			[11] = { str = "#DOVerifying the Corruption# (Elite) #COORD[41,41]#", x = 41, y = 41, zone = "Felwood" },
			[12] = { str = "#DOCleansing Felwood# #COORD[54,16]#", x = 54, y = 16, zone = "Felwood" },
			[13] = { str = "Go accept #GETDeadwood of the North# (at 64.8) but DON'T do it now.", x = 64, y = 8, zone = "Felwood" },
			[14] = { str = "Grind your way through the cave to go to Winterspring..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------54-55 Winterspring
	--[508] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 507, nID = 509,
		--itemCount = 31,
		items = {
			[1] = { str = "54-55 Winterspring" },
			[2] = { str = "Exit the cave and accept #GETWinterfall Activity# right outside of it." },
			[3] = { str = "Go to Donova Snowden at #COORD[31,45]#", x = 31, y = 45, zone = "Winterspring" },
			[4] = { str = "Turn in #INThe New Springs# and #INIt's a Secret to Everybody# and accept #GETStrange Sources#" },
			[5] = { str = "NOTE: I SKIP #NPCThe Videre Elixir# and the rest of that chain." },
			[6] = { str = "Go to Everlook.. #COORD[61,38]#", x = 61, y = 38, zone = "Winterspring" },
			[7] = { str = "Accept: #GETAre We There, Yeti?# #GETThe Everlook Report# #GETDuke Nicholas Zverenhoff# #GETSister Pamela# #GETTrouble in Winterspring#and #GETUrsius of the Shardtooth#" },
			[8] = { str = "Turn in #INFelnok Steelspring# ... accept #GETChillwind Horns# " },
			[9] = { str = "Make Everlook your home." },
			[10] = { str = "Go do #DOUrsius of the Shardtooth#   (just keep grinding mobs on the hill north of everlook till #NPCUrsius# shows up)" },
			[11] = { str = "Then turn in #INUrsius of the Shardtooth# ... accept #GETBrumeran of the Chillwind# " },
			[12] = { str = "Go do #DOBrumeran of the Chillwind# he patrols around #COORD[60,60]#", x = 60, y = 60, zone = "Winterspring" },
			[13] = { str = "Then go Discover Darkwhisper Gorge at #COORD[59,73]# for the quest #DOStrange Sources# ", x = 59, y = 73, zone = "Winterspring" },
			[14] = { str = "Then hearth back to Everlook." },
			[15] = { str = "Turn in #INBrumeran of the Chillwind# ... SKIP #NPCShy-Rotam# " },
			[16] = { str = "Then go do the following quests (steps 17-20, in any order) to the west and some to the north. When you're at west remember to turn-in #INTrouble in Winterspring# and accept #GETThreat of the Winterfall#:" },
			[17] = { str = "#DOAre We There, Yeti?# " },
			[18] = { str = "#DOThreat of the Winterfall# you should find #NPCEmpty Firewater Flask# which starts #GETWinterfall Firewater# while doing this quest.  When the #NPCWinterfall Ritual Totem# item drops, save it and put it in your bank you will need it later." },
			[19] = { str = "#DOWild Guardians# (the Ragged Owls are west of Everlook, and the Raging Owls are just north of Everlook)" },
			[20] = { str = "#DOChillwind Horns#, you can find a larger concentration of chimaera around #COORD[66,29]#", x = 66, y = 29, zone = "Winterspring" },
			[21] = { str = "Once #DOThreat of the Winterfall# and #DOWinterfall Firewater# is completed go turn them in along with #INStrange Sources# at #COORD[31,45]#... accept #GETFalling to Corruption# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "Once the rest of those quests are complete, go back to Everlook and turn in #INAre We There, Yeti?# ...accept #GETAre We There, Yeti?# part2.  Turn in #INChillwind Horns# ... i SKIP #NPCReturn to Tinkee# " },
			[23] = { str = "Then go do:" },
			[24] = { str = "#DOWinterfall Activity# #COORD[67,37]#", x = 67, y = 37, zone = "Winterspring" },
			[25] = { str = "#DOAre We There, Yeti?# (find 2 Pristine Yeti Horns) #COORD[66,43]#", x = 66, y = 43, zone = "Winterspring" },
			[26] = { str = "Then hearth to Everlook and accept #GETA Strange One #" },
			[27] = { str = "Go turn in #INAre We There, Yeti?# ... accept #GETAre We There, Yeti?# part3" },
			[28] = { str = "Go scare Legacki with the mechanical yeti for the quest #DOAre We There, Yeti?# part3" },
			[29] = { str = "Then fly to Felwood..." },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

-----------55-55 Felwood
	--[509] = {
	[5554] = {
		title = "55-55 Felwood",
		--n = "55-55 Felwood",
		--pID = 508, nID = 510,
		--itemCount = 31,
		items = {
			[1] = { str = "55-55 Felwood" },
			[2] = { str = "Turn in #INWild Guardians# ... Accept #GETWild Guardians# part2 and #GETWell of Corruption#" },
			[3] = { str = "Go turn in #INCleansing Felwood# ... then get a cenarion beacon for the quest #DOSalve Via Hunting# (just talk to the NPC to get it) #COORD[46,83]#", x = 46, y = 83, zone = "Felwood" },
			[4] = { str = "Go turn in #INVerifying the Corruption# and #INForces of Jaedenar# ... accept #GETCollection of the Corrupt Water# #COORD[51,82]#", x = 51, y = 82, zone = "Felwood" },
			[5] = { str = "Go do in the following order:" },
			[6] = { str = "Go do #DOA Husband's Last Battle# along with #DOTimbermaw Ally# #COORD[48,94]#", x = 48, y = 94, zone = "Felwood" },
			[7] = { str = "Once they are done go turn in #INTimbermaw Ally# at #COORD[50,85]# ... accept #GETSpeak to Nafien#", x = 50, y = 85, zone = "Winterspring" },
			[8] = { str = "Go do #DOWell of Corruption# at #COORD[32,66]#.  Also make sure you collect 6 #NPCCorrupted Soul Shards# for the quest #DOSalve Via Hunting# ", x = 32, y = 66, zone = "Felwood" },
			[9] = { str = "#DOCollection of the Corrupt Water# #COORD[35,59]#", x = 35, y = 59, zone = "Felwood" },
			[10] = { str = "Then go to Bloodvenom Post" },
			[11] = { str = "Turn in #INA Husband's Last Battle# and #INWell of Corruption# ... accept #GETCorrupted Sabers# " },
			[12] = { str = "Go turn in #INSalve Via Hunting# (the 6 Corrupted Soul Shards) #COORD[46,83]#", x = 46, y = 83, zone = "Felwood" },
			[13] = { str = "Go turn in #INCollection of the Corrupt Water# ... I SKIP #NPCSeeking Spiritual Aid# #COORD[51,82]# ", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "Go do #DOCorrupted Sabers# #COORD[32,66]# then go turn it in.  (NOTE: when you turn it in, you have to talk to the cat first once you get to the NPC)", x = 32, y = 66, zone = "Felwood" },
			[15] = { str = "Then go up north and do:" },
			[16] = { str = "#DODeadwood of the North# (61.9)  When the Deadwood Ritual Totem item drops, save it and put it in your bank when you get a chance, you will need it later.", x = 61, y = 9, zone = "Felwood" },
			[17] = { str = "#DOFalling to Corruption# (the cauldron at 60.5) (hint: I have my pet distract the mobs, while doing this quest)   ... then accept #GETMystery Goo# ", x = 60, y = 5, zone = "Felwood" },
			[18] = { str = "Go turn in #INDeadwood of the North# (64.8) ... accept #GETSpeak to Salfa# .  And turn in #INSpeak to Nafien# ", x = 64, y = 8, zone = "Felwood" },
			[19] = { str = "Then run through the cave (you should be Unfriendly with Timbermaw, so they shouldn't attack you).." },
			[20] = { str = "Turn in #INWinterfall Activity# and #INSpeak to Salfa# " },
			[21] = { str = "Then go turn in #INMystery Goo# at #COORD[31,45]# in Winterspring ... SKIP #NPCToxic Horrors# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "Then hearth to Everlook." },
			[23] = { str = "Fly to Orgrimmar and make it your home." },
			[24] = { str = "If you happen to see #NPCWarcaller Gorlach#, accept #GETA Call To Arms: The Plaguelands!# " },
			[25] = { str = "Fly to Thunder Bluff, then directly to Camp Mojache, Ferelas" },
			[26] = { str = "Turn in #INThe Strength of Corruption# " },
			[27] = { str = "Then fly to Tanaris..." },
			[28] = { str = "Go scare #NPCSprinkle# with the mechanical yeti for the quest #DOAre We There, Yeti?# part3" },
			[29] = { str = "Then fly to Silithus" },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

------------55-55 Silithus
	--[510] = {
	[5555] = {
		title = "55-55 Silithus",
		--n = "55-55 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 25,
		items = {
			[1] = { str = "55-55 Silithus" },
			[2] = { str = "Accept: #GETThe Twilight Mystery# #GETSecuring the Supply Lines# and #GETDeadly Desert Venom# " },
			[3] = { str = "Go do: #DOSecuring the Supply Lines# and #DODeadly Desert Venom# (do these 2 quests northeast of Cenarion Hold)" },
			[4] = { str = "Then turn them in and accept new quests." },
			[5] = { str = "Then go do:" },
			[6] = { str = "#DOStepping Up Security# " },
			[7] = { str = "#DOThe Twilight Mystery# " },
			[8] = { str = "#DONoggle's Last Hope# " },
			[9] = { str = "Once all three of those are done, go turn them in accept new ones." },
			[10] = { str = "Go do:" },
			[11] = { str = "#DONoggle's Lost Satchel#, it's at around #COORD[40,90]#", x = 40, y = 90, zone = "Silithus" },
			[12] = { str = "NOTE: I skip #NPCWanted - Deathclasp, Terror of the Sands# (Elite) cause it's too hard to solo at 55, but do it if you can find a group." },
			[13] = { str = "#DOThe Deserter# He's in the cave at #COORD[67,71]# ... i SKIP #NPCThe Twilight Lexicon# ", x = 67, y = 71, zone = "Silithus" },
			[14] = { str = "Then i die on purpose, so i end up at Cenarion Hold." },
			[15] = { str = "Turn in #INNoggle's Lost Satchel# " },
			[16] = { str = "Then go to Marshal's Refuge in Un'Goro Crater." },
			[17] = { str = "Go scare Quixxil with the mechanical yeti for the quest #DOAre We There, Yeti?# part3" },
			[18] = { str = "Then hearth to Orgrimmar." },
			[19] = { str = "Go to the Under City." },
			[20] = { str = "Go complete #INA Sample of Slime...# and #IN... and a Batch of Ooze# " },
			[21] = { str = "Go accept #GETA Call To Arms: The Plaguelands!# " },
			[22] = { str = "Make Under City your home." },
			[23] = { str = "Go to the Bulwark... (which is a small village east of Tirisfal Glades)" },
			--[24] = { str = "." },
			--[25] = { str = "." },
		}
	},

-----------55-56 Western Plaguelands
	--[511] = {
	[5556] = {
		title = "55-56 Western Plaguelands",
		--n = "55-56 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 24,
		items = {
			[1] = { str = "55-56 Western Plaguelands" },
			[2] = { str = "Turn in #INA Call To Arms: The Plaguelands!# accept #GETScarlet Diversions# ..." },
			[3] = { str = "... (make sure you get a Flame in a Bottle first, before doing this quest, it's in the box)" },
			[4] = { str = "Turn in #INThe Everlook Report# " },
			[5] = { str = "Accept and complete #DOArgent Dawn Commission# " },
			[6] = { str = "Accept #GETA Plague Upon Thee# " },
			[7] = { str = "Go into the Western Plaguelands, Felstone field at #COORD[37,56]# and...", x = 37, y = 56, zone = "Western Plaguelands" },
			[8] = { str = "Accept #GETBetter Late Than Never# (the lady in the house)" },
			[9] = { str = "Then go to the barn next door, and..." },
			[10] = { str = "Complete #DOBetter Late Than Never# .. click on the chest again to accept #GETBetter Late Than Never# again." },
			[11] = { str = "Go do #DOScarlet Diversions#, burn the tent down, and plant the banner #COORD[40,51]#  ", x = 40, y = 51, zone = "Western Plaguelands" },
			[12] = { str = "Go back to the Bulwark..  (#VIDEONOTE:# Make sure you save all #NPCBone Fragments# you find, you will need 30 of them for a later #NPCquest#)" },
			[13] = { str = "Turn in #INScarlet Diversions# ... accept #GETAll Along the Watchtowers# (Elite) and #GETThe Scourge Cauldrons# " },
			[14] = { str = "Turn in #INThe Scourge Cauldrons# ... accept #GETTarget: Felstone Field# " },
			[15] = { str = "Go complete the whole Cauldron quest chain, you need to kill the Cauldron Lord at each targeted field (listed below), grab their key and use it at the big cauldron in the middle of the field.  (Just keep going back and forth from The Bulwark to the next field completing each one, turning them in and then accepting and doing the next one)..." },
			[16] = { str = "#DOTarget: Felstone Field# #COORD[37,56]#", x = 37, y = 56, zone = "Western Plaguelands" },
			[17] = { str = "#DOTarget: Dalson's Tears# #COORD[46,52]#.  #VIDEONOTE:#  While you are here, there is a small quest chain here that starts with a little Diary in the barn #COORD[47,50]# called #INMrs. Dalson's Diary# , just click that to complete the quest.  Now, after you did that, then you need to kill a #NPCWandering Skeleton# to get a key that opens the outhouse behind the barn. After you get the key and open the outhouse, it will release a #NPCFarmer Dalson#, a level 56 undead. Kill him, grab that key, and then run in the house (that is right next to the barn) and go up the stairs, there you will find a cabinet, open the cabinet with that key (For the quest #DOLocked Away# ) and finally it's over.  Easy 10200 XP!  Or was it?", x = 46, y = 52, zone = "Western Plaguelands" },
			[18] = { str = "#DOTarget: Writhing Haunt# #COORD[53,65]# (while you're there accept #GETThe Wildlife Suffers Too# at #COORD[53,64]#, the almost dead tauren in the hut", x = 53, y = 65, zone = "Western Plaguelands" },
			[19] = { str = "#DOTarget: Gahrron's Withering# #COORD[62,59]#", x = 62, y = 59, zone = "Western Plaguelands" },
			[20] = { str = "Just keep going back and forth completing each one." },
			[21] = { str = "Then go accept and complete #DOMission Accomplished!# " },
			[22] = { str = "Then head into Eastern Plaguelands..." },
			--[23] = { str = "." },
			--[24] = { str = "." },
		}
	},

-----------56-57 Eastern Plaguelands
	--[512] = {
	[5657] = {
		title = "56-57 Eastern Plaguelands",
		--n = "56-57 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 38,
		items = {
			[1] = { str = "56-57 Eastern Plaguelands" },
			[2] = { str = "Go accept: #GETDemon Dogs# #GETBlood Tinged Skies# and #GETCarrion Grubbage# (at 7.43)", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "Grind your way to #COORD[26,74]# and accept: #GETTo Kill With Purpose# and #GETUn-Life's Little Annoyances# .  NOTE: I SKIP #NPCThe Ranger Lord's Behest# ", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[4] = { str = "Go down in the crypt at The Undercroft #COORD[27,85]# and accept #GETHameya's Plea# (the scroll on the ground). (??? TBC Quest?)", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[5] = { str = "Grind your way to Darrowshire #COORD[36,90]# while doing these quests:", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[6] = { str = "#DODemon Dogs# " },
			[7] = { str = "#DOBlood Tinged Skies# " },
			[8] = { str = "#DOCarrion Grubbage# " },
			[9] = { str = "Then turn in #INSister Pamela# ... accept and do #GETPamela's Doll# (there's 3 parts of the doll)" },
			[10] = { str = "Turn in #INPamela's Doll# ... accept #GETAuntie Marlene# and #GETUncle Carlin# " },
			[11] = { str = "Then go complete #DOBlood Tinged Skies# " },
			[12] = { str = "Then make sure you kill 20 Plaguehound Runts for the quest #DODemon Dogs# " },
			[13] = { str = "Then go to Light's Hope Chapel at #COORD[81,60]#", x = 81, y = 60, zone = "Eastern Plaguelands" },
			[14] = { str = "Accept: #GETZaeldarr the Outcast# and #GETThe Restless Souls# " },
			[15] = { str = "Turn in #INDuke Nicholas Zverenhoff# and #INUncle Carlin# ... accept #GETDefenders of Darrowshire# " },
			[16] = { str = "Get FP there.  Then go do:" },
			[17] = { str = "#DOTo Kill With Purpose# " },
			[18] = { str = "#DODefenders of Darrowshire# " },
			[19] = { str = "#DOHameya's Plea# #COORD[72,14]# (??? TBC Quest?)", x = 72, y = 14, zone = "Eastern Plaguelands" },
			[20] = { str = "#DODemon Dogs# " },
			[21] = { str = "#DOCarrion Grubbage# " },
			[22] = { str = "#DOUn-Life's Little Annoyances# " },
			[23] = { str = "#DOA Plague Upon Thee# (done at Plaguewood up north)" },
			[24] = { str = "#DOAugustus' Receipt Book# get this quest in the hut at #COORD[13,34]#, the book is upstairs in the inn at #COORD[15,33]#", x = 15, y = 33, zone = "Eastern Plaguelands" },
			[25] = { str = "#DOThe Restless Souls# (#NPCEgan# is in the hut at #COORD[13,34]#) (The next part refers to Stratholme, which I skip)", x = 13, y = 34, zone = "Eastern Plaguelands" },
			[26] = { str = "Then go turn in: #INAugustus' Receipt Book# " },
			[27] = { str = "Grind your way through the cave #COORD[15,29]# (watch out it is not easy) ", x = 15, y = 29, zone = "Eastern Plaguelands" },
			[28] = { str = "#VIDEONOTE:#  If the cave is too hard for you, another easy alternative is to take the Tower Gryphon ride from the Plaguewood Tower #COORD[22,32]# to the Crown Guard tower #COORD[39,75]#, as long as the horde has control over the towers that is.  Then turn in #INDemon Dogs# #INBlood Tinged Skies# and #INCarrion Grubbage#   accept #GETRedemption#   ... Just talk to the guy to complete it ... I SKIP #NPCOf Forgotten Memories# (you can try it if you find a group)", x = 22, y = 32, zone = "Eastern Plaguelands" },
			[29] = { str = "Then go turn in: #INTo Kill With Purpose# and #INUn-Life's Little Annoyances# at #COORD[26,74]#", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[30] = { str = "Then go do #DOZaeldarr the Outcast# #COORD[27,85]#", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[31] = { str = "Then go to the dirt mound behind the crypt and turn in #INHameya's Plea# (??? TBC Quest?)" },
			[32] = { str = "Then turn in: #INZaeldarr the Outcast# and #INDefenders of Darrowshire# at Light's Hope Chapel" },
			[33] = { str = "Hearth to Under City.." },
			[34] = { str = "Turn in #INBetter Late Than Never# ... accept #GETThe Jeremiah Blues# " },
			[35] = { str = "Turn in #INThe Jeremiah Blues# (just right underneath the bank) ... accept #GETGood Luck Charm# " },
			[36] = { str = "Go back to the Bulwark..." },
			--[37] = { str = "." },
			--[38] = { str = "." },
		}
	},

-----------57-58 Western Plaguelands
	--[513] = {
	[5758] = {
		title = "57-58 Western Plaguelands",
		--n = "57-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 37,
		items = {
			[1] = { str = "57-58 Western Plaguelands" },
			[2] = { str = "Turn in #INA Plague Upon Thee# ... accept #GETA Plague Upon Thee# part2." },
			[3] = { str = "Go turn in #INGood Luck Charm# ...accept #GETTwo Halves Become One# The lady in the house at #COORD[37,56]#", x = 37, y = 56, zone = "Western Plaguelands" },
			[4] = { str = "Do #DOTwo Halves Become One# (#NPCJabbering ghouls# out in Felstone Field drop the item you need, once you get the item right-click it in your inventory), then go back to the lady in the house to turn it in." },
			[5] = { str = "Then do #DOA Plague Upon Thee# part2 ... accept #GETA Plague Upon Thee# part3, this is all done at #COORD[48,31]#  " },
			[6] = { str = "Then go accept #GETUnfinished Business# part1 at #COORD[51,28]#, then do it. The mobs for this quest are at #COORD[50,42]# and #COORD[53,44]#", x = 51, y = 28, zone = "Western Plaguelands" },
			[7] = { str = "Turn in #INUnfinished Business# part1 (back at #COORD[51,28]#) ... accept #GETUnfinished Business# part2, then go do it. The 2 mobs for this quest are at #COORD[57,37]# and #COORD[54,24]#.", x = 55, y = 30, zone = "Western Plaguelands" },
			[8] = { str = "Turn in #INUnfinished Business# part2 (back at #COORD[51,28]#) ... accept #GETUnfinished Business# part3, then go do it. Need to go up in the tower at #COORD[45,19]# in a certain spot, watch out for Elites.", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "Then turn in #INUnfinished Business# part3" },
			[10] = { str = "Then go complete and turn in #INThe Wildlife Suffers Too# ... accept  #GETThe Wildlife Suffers Too# part2 #COORD[53,64]#", x = 53, y = 64, zone = "Western Plaguelands" },
			[11] = { str = "Do #DOThe Wildlife Suffers Too# part2, then turn it in ... accept #GETGlyphed Oaken Branch# " },
			[12] = { str = "Go turn in #INAuntie Marlene#, in the house at #COORD[49,78]#  ...accept #GETA Strange Historian# ", x = 49, y = 78, zone = "Western Plaguelands" },
			[13] = { str = "Go get the ring for #DOA Strange Historian# (the ring is out in the graveyard)" },
			[14] = { str = "Go into Andorhal.." },
			[15] = { str = "Do #DOAll Along the Watchtowers# while working your way to the inn at #COORD[39,66]#", x = 39, y = 66, zone = "Western Plaguelands" },
			[16] = { str = "Turn in #INA Strange Historian# at #NPCChromie# up stairs in the inn at #COORD[39,68]# ... accept #GETThe Annals of Darrowshire# and #GETA Matter of Time# ", x = 39, y = 68, zone = "Western Plaguelands" },
			[17] = { str = "Then go do (while grinding away at mobs):" },
			[18] = { str = "#DOAll Along the Watchtowers# (Elite) " },
			[19] = { str = "#DOA Matter of Time# #COORD[47,62]#", x = 47, y = 62, zone = "Western Plaguelands" },
			[20] = { str = "#DOThe Annals of Darrowshire# the book for this is in the building at #COORD[42,67]#, the actual Annals of Darrowshire book looks different from the others, it has a lighter tint on the top portion of the pages in the book, unlike the rest which has a darker tint on the top portion of the pages.", x = 42, y = 67, zone = "Western Plaguelands" },
			[21] = { str = "Go turn in #INA Matter of Time# and #INThe Annals of Darrowshire# ... accept #GETCounting Out Time# and #GETBrother Carlin# " },
			[22] = { str = "Go do #DOCounting Out Time# then turn it in. (it's repeatable but you only get XP once from it)" },
			[23] = { str = "I then keep grinding away at mobs in Andorhal till i'm Friendly with the Argent Dawn, so im able to buy Enriched Manna Biscuits (which replenish mana faster from drinking). As soon as I hit friendly with AD, I then go back to the Bulwark.." },
			[24] = { str = "Turn in #INA Plague Upon Thee# part3" },
			[25] = { str = "Turn in #INAll Along the Watchtowers# ... accept #GETScholomance# " },
			[26] = { str = "Turn in #INScholomance# at the undead guy right next to him ... accept #GETSkeletal Fragments# " },
			[27] = { str = "Stock up on #NPCEnriched Manna Biscuits# (which replenishes mana faster from drinking)" },
			[28] = { str = "I then go back to Andorhal, and grind all the way to level 58 while doing #DOSkeletal Fragments# quest." },
			[29] = { str = "As soon as I hit 58 and #DOSkeletal Fragments# is done and you also have 30 #NPCBone Fragments# (please note, if you are far off from the 30 bone fragments, then you can just skip it), then go back to the Bulwark and turn in #INSkeletal Fragments# .. I SKIP #NPCMold Rhymes With...# " },
			[30] = { str = "I turn in any scourge stones, I have." },
			[31] = { str = "I then stock up on #NPCEnriched Manna Biscuits# (about 600? :D)" },
			[32] = { str = "Then go get on the zeppelin to go to Orgrimmar. (while waiting, make heavy runecloth bandages)" },
			[33] = { str = "Once in Orgrimmar i get new spells/abilites." },
			[34] = { str = "Bank 2/3rd of my manna biscuits." },
			[35] = { str = "Then fly to Winterspring..." },
			--[36] = { str = "." },
			--[37] = { str = "." },
		}
	},

------------58-60 Winterspring
	--[514] = {
	[5860] = {
		title = "58-60 Winterspring",
		--n = "58-60 Winterspring",
		--pID = 513, nID = 514,
		--itemCount = 32,
		items = {
			[1] = { str = "58-60 Winterspring" },
			[2] = { str = "First thing i do here is stable my pet." },
			[3] = { str = "Then make Everlook your home." },
			[4] = { str = "Turn in #INAre We There, Yeti?# part3" },
			[5] = { str = "Accept: #GETLuck Be With You# (Elite) and #GETUrsius of the Shardtooth# (Elite)" },
			[6] = { str = "Then go tame a Winterspring Screecher (for Claw Rank8) (head south to do this)" },
			[7] = { str = "Then use that pet to do #DOLuck Be With You# (just use your pet to distract the giants while picking up the Frostmaul Shards)" },
			[8] = { str = "Then hearth to Everlook." },
			[9] = { str = "Go do #DOUrsius of the Shardtooth# (Elite) (just keep grinding mobs on the hill north of everlook till Ursius shows up)" },
			[10] = { str = "Go turn in #INLuck Be With You# (if it's done yet) and #INUrsius of the Shardtooth# ... accept #GETBrumeran of the Chillwind# (Elite)" },
			[11] = { str = "Then go south and do:" },
			[12] = { str = "#DOBrumeran of the Chillwind# (Elite)" },
			[13] = { str = "#DOLuck Be With You# (Elite) (if you still need to finish it up)" },
			[14] = { str = "#DOWild Guardians# part2 (i grind away at owls at the Owl Wing Thicket for a few hours, before leaving here)" },
			[15] = { str = "Then when im a few bars away from 59, i go back up to Everlook (DONT hearth).." },
			[16] = { str = "Turn in #INLuck Be With You# and #INBrumeran of the Chillwind# ... i SKIP #NPCShy-Rotam# (Elite)" },
			[17] = { str = "Fly to Bloodvenom Post (Felwood).." },
			[18] = { str = "Turn in #INWild Guardians# part2 ... accept #GETWild Guardians# part3" },
			[19] = { str = "Then hearth back to Everlook." },
			[20] = { str = "Then go down to the Owl Wing Thicket and do #DOWild Guardians# part3" },
			[21] = { str = "I keep grinding away at Owls till im about 59 and a half, then..." },
			[22] = { str = "I die on purpose, so i end up at Everlook (don’t hearth)" },
			[23] = { str = "Then Fly to Bloodvenom Post (Felwood).." },
			[24] = { str = "Turn in #INWild Guardians# part3 and #INGuarding Secrets# ... accept #GETGuarding Secrets# part2" },
			[25] = { str = "I then fly to XRs, then to Thunderbluff, go to Elder Rise.." },
			[26] = { str = "Turn in #INGuarding Secrets# part2 and #INGlyphed Oaken Branch# (both at Nara Wildmane)" },
			[27] = { str = "Hearth back to Everlook." },
			[28] = { str = "At this point im usually about 3/4 way to 60." },
			[29] = { str = "I then go back down to the Owl Wing Thicket and Grind to 60.  (See End Game Credits)" },
			[30] = { str = "." },
			[31] = { str = "." },
			[32] = { str = "CONGRATULATION, you're lvl60 now!"},
			[33] = { str = "." },
			--[34] = { str = "." },
		}
	},
}
