local L = AceLibrary("AceLocale-2.2"):new("MikScrollingBattleText")

L:RegisterTranslations("ruRU", function()
    return {
		["Debug mode has been enabled."] = "Debug mode включен.",
		["Debug mode has been disabled."] = "Debug mode выключен.",
		["Event search mode has been enabled.  Searching for: "] = "Поиск событий включен. Поиск: ",
		["Event search mode has been disabled."] = "Поиск событий выключен.",
		["The mod is now disabled."] = "Мод выключен",
		["The mod is now enabled."] = "Мод включен",
		["Hits"] = "Попадания",
		["Crit"] = "Критический удар",
		["Crits"] = "Критические удары",
		["Multiple"] = "Несколько",
		[" (%d vulnerability)"] = " (%d уязвимость)",
		[" <\124cff00b37e\124h%d\124h\124r>"] = " <\124cff00b37e\124h%d\124h\124r>",
		["Profile Reset"] = "Сброс профиля",
		["Drowning"] = "Тонет",
		["Falling"] = "Падение",
		["Fatigue"] = "Усталость",
		["Fire"] = "Огонь",
		["Lava"] = "Лава",
		["Slime"] = "Слизь",
		["Windfury!"]="Неистовство ветра!",
		["Low Mana! (%1)"]="Мало маны! (%1)",
		["Low Pet Health! (%1)"]="Мало здоровья питомца! (%1)",
		["%a CP Finish It!"]="%a СП Используй!",
		["+Combat"]="+Бой",
		["-Combat"]="-Бой",
		["%a CP"]="%a СП",
		["Pet "]="Питомец ",
		["Pet %a (%s)"]="Питомец %a \"(%s)\"",
		["Pet %a"]="Питомец %a",
		["-%a (Pet)"]="-%a (Питомец)",
		["! (Pet)"]="! (Питомец)",
		["+%a (%n) (Pet)"]="+%a (%n) (Питомец)",
		["Killing Blow! (%s)"]="Смертельный удар! (%s)",
		["Low Health! (%1)"]="Мало здоровья! (%1)",
    }
end)