local L = AceLibrary("AceLocale-2.2"):new("MikScrollingBattleText")

L:RegisterTranslations("enUS", function()
    return {
		["Debug mode has been enabled."] = true,
		["Debug mode has been disabled."] = true,
		["Event search mode has been enabled.  Searching for: "] = true,
		["Event search mode has been disabled."] = true,
		["The mod is now disabled."] = true,
		["The mod is now enabled."] = true,
		["Hits"] = true,
		["Crit"] = true,
		["Crits"] = true,
		["Multiple"] = true,
		[" (%d vulnerability)"] = true,
		[" <\124cff00b37e\124h%d\124h\124r>"] = true,
		["Profile Reset"] = true,
		["Drowning"] = true,
		["Falling"] = true,
		["Fatigue"] = true,
		["Fire"] = true,
		["Lava"] = true,
		["Slime"] = true,
		["Windfury!"]="Windfury!",
		["Low Mana! (%1)"]="Low Mana! (%1)",
		["Low Pet Health! (%1)"]="Low Pet Health! (%1)",
		["%a CP Finish It!"]="%a CP Finish It!",
		["+Combat"]="+Combat",
		["-Combat"]="-Combat",
		["%a CP"]="%a CP",
		["Pet "]="Pet ",
		["Pet %a (%s)"]="Pet %a (%s)",
		["Pet %a"]="Pet %a",
		["-%a (Pet)"]="-%a (Pet)",
		["! (Pet)"]="! (Pet)",
		["+%a (%n) (Pet)"]="+%a (%n) (Pet)",
		["Killing Blow! (%s)"]="Killing Blow! (%s)",
		["Low Health! (%1)"]="Low Health! (%1)",
    }
end)