--[[--------------------------------------------------
003_Alliance_40to50.lua
Authors: mrmr
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
    1.04.1
        -- First Release
            Alliance's Guide
            from level 40 to lever 50
    1.04.2
    	-- no changes in here for this revision
	1.04.3
		-- Added color codes
			Fixed various spelling errors
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "40-41 Badlands",
		--n = "40-41 Badlands",
		--pID = 312, nID = 402,
		--itemCount = 32,
		items = {
			[1] = { str = "40-41 Badlands" },
			[2] = { str = "Go to 53,43 accept #ACCEPT“Fiery Blaze Enchantment”#, #ACCEPT“Mirages”#, and #ACCEPT“A Dwarf and His Tools”#", x = 53, y = 43, zone = "Badlands" },
			[3] = { str = "Stop at 42,52 and hand in #TURNIN“Martek the Exiled”# accept #ACCEPT“Indurium”#", x = 45, y = 52, zone = "Badlands" },
			[4] = { str = "Accept #ACCEPT“Barbecued Buzzard Wings”#, #ACCEPT“Pearl Diving”# (if you have them)" },
			[5] = { str = "Now there's only one area for buzzards. So for the 2 quests that require their items, kill them whenever you see one." },
			[6] = { str = "Go to 25,44 and accept #ACCEPT“Study of the Elements: Rock pt.1”# and #ACCEPT“Coolant Heads Prevail”# then turn it back in and accept #ACCEPT“Gyro… What?”# then turn that back in. ", x = 25, y = 44, zone = "Badlands" },
			[7] = { str = "Accept #ACCEPT“Liquid Stone”# then turn it back in" },
			[8] = { str = "Grind down to 66,21 and open the crate for #DOQUEST“Mirages”#", x = 66, y = 21, zone = "Badlands" },
			[9] = { str = "Grind over to the dig site at 53,29 and kill the dwarfs for #DOQUEST“A Dwarf and His Tools”# On the right side of the hole at 53,33 touch the note in the tent for #DOQUEST“A Sign of Hope”#", x = 53, y = 29, zone = "Badlands" },
			[10] = { str = " Grind up to 53,43 and hand in #TURNIN“Mirages”# accept #ACCEPT“Scrounging”#", x = 53, y = 43, zone = "Badlands" },
			[11] = { str = "Also turn in #TURNIN“A Dwarf and His Tools”# and #TURNIN“A Sign of Hope”# accept the next part to Uldaman" },
			[12] = { str = "Grind down to 61,54 and accept #ACCEPT“Tremors of the Earth”# The ogres spawn at 62,70 and wander to 29,56 so kill them if you see them. The boss is easy to pull off the back, with the small add or none.", x = 61, y = 54, zone = "Badlands" },
			[13] = { str = "Go south to 62,70 and kill ogres here for #DOQUEST“Scrounging”# and hopefully the boss is here. There isn’t many ogres so don’t worry ", x = 62, y = 70, zone = "Badlands" },
			[14] = { str = "Grind to 50,62, turn in #TURNIN“Find Agmond”# accept #ACCEPT“Murdaloc”#", x = 50, y = 62, zone = "Badlands" },
			[15] = { str = "Go just south to the gnoll camp and do #DOQUEST“Murdaloc”# and #DOQUEST“Indurium”#" },
			[16] = { str = "Go up to 42,52 and turn in #TURNIN“Barbecued Buzzard Wings”# and #TURNIN“Indurium”# accept #ACCEPT“News for Fizzle”#", x = 45, y = 52, zone = "Badlands" },
			[17] = { str = "Go to 18,41 and kill the lesser rock elementals for #DOQUEST“Study of the Elements: Rock pt.1”# and #DOQUEST“Badlands Reagent Run”#", x = 18, y = 41, zone = "Badlands" },
			[18] = { str = "Go back to 26,44 turn in #TURNIN“Study of the Elements: Rock pt.1”# accept #ACCEPT“Study of the Elements: Rock pt.2”# and do it by killing rock elementals", x = 26, y = 44, zone = "Badlands" },
			[19] = { str = "Go back to 26,44 turn in #TURNIN“Study of the Elements: Rock pt.2”# accept #ACCEPT“Study of the Elements: Rock pt.3”#", x = 26, y = 44, zone = "Badlands" },
			[20] = { str = "Kill buzzards around 15,60 and coyotes around 33,62 for #DOQUEST“Badlands Reagent Run”# if you still need them", x = 33, y = 62, zone = "Badlands" },
			[21] = { str = "Grind down to 11,77 and kill ogres for #DOQUEST“Scrounging”#", x = 11, y = 77, zone = "Badlands" },
			[22] = { str = "Kill greater rock elementals at 14,88 for #DOQUEST“Study of the Elements: Rock#", x = 14, y = 88, zone = "Badlands" },
			[23] = { str = "Go back to 26,44 turn in #TURNIN“Study of the Elements: Rock pt.3”# accept #ACCEPT“This Is Going To Be Hard pt.1”# turn around and hand it in, accept #ACCEPT“This Is Going To Be Hard pt.2”# then turn around and hand it in, accept #ACCEPT“This Is Going To Be Hard pt.3”#", x = 26, y = 44, zone = "Badlands" },
			[24] = { str = "Kill the elemental that’s summoned, he’s level 45. Then turn it back in to get your Nifty Stopwatch" },
			[25] = { str = "Go to 53,43 and turn in #TURNIN“Scrounging”#", x = 53, y = 43, zone = "Badlands" },
			[26] = { str = "Go to 61,54 and turn in #TURNIN“Tremors of the Earth”# SKIP the next part", x = 61, y = 54, zone = "Badlands" },
			[27] = { str = "Now you should be level 41, if you’re not go east into the ravine and kill the whelps until you level. I usually go here and grind for at least 30 min whether or not im 41 and try to get the heart for #DOQUEST“Fiery Blaze Enchantment”# If you don’t find it in 30 min just abandon it" },
			[28] = { str = "Hearth to Thelsamar" },
			[29] = { str = "Go in the house behind the Inn and turn in #TURNIN“Badlands Reagent Run”# accept the Uldaman part" },
			[30] = { str = "Run to 65,65 turn in #TURNIN“Murdaloc”# accept the Uldaman part. I’m almost 25% into 41 now", x = 65, y = 65, zone = "Loch Modan" },
			[31] = { str = "Fly to Duskwood, make it your home. Fly to SW Go to 64,20 and accept #ACCEPT“In Search of The Temple”#", x = 64, y = 20, zone = "Stormwind" },
			[32] = { str = "Fly back to Duskwood, Run into Swamp of Sorrows" },
		}
	},

-----------41-41 Swamp of Sorrows
	--[402] = {
	[4141] = {
		title = "41-41 Swamp of Sorrows",
		--n = "41-41 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 27,
		items = {
			[1] = { str = "41-41 Swamp of Sorrows" },
			[2] = { str = "Run into the Swamp of Sorrows, go to 12,58 and kill the whelps for #DOQUEST“Dream Dust In the Swamp”# low droprate but they respawn fast", x = 12, y = 58, zone = "Swamp of Sorrows" },
			[3] = { str = "Go to 26,59 and accept #ACCEPT“Enroaching Wildlife”# and go do it. Kill the 3 mob types around him and north. It’s all close to the quest giver", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[4] = { str = "Go up and find Noboru the Cudgel he circles around 43,38 and drops an item that starts #ACCEPT“Noboru the Cudgel”#", x = 43, y = 38, zone = "Swamp of Sorrows" },
			[5] = { str = "Go back to 26,59 and turn in #TURNIN“Enroaching Wildlife”# accept #ACCEPT“The Lost Caravan”#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[6] = { str = "Grind up to 25,31 and turn in #TURNIN“Noboru the Cudgel”# accept #ACCEPT“Draenethyst Crystals”#", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[7] = { str = "Go up to the sanctuary that starts at 54,29 and start collecting the #DOQUEST“Draenethyst Crystals”#", x = 54, y = 29, zone = "Swamp of Sorrows" },
			[8] = { str = "When you get to the last camp with the npc in the cage at 65,18 first grab the chest off the cart to the left for #DOQUEST“The Lost Caravan”#", x = 65, y = 18, zone = "Swamp of Sorrows" },
			[9] = { str = "Make sure you clear the camp beside the caged npc." },
			[10] = { str = "Then accept #ACCEPT“Galen’s Escape”# it’s a breeze if you cleared the camp" },
			[11] = { str = "Grind down to 48,39 to the busted up looking tent and open the chest to complete #DOQUEST“Galen’s Escape”#", x = 48, y = 39, zone = "Swamp of Sorrows" },
			[12] = { str = "Go back to 26,31 and turn in #TURNIN“Draenethyst Crystals”#", x = 26, y = 31, zone = "Swamp of Sorrows" },
			[13] = { str = "Go to 26,59 and turn in #TURNIN“The Lost Caravan”# accept #ACCEPT“Driftwood”#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[14] = { str = "Run through the swamp and go south into the Blasted Lands at 36,59 and over to Nethergarde Keep at 54,78. Grab the FP and fly to Darkshire.", x = 54, y = 78, zone = "Blasted Lands" },
			[15] = { str = "Stable your cat and get the Badlands cat back out" },
			[16] = { str = "Accept #ACCEPT“Supplies for Nethergarde”# on your way back NE" },
			[17] = { str = "Fly back to Nethergarde, turn in #TURNIN“Supplies for Nethergarde”# easy xp." },
			[18] = { str = "Run back up into the Swamp of Sorrows." },
			[19] = { str = "Run up to the lake around the Sunken Temple at 70,54 and you should get a complete message for #DOQUESTIn Search of The Temple#", x = 70, y = 54, zone = "Swamp of Sorrows" },
			[20] = { str = "Go up to about 76,6 and start killing silt and monstrous crawlers and work your way south for #DOQUEST“… and bugs”# until it’s done. Also look for wood planks on the ground for #DOQUEST“Driftwood”#", x = 76, y = 6, zone = "Swamp of Sorrows" },
			[21] = { str = "Hearth to Darkshire and get your cat back out." },
			[22] = { str = "Fly to Nethergarde and run back up into the Swamp" },
			[23] = { str = "Go to 26,59 and turn in #TURNIN“Driftwood”# accept #ACCEPT“Deliver the Shipment”#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[24] = { str = "Run down into the Blasted Lands and turn in #TURNIN“Deliver the Shipment”# at 66,21", x = 66, y = 21, zone = "Blasted Lands" },
			[25] = { str = "Fly to BB and turn in #TURNIN“Dream Dust In the Swamp”# atop the Inn and accept #ACCEPT“Rumors for Kravel”#" },
			[26] = { str = "Get on the ship to Rachet and fly to Theramore and turn in #TURNIN“… and bugs”# at the Inn" },
			[27] = { str = "Fly to Desolace" },
		}
	},

-----------41-42 Desolace
	--[403] = {
	[4142] = {
		title = "41-42 Desolace",
		--n = "41-42 Desolace",
		--pID = 402, nID = 404,
		--itemCount = 16,
		items = {
			[1] = { str = "41-42 Desolace" },
			[2] = { str = "Make Nijel’s Point your home" },
			[3] = { str = "Accept #ACCEPT“Down the Scarlet Path”#" },
			[4] = { str = "Go down accept #ACCEPT“Reagents For Reclaimers Inc pt.3”#" },
			[5] = { str = "Run to 47,61 and accept #ACCEPT“Ghost-O-Plasm Round Up”#", x = 47, y = 61, zone = "Desolace" },
			[6] = { str = "Kill the demons around 51,75 for #DOQUEST“Reagents For Reclaimers Inc pt.3”#", x = 51, y = 75, zone = "Desolace" },
			[7] = { str = "Kill undead ravagers around 61,90 for #DOQUEST“Down the Scarlet Path”# and #DOQUEST“Ghost-O-Plasm Round Up”# between the 2 skeletons in the middle", x = 61, y = 90, zone = "Desolace" },
			[8] = { str = "You should hit level 42 by the time you’re done kililng these" },
			[9] = { str = "Go back to 47,61 and turn in #TURNIN“Ghost-O-Plasm Round Up”#", x = 47, y = 61, zone = "Desolace" },
			[10] = { str = "Hearth to Nijel’s Point" },
			[11] = { str = "Turn in #TURNIN“Down the Scarlet Path”# SKIP the next part" },
			[12] = { str = "Go just south of the Inn, turn in #TURNIN“Reagents For Reclaimers Inc pt.3”# accept #ACCEPT“Reagents For Reclaimers Inc pt.4”#" },
			[13] = { str = "Fly to Theramore, Sail to Menethil and Fly to IF" },
			[14] = { str = "Turn in #TURNIN“Reagents For Reclaimers Inc pt.4”# at 67,17", x = 67, y = 17, zone = "Ironforge" },
			[15] = { str = "Get new skills" },
			[16] = { str = "Fly to Booty Bay" },
		}
	},
-----------42-43 Stranglethron Vale
	--[404] = {
	[4243] = {
		title = "42-43 Stranglethron Vale",
		--n = "42-43 Stranglethron Vale",
		--pID = 403, nID = 405,
		--itemCount = 29,
		items = {
			[1] = { str = "42-43 Stranglethron Vale" },
			[2] = { str = "Go into the Inn, accept #ACCEPT“Tran'Rek”#" },
			[3] = { str = "Make BB your home" },
			[4] = { str = "Accept #ACCEPT“Zanzil's Secret”# and #ACCEPT“Whiskey Slim's Lost Grog”#" },
			[5] = { str = "Go near the Bank, accept #ACCEPT“Akiris By the Bundle pt.1”#" },
			[6] = { str = "Go in the house next to the half ship, accept #ACCEPT“Stoley's Debt”#" },
			[7] = { str = "Where the dock forks up and down, go up and around the corner, accept #ACCEPT“Keep An Eye Out”#" },
			[8] = { str = "Go out of BB and to the right and south. All around 31,79 You’re gonna kill the buccaneers for #DOQUEST“Up To Snuff”# and #DOQUEST“Keep An Eye Out”#", x = 31, y = 79, zone = "Stranglethorn Vale" },
			[9] = { str = "Kill the swashbucklers around the two camps at 29,81(bloodsail charts are here on the box) and 27,82 (bloodsail orders, on the box, NE tent) for #DOQUEST“The Bloodsail Buccaneers pt.4”#", x = 27, y = 82, zone = "Stranglethorn Vale" },
			[10] = { str = "Run back up into BB, and turn left" },
			[11] = { str = "Turn in #TURNIN“Keep An Eye Out”# near the forge" },
			[12] = { str = "Go up in the Inn, turn in #TURNIN“Up To Snuff”#" },
			[13] = { str = "Go just outside and hand in #TURNIN“The Bloodsail Buccaneers pt.4”# accept #ACCEPT“The Bloodsail Buccaneers pt.5”#" },
			[14] = { str = "Go kill naga around 25,63 for #DOQUEST“Akiris By the Bundle pt.1”#", x = 25, y = 63, zone = "Stranglethorn Vale" },
			[15] = { str = "Grind on the nagas until you’re at least 50% into level 43" },
			[16] = { str = "Go up to the Ruins of Aboraz and kill #NPCChucky# (40,58) for #DOQUEST“Voodoo Dues”# while killing the mobs for #DOQUEST“Zanzil's Secret”# you only need 8-10", x = 40, y = 58, zone = "Stranglethorn Vale" },
			[17] = { str = "Go up to the Ruins of Jubawal and kill #NPCJon-Jon# (34,51) and #NPCMaury# (35,51) for #DOQUEST“Voodoo Dues”# and the rest of #DOQUEST“Zanzil's Secret”#", x = 35, y = 51, zone = "Stranglethorn Vale" },
			[18] = { str = "Go kill #NPCTethis# for #DOQUEST“Raptor Mastery pt.4”# behind the arena around 31,43 then turn it in at nessingways at 35,10 accept #ACCEPT“Big Game Hunter”#", x = 31, y = 43, zone = "Stranglethorn Vale" },
			[19] = { str = "Go up to the rebel camp at 38,3 and accept #ACCEPT“Colonel Kurzen”#", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[20] = { str = "Go to the cave at 45,8 go to the fork and go down once like earlier kill the elites and subchiefs (when they get a red aura stop your pet from hitting them or he’ll get owned) for #DOQUEST“Colonel Kurzen”# Kurzen is at 49,3 ", x = 49, y = 3, zone = "Stranglethorn Vale" },
			[21] = { str = "Die on purpose so you’re near the rebel camp" },
			[22] = { str = "Go to the rebel camp at 38,3 and turn in #TURNIN“Colonel Kurzen”#", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[23] = { str = "Kill the trolls around 44,34 until you’re about 9k xp from leveling", x = 44, y = 34, zone = "Stranglethorn Vale" },
			[24] = { str = "Hearth to BB" },
			[25] = { str = "Turn in #TURNIN“Zanzil's Secret”#" },
			[26] = { str = "Go down by the Bank, turn in #TURNIN“Akiris By the Bundle pt.1”# accept #ACCEPT“Akiris By the Bundle pt.2”#" },
			[27] = { str = "Go to the house in front of the half boat, turn in #TURNIN“Voodoo Dues”# accept #ACCEPT“Cracking Maury's Foot”#" },
			[28] = { str = "Get on the boat to Rachet then fly to Theramore" },
			[29] = { str = "Turn in #TURNIN“Akiris By the Bundle pt.2”# in front of you, fly to Gadgetzan" },
		}
	},

-----------43-43 Tanaris
	--[405] = {
	[4343] = {
		title = "43-43 Tanaris",
		--n = "43-43 Tanaris",
		--pID = 404, nID = 406,
		--itemCount = 34,
		items = {
			[1] = { str = "43-43 Tanaris" },
			[2] = { str = "Accept #ACCEPT“Wastewander Justice”# and #ACCEPT“Water Pouch Bounty”#" },
			[3] = { str = "Make Gadgetzan your home" },
			[4] = { str = "Go in front of the cage and grab the 2 quests off the sign #ACCEPT“WANTED: Caliph Scorpidsting”# and #ACCEPT“WANTED: Andre Firebeard”#" },
			[5] = { str = "Turn in #TURNIN“Tran'Rek”# SKIP the next part" },
			[6] = { str = "On the left side of town on the hill accept #ACCEPT“Gadgetzan Water Survey”#" },
			[7] = { str = "Go to The Shimmering Flats to 77,77 and turn in #TURNIN“Rumors for Kravel”# accept #ACCEPT“Back to Booty Bay”#", x = 77, y = 77, zone = "Thousand Needles" },
			[8] = { str = "Just beside him turn in #TURNIN“News for Fizzle”#" },
			[9] = { str = "Go to 80,75 and accept #ACCEPT“Keeping Pace”# do it by talking with zamek just south of here, has a blue ? on his head. Don’t follow him, run to rizzles house at 77,77 and when he leaves grab the unguarded plans which turns in #TURNIN“Keeping Pace”# accept #ACCEPT“Rizzle's Schematics”# turn it in at 80,75", x = 80, y = 75, zone = "Thousand Needles" },
			[10] = { str = "Hearth to Gadgetzan" },
			[11] = { str = "Run out to Steamwheedle Port at 59,80", x = 59, y = 80, zone = "Tanaris" },
			[12] = { str = "Turn in #TURNIN“Stoley's Debt”# at the southern most house, accept #ACCEPT“Stoley’s Shipment”# and #ACCEPT“Southsea Shakedown”#" },
			[13] = { str = "Go to the northern houses, accept #ACCEPT“Pirate Hats Ahoy!”# and #ACCEPT“Screecher Spirits”#" },
			[14] = { str = "Go to around 63,30 and kill the mobs here for #DOQUEST“Wastewander Justice”# and #DOQUEST“Water Pouch Bounty”# Look for #NPCCaliph Scorpidsting# and kill him for #ACCEPT“WANTED: Caliph Scorpidsting”#  while here. He has 2 stealthed guards but is fairly easy. He patrols up and down", x = 63, y = 30, zone = "Tanaris" },
			[15] = { str = "Run over to the cave at 68,41 and go through to Lost Rigger Cove.", x = 68, y = 41, zone = "Tanaris" },
			[16] = { str = "Start killing the mobs all back here for  #DOQUEST“Southsea Shakedown”# and #DOQUEST“Pirate Hats Ahoy!”#" },
			[17] = { str = "You may get some drops of Pirate's Footlocker which can hold  #NPCShip Schedule#  and the upper middle and lower map fragments which starts #ACCEPT“Cuergo’s Gold”# and #ACCEPT“Ship Schedules”# only do them if you find them. If I don’t find them all I skip them or sell what I have." },
			[18] = { str = "Kill #NPCAndre Firebeard# at 73,47 for #ACCEPT“WANTED: Andre Firebeard”#", x = 73, y = 47, zone = "Tanaris" },
			[19] = { str = "Go to the only 2 story house out here at 72,46 and get the stolen wine for #DOQUEST“Stoley’s Shipment”#. It’s on the 2nd floor", x = 72, y = 46, zone = "Tanaris" },
			[20] = { str = "Hearth to Gadgetzan" },
			[21] = { str = "Turn in #TURNIN“Wastewander Justice”#  accept #ACCEPT“More Wastewander Justice”#" },
			[22] = { str = "Turn in #TURNIN“WANTED: Caliph Scorpidsting”# and #TURNIN“Water Pouch Bounty”#" },
			[23] = { str = "You should be close to half way TNL" },
			[24] = { str = "Go west to 39,29 and do #DOQUEST“Gadgetzan Water Survey”# Run once you get the sample a 47 and 48 will attack you.", x = 32, y = 29, zone = "Tanaris" },
			[25] = { str = "Run back to Gadgetzan and hand in #TURNIN“Gadgetzan Water Survey”# accept #ACCEPT“Noxious Lair Investigation”#" },
			[26] = { str = "Go do #DOQUEST“More Wastewander Justice”# around 60,35 by killing the mobs", x = 60, y = 35, zone = "Tanaris" },
			[27] = { str = "Go back up to Steamweedle Port at 59,80 to the southern house and turn in  #TURNIN“Stoley’s Shipment”# accept #ACCEPT“Deliver to MacKinley”#", x = 59, y = 80, zone = "Tanaris" },
			[28] = { str = "Turn in #TURNIN“WANTED: Andre Firebeard”# and #TURNIN“Southsea Shakedown”#" },
			[29] = { str = "Go to the northern house, turn in #TURNIN“Pirate Hats Ahoy!”#" },
			[30] = { str = "Hearth to Gadgetzan" },
			[31] = { str = "Turn in #TURNIN“More Wastewander Justice”#" },
			[32] = { str = "Accept #ACCEPT“Handle With Care”# near the north side of town" },
			[33] = { str = "You should be about ¾ TNL now" },
			[34] = { str = " Fly to Feralas" },
		}
	},

-----------43-45 Feralas
	--[406] = {
	[4345] = {
		title = "43-45 Feralas",
		--n = "43-45 Feralas",
		--pID = 405, nID = 407,
		--itemCount = 43,
		items = {
			[1] = { str = "43-45 Feralas" },
			[2] = { str = "On the water side of the inn in the gazebo, accept #ACCEPT“The Mark of Quality”#" },
			[3] = { str = "Make Feralas your home" },
			[4] = { str = "Go into the big building across from the Inn, accept #ACCEPT“The Missing Courier pt.1”# and #ACCEPT“The Ruins of Solarsal”#" },
			[5] = { str = "Go to the building just west accept #ACCEPT“In Search of Knowledge”# and #ACCEPT“The High Wilderness”#" },
			[6] = { str = "Go upstairs turn in #TURNIN“The Missing Courier pt.1”# accept #ACCEPT“The Missing Courier pt.2”#" },
			[7] = { str = "Go to the gazebo at 26,52 and turn in #TURNIN“The Ruins of Solarsal”# accept #ACCEPT“Return to Feathermoon Stronghold”#", x = 26, y = 52, zone = "Feralas" },
			[8] = { str = "Go back to Feathermoon to the big building, turn in #TURNIN“Return to Feathermoon Stronghold”# accept #ACCEPT“Against the Hatecrest pt.1”# turn around and hand it in accept #ACCEPT“Against the Hatecrest pt.2”#" },
			[9] = { str = "Kill naga around 26,54 for #DOQUEST“Against the Hatecrest pt.2”#", x = 26, y = 54, zone = "Feralas" },
			[10] = { str = "I kill the naga until im about 2500 TNL because I’m usually under 15k TNL when I get to this part. They give an average of 250 xp per kill" },
			[11] = { str = "Go back to Feathermoon to the big building, turn in #TURNIN“Against the Hatecrest pt.2”# accept #ACCEPT“Against Lord Shalzaru”#" },
			[12] = { str = "Go down to the cave at 26,66 and kill #NPCLord Shalzaru# at the end for #DOQUEST“Against Lord Shalzaru”#", x = 26, y = 66, zone = "Feralas" },
			[13] = { str = "Die so you end up at Feathermoon" },
			[14] = { str = "Go back to Feathermoon to the big building, turn in #TURNIN“Against Lord Shalzaru”# accept #ACCEPT“Delivering the Relic”# go to the other side of the building and turn it in." },
			[15] = { str = "Take the boat to the mainland" },
			[16] = { str = "Go south of the dock and kill screechers for #DOQUEST“Screecher Spirits”#" },
			[17] = { str = "Go down to 45,65 and touch the wrecked boat to turn in #TURNIN“The Missing Courier pt.2”# accept #ACCEPT“Boat Wreckage”#", x = 45, y = 65, zone = "Feralas" },
			[18] = { str = "Hearth to Feathermoon" },
			[19] = { str = "Go in the little building across from the Inn on the 2nd floor, turn in #TURNIN“Boat Wreckage”# accept #ACCEPT“The Knife Revealed”#" },
			[20] = { str = "Go up top of the big spiral tower, turn in #TURNIN“The Knife Revealed”# accept #ACCEPT“Psychometric Reading”#" },
			[21] = { str = "Go in the little building across form the Inn on the 2nd floor, turn in #TURNIN“Psychometric Reading”# accept #ACCEPT“The Woodpaw Gnolls”#" },
			[22] = { str = "Take the boat to the mainland" },
			[23] = { str = "Go into the yeti cave at 56,56 and kill yeti’s for #DOQUEST“The Mark of Quality”# you can skin them and it’s also a drop.", x = 56, y = 56, zone = "Feralas" },
			[24] = { str = "If a #NPCOOX-22/FE Distress Beacon# has fallen accept the quest #ACCEPT“Find OOX-22/FE!”# and turn it in at the back of the cave SKIP the escort. " },
			[25] = { str = "Grind east and kill the Brutes around 60,56, and warlocks and shamans around 59,66 for #DOQUEST“The High Wilderness”# I kill any I see", x = 60, y = 56, zone = "Feralas" },
			[26] = { str = "Go up to 65,45 and accept #ACCEPT“Freedom For All Creatures”# It’s pretty hidden, just NW of the camp entrance is a path that doesn’t even look like you can walk on it. To do this simply escort her to the cage, open it and kill anything until it says complete. ", x = 65, y = 45, zone = "Feralas" },
			[27] = { str = "Hand it back in and accept #ACCEPT“Doling Justice pt.1”# The mobs can be found in this camp." },
			[28] = { str = "Turn in #TURNIN“Doling Justice pt.1”#  at 65,45 and accept #ACCEPT“Doling Justice pt.2”#", x = 65, y = 45, zone = "Feralas" },
			[29] = { str = "Go down to 73,56 and touch Large Leather Backpacks on the big tree. Turn in #TURNIN“The Woodpaw Gnolls”# accept #ACCEPT“The Writhing Deep”#", x = 73, y = 56, zone = "Feralas" },
			[30] = { str = "Right click the Backpack, accept #ACCEPT“Thalanaar Delivery”#" },
			[31] = { str = "Grind down to the hive at 73,63 and go all the way down. Go into the southern tunnel and stay right, You’ll see a Zukk’Ash Pod there. Turn in #TURNIN“The Writhing Deep”# accept #ACCEPT“Freed From the Hive”#", x = 73, y = 63, zone = "Feralas" },
			[32] = { str = "Hearth to Feathermoon" },
			[33] = { str = "On the water side of the Gazebo, turn in #TURNIN“The Mark of Quality”# accept #ACCEPT“Improved Quality”#" },
			[34] = { str = "Go in the small house across from the Inn, turn in #TURNIN“The High Wilderness”# then go upstairs and turn in #TURNIN“Freed From the Hive”# accept #ACCEPT“A Hero’s Welcome”#" },
			[35] = { str = "Go to the big building next door and turn in #TURNIN“A Hero’s Welcome”# accept #ACCEPT“Rise of the Silithid”#" },
			[36] = { str = "Fly out to Thalanaar (spot between 1k needles and here) turn in #TURNIN“Thalanaar Delivery”# at 89,46", x = 89, y = 46, zone = "Feralas" },
			[37] = { str = "Fly to Rut'theran Village (Darnassus)" },
			[38] = { str = "Follow the dock and go in the house, turn in #TURNIN“Handle With Care”# accept #ACCEPT“Favored of Elune?”#" },
			[39] = { str = "Go upstairs, turn in #TURNIN“In Search of Knowledge”# then go to the back of the house on the 2nd floor, open the green book and accept #ACCEPT“Feralas: A History”# turn it back in to her, accept #ACCEPT“The Borrower”#" },
			[40] = { str = "Get new skills" },
			[41] = { str = "Go to the temple of the moon at 39,86 and up to the 2nd floor, turn in #TURNIN“Rise of the Silithid”# and #TURNIN“Doling Justice pt.2”#", x = 39, y = 86, zone = "Feralas" },
			[42] = { str = "Buy 2 Elixir of Fortitude for a later part of this quest" },
			[43] = { str = "Hearth to Feathermoon and fly to Gadgetzan and turn in #TURNIN“The Borrower”# accept #ACCEPT“The Super Snapper FX”#" },
		}
	},

-----------45-46 Uldaman
	--[407] = {
	[4546] = {
		title = "45-46 Uldaman",
		--n = "45-46 Uldaman",
		--pID = 406, nID = 408,
		--itemCount = 7,
		items = {
			[1] = { str = "45-46 Uldaman" },
			[2] = { str = "Now you can either grind on the gnolls in Feralas around where you found the backpack on the tree, or you can do Uldaman. I highly suggest you do Uldaman. You picked up some quests earlier, there are a few more in IF and in the badlands. If you get a good group build you can easily do just about every quest in there in under 3 hours max. I usually fully do Uldaman inside and out, I don’t finish all the quests unless I have to level. 1 full run inside and out should get you 75-100% through this level. I usually do this in about 3 hours no problem. Plus you can solo all the mobs outside of the instance 3 at a time no problem. The end of Uldaman, after the boss, (mini disks quest) gives about 20k xp between that and talking to the ghostly npc who spawns in there, as well as gives some nice xp for quests later on. And you could miss some xp spots for later quests I do if you skip this." },
			[3] = { str = "I don’t list all the quests for Uldaman because there is a good handful and you don’t have to do them all to fully level, and again it is optional. This is much faster than grinding would be. I really hate to do instances when trying for the best time but alliance has less quests than the horde do and I did mention there will be about 10-15% of grinding on your way to 60. If you did do all instances though you would be really slowed down. This isn’t going to put a break in your time with a good group, preferrably guild groups of 45+" },
			[4] = { str = "You can stop at about 75% to 46 but again I suggest you level. It’s not as bad as it seems." },
			[5] = { str = "A great map of Uldaman and where the parts of most of the quests pieces can be done at is listed here on worldofwar.net" },
			[6] = { str = "Once you’re all set, fly to SW and turn in #TURNIN“In Search of The Temple”# at 64,20 and accept #ACCEPT“In Search of The Hinterlands”# get new skills then fly to Southshore.", x = 64, y = 20, zone = "Stormwind" },
			[7] = { str = " Run up to the path at 84,33 behind Durnholde Keep (you’ll see 2 griffins) into The Hinterlands", x = 84, y = 33, zone = "Tarren Mill" },
		}
	},

-----------46-47 The Hinterlands
	--[408] = {
	[4647] = {
		title = "46-47 The Hinterlands",
		--n = "46-47 The Hinterlands",
		--pID = 407, nID = 409,
		--itemCount = 29,
		items = {
			[1] = { str = "46-47 The Hinterlands" },
			[2] = { str = "Go up to 11,46 and turn in #TURNIN“In Search of The Hinterlands”# accept #TURNIN“Gryphon Master Talonaxe”#", x = 11, y = 46, zone = "The Hinterlands" },
			[3] = { str = "Get the FP at 11,46 way up top then go in the cave and turn in  #TURNIN“Gryphon Master Talonaxe”#, accept #ACCEPT“Rhapsody Shindigger”# and #ACCEPT“Witherbark Cages”#", x = 11, y = 46, zone = "The Hinterlands" },
			[4] = { str = "Go into the Inn and turn right, accept #ACCEPT“Skulk Rock Clean-Up”# and #ACCEPT“Troll Necklace Bounty”#" },
			[5] = { str = "Go way in the back of the Inn up to around 13,41 and make Aerie Peak your home.", x = 13, y = 41, zone = "The Hinterlands" },
			[6] = { str = "Grind east to 20,48 to the path while keeping an eye out for feathers on the ground for #DOQUEST“Favored of Elune?”# You don’t need them all yet", x = 20, y = 48, zone = "The Hinterlands" },
			[7] = { str = "Follow the path up to 26,48 and turn in #TURNIN“Rhapsody Shindigger”# accept #ACCEPT“Rhapsody's Kalimdor Kocktail”#", x = 26, y = 48, zone = "The Hinterlands" },
			[8] = { str = "Go back down and to the troll camp and clear most of them out at 23,58 and open the 2 cages for #DOQUEST“Witherbark Cages”#", x = 23, y = 58, zone = "The Hinterlands" },
			[9] = { str = "Grind east to 31,57 and open the 3rd cage for #DOQUEST“Witherbark Cages”#", x = 31, y = 57, zone = "The Hinterlands" },
			[10] = { str = "You should also have 5 necklaces for #DOQUEST“Troll Necklace Bounty”# now" },
			[11] = { str = "Go NE up to 46,42, collecting feathers if you still need them on the way, and kill the Green Sludges for #DOQUEST“Skulk Rock Clean-Up pt.1”#", x = 46, y = 62, zone = "The Hinterlands" },
			[12] = { str = "Go to 49,37 if you found OOX-09/HL Distress Beacon", x = 49, y = 37, zone = "The Hinterlands" },
			[13] = { str = "Go to 56,41 and kill Jade Oozes for part 2 of #DOQUEST“Skulk Rock Clean-Up”#", x = 56, y = 41, zone = "The Hinterlands" },
			[14] = { str = "Go to the waterfall at 81,46 and dive into the water below, then go south along this shore until you see Gammerita and take her picture for #DOQUEST“The Super Snapper FX”# Also you want to keep an eye out for bottles along the shore for #DOQUEST“Whiskey Slim's Lost Grog”#", x = 81, y = 46, zone = "The Hinterlands" },
			[15] = { str = "Hearth to Aerie Peak" },
			[16] = { str = "Go to the front of the Inn and turn in #TURNIN“Skulk Rock Clean-Up”# and #TURNIN“Troll Necklace Bounty”# and any extra 5 necklaces you have." },
			[17] = { str = "Go up past the FP in the cave at 9,44 and turn in #TURNIN“Witherbark Cages”# accept #ACCEPT“The Altar of Zul”#", x = 9, y = 44, zone = "The Hinterlands" },
			[18] = { str = "Go run up top of the Altar of Zul at 48,68 for #DOQUEST“The Altar of Zul”#", x = 48, y = 68, zone = "The Hinterlands" },
			[19] = { str = "Now I grind on the trolls and wolves around Zul until I’m 1 bar from level 47. You should be at least half way through level 46 at this point." },
			[20] = { str = "Get the quest #ACCEPT“Jammal'an the Prophet”# at 33,75 if you plan to do Sunken Temple later.", x = 33, y = 75, zone = "The Hinterlands" },
			[21] = { str = "I’m sure by the time you near level 47 you’re going to find OOX-09/HL Distress Beacon accept #ACCEPT“Find OOX-09/HL”# and turn it in at 49,37 and then accept #ACCEPT“Rescue OOX-09/HL”# and escort it to 78,61 Theres only 2 encounters of 3 mobs, but watch out for the stealthed wolves", x = 49, y = 37, zone = "The Hinterlands" },
			[22] = { str = "Once you’re about 6k or 1 bar from level 47 hearth to Aerie Peak" },
			[23] = { str = "Turn in any #TURNIN“Troll Necklace Bounty”# you have just before you go out" },
			[24] = { str = "Go up past FP to 9,44 and turn in #TURNIN“The Altar of Zul”# accept #ACCEPT“Thadius Grimshade”#", x = 9, y = 44, zone = "The Hinterlands" },
			[25] = { str = "Fly to Menethil Harbor and take the boat to Auberdine, then fly to Rut’theran Village" },
			[26] = { str = "Run to the house at 55,92 and turn in #TURNIN“Favored of Elune?”#", x = 55, y = 92, zone = "The Hinterlands" },
			[27] = { str = "Go upstairs, turn in #TURNIN“The Super Snapper FX”# accept #ACCEPT“Return to Troyas”#" },
			[28] = { str = "You should now be level 47 and about 8k into it." },
			[29] = { str = "Fly to Feralas" },
		}
	},

-----------47-47 Feralas
	--[409] = {
	[4747] = {
		title = "47-47 Feralas",
		--n = "47-47 Feralas",
		--pID = 408, nID = 410,
		--itemCount = 22,
		items = {
			[1] = { str = "47-47 Feralas" },
			[2] = { str = "Make Feathermoon Stronghold your home" },
			[3] = { str = "Go across from the Inn to the 2 story house, turn in #TURNIN“Return to Troyas”# accept #ACCEPT“The Stave of Equinex”#" },
			[4] = { str = "Accept #ACCEPT“The Sunken Temple”# Next to him" },
			[5] = { str = "Swim or sail east to the dock." },
			[6] = { str = "Beside the dock at 44,33 accept #ACCEPT“Zapped Giants”# and #ACCEPT“Fuel for Zapping”#", x = 44, y = 33, zone = "Feralas" },
			[7] = { str = "Make the Zorbin's Ultra-Shrinker a hotkey. Then go south along the shore and start zapping giants and killing them for #DOQUEST“Zapped Giants”# and kill water elementals for #DOQUEST“Fuel for Zapping”#" },
			[8] = { str = "Go back to 44,33 and turn in #TURNIN“Zapped Giants”# and #TURNIN“Fuel for Zapping”# You can now do those again, but I wouldn’t, for about 500 xp per turn in. Now he opens his store to you.", x = 44, y = 33, zone = "Feralas" },
			[9] = { str = "Run over to the grimtotem camp at 65,45 and accept #ACCEPT“An Orphan Looking For A Home”#", x = 65, y = 45, zone = "Feralas" },
			[10] = { str = "Go down to the yeti cave at 56,56 and do the robot chicken escort if you can, don’t be afraid to ask for help if needed.", x = 56, y = 56, zone = "Feralas" },
			[11] = { str = "Grind to the yeti cave at 51,31 on Ironfur Bears and Groddoc Gorillas until you get 3 livers from each of them for #DOQUEST“Rhapsody's Kalimdor Kocktail”#", x = 51, y = 31, zone = "Feralas" },
			[12] = { str = "Kill the Rage Scar Yeti’s here for #DOQUEST“Improved Quality”# remember you can skin them for these as well. If a Pristine Yeti Hide drops, accept the quest it gives #ACCEPT“Pristine Yeti Hide”#" },
			[13] = { str = "Go to Rockbiter at 42,22 and accept #ACCEPT“The Giant Guardian”#", x = 42, y = 22, zone = "Feralas" },
			[14] = { str = "Do #DOQUEST“The Stave of Equinex”# by doing the following. Get the Blytan Essence from the fire at 38,15 #DOQUEST“The Stave of Equinex”# Get the Samha Essence from the fire at 40,12 (atop the ruined arch) to get to it, go around back and hop up the broken rocks (it’s not easily noticed) Go back out the back and Grab the Imbel Essence from the fire at 39,9. Get the Lahassa Essence from the fire at 37,12 under the brown gazebo. Go down to the Equinex Monolith just over the cliff. Use Troya’s Staff next to it. Touch the Monolith and turn in #TURNIN“The Stave of Equinex”#  accept #ACCEPT“The Morrow Stone”#", x = 38, y = 15, zone = "Feralas" },
			[15] = { str = "Go back up near the previous flame to 38,10 and turn in #TURNIN“The Giant Guardian”# accept the escort #ACCEPT“Wandering Shay”#", x = 38, y = 10, zone = "Feralas" },
			[16] = { str = "Grab the bell from the chest and hotkey it. This is similar to the druid quest back in Darkshore. Run her back to Rockbiter at 42,21 and turn in #TURNIN“Wandering Shay”# (the trick is to keep ahead of her, if she’s with you by your side she will wander off a lot more and the bell has a 1 minute timer.", x = 42, y = 21, zone = "Feralas" },
			[17] = { str = "Hearth to Feathermoon Stronghold" },
			[18] = { str = "Go to the gazebo near the water beside the hippogryph master, turn in #TURNIN“Pristine Yeti Hide”# and #TURNIN“Improved Quality”#" },
			[19] = { str = "Take your 2 Elixirs of Fortitude out of your mailbox if you don’t already have them on you." },
			[20] = { str = "Go across to the 2 story house, turn in #TURNIN“The Morrow Stone”#" },
			[21] = { str = "You should be close to 70% into 47" },
			[22] = { str = "Fly to Gadgetzan" },
		}
	},

-----------47-48 Tanaris
	--[410] = {
	[4748] = {
		title = "47-48 Tanaris",
		--n = "47-48 Tanaris",
		--pID = 409, nID = 411,
		--itemCount = 42,
		items = {
			[1] = { str = "47-48 Tanaris" },
			[2] = { str = "Just inside Gadgetzan to the right, accept #ACCEPT“The Thirsty Goblin”#" },
			[3] = { str = "Make Gadgetzan your home" },
			[4] = { str = "Go behind the Inn, accept #ACCEPT“The Dunemaul Compound”#" },
			[5] = { str = "Near the north entrance, accept #ACCEPT“Thistleshrub Valley”#" },
			[6] = { str = "Go south to the skeleton in the ground at 49,36 and 44,39 and 47,45 kill Rocs for #DOQUEST“Rhapsody's Kalimdor Kocktail”# If it’s busy just do it later.", x = 49, y = 36, zone = "Tanaris" },
			[7] = { str = "Ride over to 52,45 turn in #TURNIN“The Sunken Temple”# and accept #ACCEPT“The Stone Circle”# and #ACCEPT“Gahz'Ridian”#", x = 52, y = 45, zone = "Tanaris" },
			[8] = { str = "Now put on the Gahz’Ridian Detector Helm and yellow dots on mini map will show the pieces you need to get for #DOQUEST“Gahz'Ridian”#. It’s up to you if you want to wear this in fights. This stuff is all over" },
			[9] = { str = "Run over west to the Dunemaul Compound clear a path to 40,58 and kill Gor’Marok the Ravager for #DOQUEST“The Dunemaul Compound”# You don’t need the 20 ogre kills all from here", x = 40, y = 58, zone = "Tanaris" },
			[10] = { str = "Head over to 47,65 and finish killing the ogres for The Dunemaul Compound while gathering the rest of the artifacts for Gahz'Ridian", x = 47, y = 65, zone = "Tanaris" },
			[11] = { str = "Grind on the ogres until you’re 10,000 from level 48" },
			[12] = { str = "Sneak up the left side of Uldum and go up to the pedestal at 37,81 and turn in #TURNIN“Seeing What Happens”#", x = 37, y = 81, zone = "Tanaris" },
			[13] = { str = "Talk to the guy who appears, accept #ACCEPT“The Stone Watcher”# and talk to him until completed. Then touch the pedastal to turn it back in" },
			[14] = { str = "Touch the pedastal one more time and accept #ACCEPT“Return to Ironforge”#" },
			[15] = { str = "Go west to 29,66 and kill Gnarled Thistlegrub and Thistlegrub Rootshapers for #DOQUEST“Thistleshrub Valley”# and the dew collectors for #DOQUEST“The Thirsty Goblin”# You should hit level 48 here", x = 29, y = 66, zone = "Tanaris" },
			[16] = { str = "If you find Tooga, accept #ACCEPT“Tooga’s Quest”# I found him at 29,73 near the zepplin, but you can find him anywhere around this valley. He follows you, you don’t have to follow him ", x = 29, y = 73, zone = "Tanaris" },
			[17] = { str = "Go up to the Noxious Lair around 34,46 and kill Centipaar there for #DOQUEST“Noxious Lair Investigation”# If you can’t get them all before tooga has 10 minutes left, go turn that in and then come back.", x = 34, y = 76, zone = "Tanaris" },
			[18] = { str = "Turn in #TURNIN“Tooga’s Quest”# near steamwheedle port at 66,25", x = 66, y = 25, zone = "Tanaris" },
			[19] = { str = "Accept #ACCEPT“Yuka Screwspigot”#" },
			[20] = { str = "Turn in #TURNIN“Screecher Spirits”# at 66,22 SKIP the ZF part", x = 66, y = 22, zone = "Tanaris" },
			[21] = { str = "Hearth to Gadgetzan" },
			[22] = { str = "Go near the entrance and accept #ACCEPT“The Thirsty Goblin”# back and turn it in accept #ACCEPT“In Good Taste”#" },
			[23] = { str = "Go behind the Inn near the fire, turn in #TURNIN“The Dunemaul Compound”#" },
			[24] = { str = "Go near the north entrance, hand in #TURNIN“Thistleshrub Valley”#" },
			[25] = { str = "Go west to Sprinkle, turn in #TURNIN“In Good Taste”# accept #ACCEPT“Sprinkle's Secret Ingredient”#" },
			[26] = { str = "In the building behind her, turn in #TURNIN“Noxious Lair Investigation”#" },
			[27] = { str = "Go on the hill behind the building, accept #ACCEPT“The Schrimshank Redemption”#" },
			[28] = { str = "Run down to 52,45 and turn in #TURNIN“Gahz'Ridian”#", x = 52, y = 45, zone = "Tanaris" },
			[29] = { str = "Run down to the entrance at 55,70 take the spiral down to the entrance that is north. first fork go right. after the circular room at the next fork go right. You will enter a big square room. Go right to 55,71 and grab the survey gear for #DOQUEST“The Schrimshank Redemption”#", x = 55, y = 70, zone = "Tanaris" },
			[30] = { str = "Die on purpose so you end up at Gadgetzan" },
			[31] = { str = "Go to the hill on the west side of town, turn in #TURNIN“The Schrimshank Redemption”# accept #ACCEPT“Insect Part Analysis pt.1”#" },
			[32] = { str = "Go to the house on the NW part of town, turn in #TURNIN“Insect Part Analysis pt.1”# accept #ACCEPT“Insect Part Analysis pt.2”#" },
			[33] = { str = "Go back up on the hill, turn in #TURNIN“Insect Part Analysis pt.2”# accept #ACCEPT“Rise of the Silithid”#" },
			[34] = { str = "Run up to the Shimmering Flats to 78,74 and turn in #TURNIN“An Orphan Looking For A Home”# accept #ACCEPT“A Short Incubation”# and since you already have this, turn it back in and accept #ACCEPT“The Newest Member of the Family”# now you have 1 hour.", x = 78, y = 74, zone = "Thousand Needles" },
			[35] = { str = "Fly to Theramore and get any mageweave you have out and build up first aid as much as you can." },
			[36] = { str = "Sail to Menethil and fly to IF" },
			[37] = { str = "Make IF your home and get new skills" },
			[38] = { str = "Go to 77,11 and turn in #TURNIN“Return to Ironforge”# accept #ACCEPT“A Future Task”# and #ACCEPT“Passing the Burden”#", x = 77, y = 11, zone = "Ironforge" },
			[39] = { str = "Turn around to 70,18 and turn in #TURNIN“A Future Task”#", x = 70, y = 18, zone = "Ironforge" },
			[40] = { str = "Go to 31,4 and turn in #TURNIN“Passing the Burden”# accept #ACCEPT“Arcane Runes”# and #ACCEPT“An Easy Pickup”#", x = 31, y = 4, zone = "Ironforge" },
			[41] = { str = "Go to 70,93, turn in #TURNIN“An Easy Pickup”# accept #ACCEPT“Signal For Pickup”# then turn it back in. Now you got the flare gun to signal later on.", x = 70, y = 93, zone = "Ironforge" },
			[42] = { str = "Fly to the Hinterlands" },
		}
	},

-----------48-48 The Hinterlands
	--[411] = {
	[4848] = {
		title = "48-48 The Hinterlands",
		--n = "48-48 The Hinterlands",
		--pID = 410, nID = 412,
		--itemCount = 8,
		items = {
			[1] = { str = "48-48 The Hinterlands" },
			[2] = { str = "Go in the base downstairs to 14,43 and turn in #TURNIN“The Newest Member of the Family”# accept #ACCEPT“Food For Baby”#", x = 14, y = 43, zone = "The Hinterlands" },
			[3] = { str = "Run up to 26,48 and turn in #TURNIN“Rhapsody's Kalimdor Kocktail”# Accept #ACCEPT“Rhapsody's Tale”#", x = 26, y = 48, zone = "The Hinterlands" },
			[4] = { str = "Grind down to the lake at 40,59 and Violet Tragan (Mushroom) from the bottom of the lake for #DOQUEST“Sprinkle's Secret Ingredient”#", x = 40, y = 59, zone = "The Hinterlands" },
			[5] = { str = "Grind until you’re east of 57,47 and kill Silvermane Stalkers for #DOQUEST“Food For Baby”#", x = 57, y = 47, zone = "The Hinterlands" },
			[6] = { str = "Run back to Aerie Peak and go to the bottom floor of the Inn" },
			[7] = { str = "Turn in #TURNIN“Food For Baby”# accept #ACCEPT“Becoming A Parent”# then turn it back in. Cute pet and good xp =)" },
			[8] = { str = "Hearth to IF and fly to BB" },
		}
	},

-----------48-49 Stranglethorn Vale
	--[412] = {
	[4849] = {
		title = "48-49 Stranglethorn Vale",
		--n = "48-49 Stranglethorn Vale",
		--pID = 411, nID = 413,
		--itemCount = 27,
		items = {
			[1] = { str = "48-49 Stranglethorn Vale" },
			[2] = { str = "Go down to the first floor of the Inn, make it your home" },
			[3] = { str = "Turn in #TURNIN“Back To Booty Bay”# and #TURNIN“Whiskey Slim's Lost Grog”#" },
			[4] = { str = "Enter the house next to the upside down, half ship, turn in #TURNIN“Deliver to MacKinley”#" },
			[5] = { str = "Under that boat outside, accept #ACCEPT“Stranglethorn Fever”#" },
			[6] = { str = "Go up the ramp and first house past the bridge, turn in all of the robot chicken escorts you’ve gotten. I didn’t get the Tanaris one while writing this guide so I missed out on the quest to get 7100 extra exp" },
			[7] = { str = "Near the boat, accept #ACCEPT“The Captain's Chest”#" },
			[8] = { str = "Go kill gorillas around 34,63 for #DOQUEST“Stranglethorn Fever”# then go up into the cave at 35,60 turn it in. the guy in the cave asks for 10 gorilla fangs, then he summons 3 waves of gorillas. Mokk is in the 3rd wave. They’re all around level 42-44 it starts with 3, then 5 then I think 6 or 7. It can get tough. Just kill Mokk first in case you die.", x = 35, y = 60, zone = "Stranglethorn Vale" },
			[9] = { str = "Go up to 38,34 and kill #NPCKing Bangalash# for #DOQUEST“Big Game Hunter”# he spawns level 33 minions. You can kill him before a few come out.", x = 38, y = 34, zone = "Stranglethorn Vale" },
			[10] = { str = "Run up to 48,25 and kill the elite ogres all around here until Maury’s Key drops for #DOQUEST“Cracking Maury’s Foot”# If you don’t find this after an hour just abandon the quest. It has a low drop rate. I grind until i'm 2 bars from level 49 if I don’t get the key. Usally it’s about an hours worth.", x = 48, y = 25, zone = "Stranglethorn Vale" },
			[11] = { str = "Go up to Nessingways at 35,10 and turn in #TURNIN“Big Game Hunter”#", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[12] = { str = "Hearth to Booty Bay, run up to the half boat just outside the Inn" },
			[13] = { str = "Turn in #TURNIN“Stranglethorn Fever”#" },
			[14] = { str = "Run to the shore just east of BB and open blue bottles until you get Carefully Folded Note which starts #ACCEPT“Message in A Bottle pt.1”#" },
			[15] = { str = "Go to 36,69 and kill #NPCGorlash# for #DOQUEST“The Captain's Chest”# He’s a 47 elite, it can be tough but I did it. Use everything you have", x = 36, y = 69, zone = "Stranglethorn Vale" },
			[16] = { str = " Go to 38,80 and turn in #TURNIN“Message in A Bottle pt.1”# SKIP the next part, unless you can get a group to kill the 51 ape", x = 38, y = 80, zone = "Stranglethorn Vale" },
			[17] = { str = "Go down to the pirate ships, 1 is at 33,87 and the other 2 are at 30,88 You want to go to the 2nd floor near the front of the ship and kill the captain of each for #DOQUEST“The Bloodsail Buccaneers pt.5”#", x = 33, y = 87, zone = "Stranglethorn Vale" },
			[18] = { str = "Look for a scroll on one of the ships called Cortello's Riddle which starts #ACCEPT“Cortello's Riddle pt.1”#" },
			[19] = { str = "If hearth is up, use it, otherwise die so you end up at BB" },
			[20] = { str = "Go near the boat, turn in #TURNIN“The Captain's Chest”#" },
			[21] = { str = "Go up top of the Inn, turn in #TURNIN“The Bloodsail Buccaneers pt.5”#" },
			[22] = { str = "Fly to SW and go to 64,20 turn in #TURNIN“Rhapsody's Tale”# SKIP the rest", x = 64, y = 20, zone = "Stormwind" },
			[23] = { str = "From here on, either look at the AH when you go by one, or use your AH char to search for your Beaststalker Bracers. I got mine for 8g also look for a mithril casing for later in Un’Goro" },
			[24] = { str = "Fly to Duskwood" },
			[25] = { str = "Run east through Deadwind Pass to the Swamp of Sorrows" },
			[26] = { str = "Follow the road until it forks and the left fork has a bridge at 22,48 and under it is A Soggy Scroll which turns in #TURNIN“Cortello's Riddle pt.1”# accept #ACCEPT“Cortello's Riddle pt.2”#", x = 22, y = 48, zone = "Swamp of Sorrow" },
			[27] = { str = "Run down to the Blasted Lands" },
		}
	},
	
--------49-50 Blasted Lands
	--[413] = {
	[4950] = {
		title = "49-50 Blasted Lands",
		--n = "49-50 Blasted Lands",
		--pID = 412, nID = 501,
		--itemCount = 30,
		items = {
			[1] = { str = "49-50 Blasted Lands" },
			[2] = { str = "No need to rush through this zone, so grind on anything you see." },
			[3] = { str = "Stop at 50,14 and accept the following 5 quests: #ACCEPT“The Basilisk's Bite”# #ACCEPT“Vulture's Vigor”# #ACCEPT“Snickerfang Jowls”# #ACCEPT“A Boar's Vitality”# and #ACCEPT“The Decisive Striker”#", x = 50, y = 14, zone = "Blasted Lands" },
			[4] = { str = "You’re going to need the following amount of items to complete all 5 of these quests. Snickerfang Jowls:5, Blasted Boar Lungs:6, Scorpok Pincers:6, Basilisk Brain:11, Vulture Gizzards:14 It’s going to be like grinding getting all this so you’re killing 2 birds with 1 stone. You’ll most likely gain half a level before you turn these in." },
			[5] = { str = "Just circle the center of the map and you’ll find all the stuff you need to kill. I’d mark it with coords but there would be way too many. You might want to avoid anything level 53 and up which are farther to the south. You should make some nice money with skinning here." },
			[6] = { str = "You should be close to 3 ½ bars into level 49 now" },
			[7] = { str = "Grind down to 51,35 and accept #ACCEPT“Everything Counts In Large Amounts”# If you do find one of these, hand it back in when you pass her, you’re bound to find at least one while here. Don’t even bother with the other quest you’ll Never find it. I’ve been playing WoW since release and never found one. ", x = 51, y = 35, zone = "Blasted Lands" },
			[8] = { str = "Go to 50,14 and turn in the 5 quests, #TURNIN“The Basilisk's Bite”# #TURNIN“Vulture's Vigor”# #TURNIN“Snickerfang Jowls”# #TURNIN“A Boar's Vitality”# and #TURNIN“The Decisive Striker”# but turn in the one you want the most last, because you get buffed and get an item as well. These each give 4700 xp", x = 50, y = 14, zone = "Blasted Lands" },
			[9] = { str = "Go to Nethergarde Keep to the top of the tall tower at 66,19 and turn in #TURNIN“Thadius Grimshade”# SKIP the next part.", x = 66, y = 19, zone = "Blasted Lands" },
			[10] = { str = "You should be close to 70% into level 49 now.  If you don’t want to do ZF to hit 50, grind here until you’re about 13k from level 50. If you want do ZF go to the next step." },
			[11] = { str = "Hearth to Booty Bay" },
			[12] = { str = "Accept #ACCEPT“Zanzil's Mixture”# and #ACCEPT“A Fool's Stout”#" },
			[13] = { str = "Get on the boat to Ratchet" },
			[14] = { str = "Accept #ACCEPT“Volcanic Activity”# at the first hut off the dock" },
			[15] = { str = "Just outside this hut is a green chest, open it for #DOQUEST“The Stone Circle”#" },
			[16] = { str = "Fly to Tanaris" },
			[17] = { str = "Go near the NW entrance, turn in #TURNIN“Sprinkle's Secret Ingredient”# accept #ACCEPT“Delivery For Marin”#" },
			[18] = { str = "Go back near the South entrance and turn in #TURNIN“Delivery For Marin”# accept #ACCEPT“Noggenfogger Elixir”# then turn it back in. You will recieve 5 elixirs and be able to purchase them." },
			[19] = { str = "Run in the Shimmering Flats to 77,77 and turn in #TURNIN“Zanzil's Mixture”# and #TURNIN“A Fool's Stout”# accept #ACCEPT“Get the Goblins Drunk”# go to 79,76 and turn it in.", x = 77, y = 77, zone = "Thousand Needles" },
			[20] = { str = "Go back to 77,77 and accept #ACCEPT“Report Back to Fizzlebub”#", x = 77, y = 77, zone = "Thousand Needles" },
			[21] = { str = "Go to 52,45 and turn in #TURNIN“The Stone Circle” SKIP the rest unless you plan on doing the Sunken Temple.", x = 52, y = 45, zone = "Thousand Needles" },
			[22] = { str = "You should be about 30k from level 50 now, like I said above, either go do ZF or you should have grinded in Blasted Lands." },
			[23] = { str = "If you do ZF you only really need to complete at least 2-3 of the following quests #DOQUEST“Troll Temper”# #DOQUEST“Divino-matic Rod”# #DOQUEST“Gahz'rilla”# #DOQUEST“The Prophecy of Mosh'Aru”# I highly suggest getting  #ACCEPT“Divino-matic Rod”# and #ACCEPT“Gahz'rilla”# because you get an awesome ring and a mount speed inscrease trinket." },
			[24] = { str = "Now you should be about 1-2 bars into level 50 if you went to ZF. From here on out there is a lot more fresh content, as you seen 45-50 is a pain in the ass. We still have a lot of untouched areas to level in now." },
			[25] = { str = "Hearth to BB and turn in #TURNIN“Report Back to Fizzlebub”#" },
			[26] = { str = "Fly to IF to get new skills and accept the quest #ACCEPT“The Hunter's Charm”#" },
			[27] = { str = "Make sure you get at least 15 Silk Cloth out of the mailbox or AH alt" },
			[28] = { str = "Make IF your home and accept #ACCEPT“Assisting Arch Druid Staghelm”#" },
			[29] = { str = "Fly to Thelsamar" },
			[30] = { str = "Run down into the Badlands all the way west to 1,62 and enter the Searing Gorge", x = 1, y = 62, zone = "Badlands" },
		}
	},
}