--[[--------------------------------------------------
003_Alliance_50to60.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 50 to Lvl 60
	1.04.1
		-- First Release
			Alliance's Guide
			from level 50 to lever 60
	1.04.2
		-- no changes in here for this revision
	1.04.3
		-- Added color codes
			Fixed various spelling errors
			Adjustment to coordinate visibility
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_50to60 = {
-----------50-51 Searing Gorge
	--[501] = {
	[5051] = {
		title = "50-51 Searing Gorge",
		--n = "50-51 Searing Gorge",
		--pID = 413, nID = 502,
		--itemCount = 72,
		items = {
			[1] = { str = "50-51 Searing Gorge" },
			[2] = { str = "Go down to #COORD[65,62]# and touch the outhouse, accept #GETCaught!#", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "Go just below the outhouse and kill the geologists for #DOCaught!#" },
			[4] = { str = "Clear all the mobs and at the bottom of the little pit, accept #GETSuntara Stones pt.1# escort him to #COORD[74,19]# and when he dies grab the note which starts #GETSuntara Stones pt.2#", x = 74, y = 19, zone = "Searing Gorge" },
			[5] = { str = "Run back down near the outhouse at #COORD[65,62]# and get the last of your geologist kills if you need them and turn in #INCaught!# at the outhouse, accept #GETLedger From Tanaris# and grab the book he slips you under the door.", x = 65, y = 62, zone = "Searing Gorge" },
			[6] = { str = "Run down to #COORD[71,72]# and kill #NPCMargol the Rager#, and grab Margol's Horn off him which starts #GETThe Horn of the Beast# This gives you the searing gorge key, useless now that there is a FP here but good XP", x = 71, y = 72, zone = "Searing Gorge" },
			[7] = { str = "Run over to #COORD[39,38]# and accept #GETDivine Retribution# then talk to him until completed, accept #GETThe Flawless Flame#", x = 39, y = 38, zone = "Searing Gorge" },
			[8] = { str = "Run up to Thorium Point at #COORD[38,26]#", x = 38, y = 26, zone = "Searing Gorge" },
			[9] = { str = "Grab these quests off the sign: #GETWANTED: Overseer Maltorius# (this will require a group) #GETSTOLEN: Smithing Tuyere and Lookout's Spyglass# and #GETJOB OPPORTUNITY: Culling the Competition#" },
			[10] = { str = "Accept #GETCurse These Fat Fingers# #GETFiery Menace!# #GETIncendosaurs? Whateverosaur is More Like It# near the tower" },
			[11] = { str = "Under the tent accept #GETWhat The Flux?#" },
			[12] = { str = "Grab the FP and fly to IF" },
			[13] = { str = "Stop at #COORD[71,16]# and turn in #INSuntara Stones pt.2# accept #GETDwarven Justice#", x = 71, y = 16, zone = "Searing Gorge" },
			[14] = { str = "Fly to Thelsamar" },
			[15] = { str = "Run down to #COORD[18,83]# and turn in #INThe Horn of the Beast# accept #GETProof of Deed#", x = 18, y = 83, zone = "Searing Gorge" },
			[16] = { str = "Hearth to IF" },
			[17] = { str = "Go to #COORD[69,11]# turn in, #INProof of Deed#, accept #GETAt Last!#", x = 69, y = 11, zone = "Searing Gorge" },
			[18] = { str = "Go to #COORD[75,23]# and accept #GETA Little Slime Goes A Long Way#", x = 75, y = 23, zone = "Searing Gorge" },
			[19] = { str = "Fly to Thelsamar and run to #COORD[18,83]#", x = 18, y = 83, zone = "Searing Gorge" },
			[20] = { str = "Turn in #INAt Last!# put the key on your keyring. Easy 12k xp" },
			[21] = { str = "Now the fun part, doing all these quests. Some of the mobs you have to kill are in a widespread area so I really won’t list coords on them." },
			[22] = { str = "From here south kill glassweb spiders for #DOLedger From Tanaris#" },
			[23] = { str = "Kill any golems you see over here for #DOThe Flawless Flame#" },
			[24] = { str = "Go around the southern part of the cauldron (the pit) and circle it back towards TP and do the following:" },
			[25] = { str = "Kill heavy war golems and infernal elementals (not magma elementals for #DOThe Flawless Flame# and heavy war golems for #DOCurse These Fat Fingers#" },
			[26] = { str = "Kill dark iron lookouts and steamsmiths (Only 6 of them, so come back if they don’t drop, they seem to drop outhouse key a lot) for #DOSTOLEN: Smithing Tuyere and Lookout's Spyglass#" },
			[27] = { str = "Turn in #INThe Flawless Flame# accept #GETForging the Shaft# when you’re near TB again." },
			[28] = { str = "Kill greater lava spiders (not searing) for #DOFiery Menace!# Mostly SW" },
			[29] = { str = "If the Grimesilt Outhouse Key dropped, use it to start #GETThe Key to Freedom# and turn it in at #COORD[65,62]#", x = 65, y = 62, zone = "Searing Gorge" },
			[30] = { str = "Go to #COORD[63,38]# and start going down into the cauldron.", x = 63, y = 38, zone = "Searing Gorge" },
			[31] = { str = "Kill dark iron taskmasters and slavers down here and inside the cave if you see them for #DOJOB OPPORTUNITY: Culling the Competition and Forging the Shaft#" },
			[32] = { str = "Enter the caves at #COORD[41,54]#", x = 41, y = 54, zone = "Searing Gorge" },
			[33] = { str = "Go in the cave to #COORD[41,25]# and go through the jail bar door, turn in #INDwarven Justice# accept #GETRelease Them#", x = 41, y = 25, zone = "Searing Gorge" },
			[34] = { str = "Go up the ramp and stay right until #COORD[40,35]# kill the boss here for #DOWANTED: Overseer Maltorius# and grab #DOWhat The Flux?# on the rail behind him. If you can’t find a group have the pet get the aggro and run the guys away from the plans. This is doable with 2 people but very tough. If you can’t get this quest done no big deal but I usually get it done.", x = 40, y = 35, zone = "Searing Gorge" },
			[35] = { str = "Keep following the path that goes outside and curves back in. You’ll come to a big dead end area with lots of Incendosaur for #DOIncendosaurs? Whateverosaur is More Like It# Save the scales" },
			[36] = { str = "Grind until youre 36k from leveling" },
			[37] = { str = "Die on purpose so you end up back at TP and turn in these quests" },
			[38] = { str = "Go next to the sign, turn in #INWANTED: Overseer Maltorius#" },
			[39] = { str = "To the right of the tower, turn in #INCurse These Fat Fingers# #INFiery Menace!# and #INIncendosaurs? Whateverosaur is More Like It#" },
			[40] = { str = "Go to the tent behind here, turn in #INSTOLEN: Smithing Tuyere and Lookout's Spyglass# and #INJOB OPPORTUNITY: Culling the Competition#" },
			[41] = { str = "Go to the next tent, turn in #INWhat The Flux?#" },
			[42] = { str = "Once this is all handed in you can now do repeat quests for small xp and faction with TB. The reason I said to save the scales or sell them" },
			[43] = { str = "You should be a hair from level 51 now, go south of base to #COORD[38,38]#", x = 38, y = 38, zone = "Searing Gorge" },
			[44] = { str = "Turn in #INForging the Shaft# accept #GETThe Flame’s Casing#" },
			[45] = { str = "Now you shoud be between 1-2 bars into level 51" },
			[46] = { str = "Run over to the path up the mountain at #COORD[24,32]#", x = 24, y = 32, zone = "Searing Gorge" },
			[47] = { str = "Kill the elites 1 by 1 on your way up to the lava pit at #COORD[29,25]# and clear the mobs around it, the idolators don’t chain link and don’t attack when you touch the rock in the center. Jump on the rock either with mount or jump in lava then on it. Open it for #GETRelease Them#", x = 29, y = 25, zone = "Searing Gorge" },
			[48] = { str = "While killing these guys around the pool you should have found a Symbol of Ragnaros for #DOThe Flame’s Casing# if not kill until you do" },
			[49] = { str = "Make sure you talk to the caged npc next to the lava, he gives you #GETPrayer to Elune pt.1# Listen to his short story and turn it in for #GETPrayer to Elune pt.2# Now you have to kill these for the Rag dropping and the Prayer of Elune, Easy drops" },
			[50] = { str = "Go down to #COORD[38,38]# and turn in #INThe Flame’s Casing# accept #GETThe Torch of Retribution pt.1# then turn it back in accept #GETThe Torch of Retribution pt.2# then grab the torch in front of him and complete it and accept #GETSquire Maltrake# and turn that back in and accept #GETSet Them Ablaze!#", x = 38, y = 38, zone = "Searing Gorge" },
			[51] = { str = "Now equip the staff and run to each of the 4 towers at N:#COORD[33,53]# W:#COORD[36,60]# S:#COORD[44,61]# E:#COORD[50,54]# and either kill the guys downstairs, and run up and light the brazier." },
			[52] = { str = "When you get them all, look for a safe spot to jump down and go in the caves at #COORD[41,54]# again and through the jail bar door at #COORD[37,44]# and run to the room with the golem at #COORD[41,25]# and touch the candle covered stone and turn in Release Them SKIP the next part unless you wanna do it with a group, it’s very tough you have to fight that golem and a dwarf both elites.", x = 41, y = 54, zone = "Searing Gorge" },
			[53] = { str = "Die on purpose so you end up at TP and go down to #COORD[29,38]# and turn in #INSet Them Ablaze!# watch the cutscene as he turns into a dragon", x = 29, y = 38, zone = "Searing Gorge" },
			[54] = { str = "Open the chest on the ground accept #GETTrinkets...# then open it again and complete it. Open it and keep the Black Dragonflight Molt for later In the Burning Steppes." },
			[55] = { str = "Fly to the Blasted Lands and run up into the Swamp of Sorrows" },
			[56] = { str = "Go to #COORD[81,91]# and look for a named murloc #NPCJarquia# for #DOLedger From Tanaris#", x = 81, y = 91, zone = "Swamp of Sorrows" },
			[57] = { str = "Once you kill him hearth to IF then either get a portal to Darnassus or fly to Menethil then sail to Auberdine and fly to Darnassus" },
			[58] = { str = "Go to the top of the temple of the moon at #COORD[38,80]# and turn in #INPrayer to Elune pt.2#", x = 38, y = 80, zone = "darnassus" },
			[59] = { str = "Go to the next section up here and turn in #INRise of the Silithid# accept #GETMarch of the Silithid#" },
			[60] = { str = "Go to 34,9 at the top of the tower and turn in #INAssisting Arch Druid Staghelm# accept #GETUn'Goro Soil#", x = 34, y = 9, zone = "darnassus" },
			[61] = { str = "Make Darnassus your home at #COORD[67,15]#", x = 67, y = 15, zone = "darnassus" },
			[62] = { str = "Now either fly to Theramore or sail to Menethil then to Theramore" },
			[63] = { str = "Get first aid up to 290 if you haven’t for heavy runecloth bandages" },
			[64] = { str = "Go over to #COORD[54,55]# to the wrecked ship and grab the overdue package for #DOLedger From Tanaris#", x = 54, y = 55, zone = "Duskwallow Marsh" },
			[65] = { str = "Go to the cave at #COORD[31,66]# and touch the scroll in the back of the cave which turns in #INCortello's Riddle pt.2# accept #GETCortello's Riddle pt.3#", x = 31, y = 66, zone = "Duskwallow Marsh" },
			[66] = { str = "Aggro all the raptors and die so you end up at Theramore" },
			[67] = { str = "Fly to Gadgetzan" },
			[68] = { str = "Just as you enter Gadgetzan, turn in #INLedger From Tanaris#" },
			[69] = { str = "Get your level 52 set gloves out of the bank or mail for later" },
			[70] = { str = "Between the 2 North gates accept #GETSuper Sticky#" },
			[71] = { str = "Go to the hut just west and turn in #INMarch of the Silithid# accept #GETBungle in the Jungle#" },
			[72] = { str = "Run down into the Un’Goro Crater at #COORD[26,52]#", x = 26, y = 52, zone = "Tanaris" },
		}
	},

-----------51-52 Un’Goro Crater
	--[502] = {
	[5152] = {
		title = "51-52 Un’Goro Crater",
		--n = "51-52 Un’Goro Crater",
		--pID = 501, nID = 503,
		--itemCount = 34,
		items = {
			[1] = { str = "51-52 Un’Goro Crater" },
			[2] = { str = "Keep an eye out for the following items laying around the crater: Power Crystals (need 7 of red,blue,green,yellow), Un’Goro Dirt Piles (get as many as you can), and Bloodpetal Sprouts: save in sets of 15" },
			[3] = { str = "I tell you to grind through the raptors here only for 1 reason. To find the item #NPCA Mangled Journal#. Once you have it you don’t have to grind through the raptors." },
			[4] = { str = "Follow the path down to the waterfall at #COORD[71,75]# and accept #GETThe Apes of Un'Goro# and #GETThe Fare of Lar'Korwi#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[5] = { str = "Grind to #COORD[62,68]# and click on the wrecked raft, accept #GETIt's A Secret to Everybody pt.1# then take 2 steps under the water, turn it in and accept #GETIt's A Secret to Everybody pt.2#", x = 62, y = 68, zone = "Un’Goro Crater" },
			[6] = { str = "Grind to #COORD[68,56]# and get the meat off the big dinosaur for #DOThe Fare of Lar'Korwi#", x = 68, y = 56, zone = "Un’Goro Crater" },
			[7] = { str = "Go back to #COORD[71,75]# and turn in #INThe Fare of Lar'Korwi# accept #GETThe Scent of Lar'Korwi#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[8] = { str = "Grind west to about #COORD[67,63]# and there will be 2 spots with a bunch of eggs. Clear the raptors around it and stand on the eggs to get the mates to spawn for #DOThe Scent of Lar'Korwi#", x = 67, y = 63, zone = "Un’Goro Crater" },
			[9] = { str = "Once you have this done, go back to #COORD[71,75]# and turn in #INThe Scent of Lar'Korwi# accept #GETThe Bait For Lar'Korwi# you should have found the jornal by now as well, if not keep grinding raptors while you’re questing in this spot. If you have start the quest #GETWilliden’s Journal#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[10] = { str = "Go up to #COORD[79,49]# it’s off to the east side in the mountains, behind the east pylon. You’ll see a big skeleton which is also the GY. There is a fairly big flat stone, stand on it and use the meat and phermone. This will summon Lar’Korwi for #DOThe Bait For Lar'Korwi# super easy kill even at 51 and he’s 56, he has 3600 hp.", x = 79, y = 49, zone = "Un’Goro Crater" },
			[11] = { str = "Go to #COORD[46,13]# and accept #GETChasing A-Me 01# and run up the path behind her into Marshal’s Refuge.", x = 46, y = 13, zone = "Un’Goro Crater" },
			[12] = { str = "Just to the left accept #GETShizzle's Flyer#" },
			[13] = { str = "Next to the left, a little bit back, accept #GETMuigin and Larion#" },
			[14] = { str = "Next, near the sign accept #GETLost!# and on the sign accept #GETBeware of Pterrordax#" },
			[15] = { str = "In front of the cave, accept #GETRoll the Bones#" },
			[16] = { str = "If you have at least 15 bloodpetal sprouts, turn them in at the kodo for the repeatable quest #GETDadanga is Hungry!# you can get a very rare and expensive recipe so it's worth trying." },
			[17] = { str = "To the right of the cave, accept #GETAlien Ecology#" },
			[18] = { str = "To the right again, turn in #INWilliden’s Journal# accept #GETExpedition Salvation#" },
			[19] = { str = "Run just south a bit and you’ll fine Linken just outside of a half hollow tree. Turn in #INIt's A Secret to Everybody pt.2# accept #GETIt's A Secret to Everybody pt.3#" },
			[20] = { str = "Get the FP to the right of the cave (added in 1.11) then go in the cave all the way to the end and accept #GETCrystals of Power# and then turn it in. Accept the 3 pylon quests #GETThe Northern Pylon# #GETThe Eastern Pylon# #GETThe Western Pylon#" },
			[21] = { str = "When ever you see the following mobs kill them on sight until the quest associate with them is finished." },
			[22] = { str = "Kill bloodpetals for #DOMuigin and Larion#" },
			[23] = { str = "Kill diametradons and pterrodaxes for #DOShizzle's Flyer# and #DORoll the Bones#" },
			[24] = { str = "Kill pterrodaxes and frenzied pterrodaxes for #DOBeware of Pterrordax#" },
			[25] = { str = "Go east along the mountains to #COORD[54,13]# and take that path up examine the pylon for #DOThe Northern Pylon# and go farther north, there should be sone pterrodaxes.", x = 54, y = 13, zone = "Un’Goro Crater" },
			[26] = { str = "Go east to #COORD[63,16]# and kill gorillas for #DOThe Apes of Un'Goro# then go in the cave and stay right to turn in #INChasing A-Me 01# SKIP the next part for now", x = 63, y = 16, zone = "Un’Goro Crater" },
			[27] = { str = "You’re gonna see a bunch of black lakes near the north of the map around #COORD[52,23]# Kill the tar monsters around the lakes for #DOSuper Sticky# The 3 lakes south of the gorillas around #COORD[61,27]# have lower level tar monsters and there is also bloodpetals around here for #DOMuigin and Larion# there is also diametradons and pterrodaxes for #DOShizzle's Flyer# running around", x = 61, y = 27, zone = "Un’Goro Crater" },
			[28] = { str = "Stop at #COORD[68,36]# and grab the crate of foodstuff for #DOExpedition Salvation#", x = 68, y = 36, zone = "Un’Goro Crater" },
			[29] = { str = "Try to collect all the stuff for #DOShizzle's Flyer# out here if you aren’t just going around looking for them alone. I always seem to find them all before I finish the bloodpetals." },
			[30] = { str = "Go to #COORD[76,51]# and follow the path up to the pylon for #DOThe Eastern Pylon# and there should be pterrodaxes further south at #COORD[75,61]#", x = 76, y = 51, zone = "Un’Goro Crater" },
			[31] = { str = "Go to #COORD[71,75]# and turn in #INThe Bait For Lar'Korwi# and #INThe Apes of Un'Goro# SKIP the next part for now", x = 71, y = 75, zone = "Un’Goro Crater" },
			[32] = { str = "Now if you grinded a lot like I did on those flowers and dinosaurs, you should be really close to level 52 if not level 52 already." },
			[33] = { str = "Just east of the volcano (center of map) there are pterrodaxes all for #DOBeware of Pterrordax# if you’re having trouble finding them there is a spawn of 6 of them all the way south at #COORD[55,90]#", x = 55, y = 90, zone = "Un’Goro Crater" },
			[34] = { str = "Run west to #COORD[55,73]# there is a diametradon camp of about 5-6 Kill these if you need scales still for #DOShizzle's Flyer# or #DORoll the Bones#", x = 55, y = 73, zone = "Un’Goro Crater" },
			[35] = { str = "Go west to #COORD[50,77]# into the slithering scar, at the fork go left into the big room, stand in the middle, use the scraping vial for #DOAlien Ecology#", x = 50, y = 77, zone = "Un’Goro Crater" },
			[36] = { str = "There is another diametradon camp if you still need scales or bones for #DOShizzle's Flyer# or #DORoll the Bones# and they’re also all over now" },
			[37] = { str = "Run to the camp at #COORD[38,65]# and grab the research equipment for #DOExpedition Salvation#", x = 38, y = 65, zone = "Un’Goro Crater" },
			[38] = { str = "Kill frenzied pterrodaxes all around #COORD[35,38]# (they’re everywhere) in the NW part of the map for #DOBeware of Pterrordax# plus there are many diametradons here for #DOShizzle's Flyer# or #DORoll the Bones#", x = 35, y = 38, zone = "Un’Goro Crater" },
			[39] = { str = "Go down to #COORD[23,59]# and touch the western pylon for #DOThe Western Pylon# and kill any pterrodaxes you need behind it", x = 23, y = 59, zone = "Un’Goro Crater" },
			[40] = { str = "Go to #COORD[30,50]# and accept #DOFinding the Source#", x = 30, y = 50, zone = "Un’Goro Crater" },
			[41] = { str = "Go over to Fire Plume Ridge at #COORD[51,48]# and kill elementals, try to avoid anything 56+ for #DOVolcanic Activity# Leave blazing invaders alone", x = 51, y = 48, zone = "Un’Goro Crater" },
			[42] = { str = "Once you have that done, dismiss pet and mount up towards the top of the volcano and look for what looks like the instance waiting stones but with fire cracks in it. Dismount and FD then if there is a mob near it put pet on it and use the thermometer for Finding the Source there is more than one and it doesn’t have to be at the top I see them at the bottom too." },
			[43] = { str = "Unless you need ashes still run to #COORD[30,50]# and turn in #INFinding the Source# accept #GETThe New Springs#", x = 30, y = 50, zone = "Un’Goro Crater" },
			[44] = { str = "Go up into the cave (in the same manner) at #COORD[51,49]# and turn in #INLost!# then accept #GETA Little Help From My Friends# he follows you, once you get him out of the ridge it’s easy. Just go straight out the cave over the edge, if done right you only have to fight 1 element. Once you go north past the river it’s pie.", x = 51, y = 49, zone = "Un’Goro Crater" },
			[45] = { str = "When you get him back to town run up near the sign by the cave and it will complete then turn it in and #INBeware of Pterrordax#" },
			[46] = { str = "Turn in #INShizzle's Flyer#" },
			[47] = { str = "Turn in #INMuigin and Larion# SKIP the rest" },
			[48] = { str = "Turn in #INRoll the Bones#" },
			[49] = { str = "Turn in #INAlien Ecology#" },
			[50] = { str = "Turn in #INExpedition Salvation#" },
			[51] = { str = "In the back of the cave turn in #INThe Northern Pylon# #INThe Eastern Pylon# #INThe Western Pylon# accept #GETMaking Sense of It# then turn it back in. She then tells you about buffs from the pylons." },
			[52] = { str = "Run to #COORD[29,22]# and follow the path into Slithus to #COORD[50,34]# grab the FP and fly to Gadgetzan.", x = 29, y = 22, zone = "Un’Goro Crater" },
			[53] = { str = "Go to the NW part of town, turn in #INBungle in the Jungle# SKIP the next part then turn in #INSuper Sticky# between the 2 entrances" },
			[54] = { str = "Hearth to Darnassus and get new skills" },
			[55] = { str = "You should have at least 50+ soils now." },
			[56] = { str = "Go to 31,8 and turn in #INUn'Goro Soil#", x = 31, y = 8, zone = "Darnassus" },
			[57] = { str = "Now go up to the top of the tower and accept #GETMorrowgrain Research pt.1# then go downstairs and turn it in, accept #GETMorrowgrain Research pt.2#" },
			[58] = { str = "Now you might want to get extra seed packets depending on how many soils you have. You can use the pouch every 10 minutes and you won’t always get a morrowgrain. All you need is 10 anyway" },
			[59] = { str = "Run through to Rut’theran Village and go in the house to the right and accept #GETMoontouched Wildkin# it’s a winterspring feather quest" },
			[60] = { str = "Fly to Astranaar, then ride all the way east on the road to #COORD[91,46]# which goes into Azshara", x = 91, y = 46, zone = "Ashenvale" },
		}
	},

-----------52-53 Azshara
	--[503] = {
	[5253] = {
		title = "52-53 Azshara",
		--n = "52-53 Azshara",
		--pID = 502, nID = 504,
		--itemCount = 10,
		items = {
			[1] = { str = "52-53 Azshara" },
			[2] = { str = "Just as you enter, on the right at #COORD[11,77]# grab the FP", x = 11, y = 77, zone = "Azshara" },
			[3] = { str = "Just behind him, accept #GETSpiritual Unrest# and #GETA Land Filled With Hatred#" },
			[4] = { str = "Go just north to around #COORD[14,72]# and #COORD[16,67]#and kill all the ghosts around here until you complete #DOSpiritual Unrest#", x = 14, y = 72, zone = "Azshara" },
			[5] = { str = "Go just north to #COORD[19,61]# and kill all the satyr’s around here for #DOA Land Filled With Hatred", x = 19, y = 61, zone = "Azshara" },
			[6] = { str = "Go back to #COORD[11,77]# and turn in #INSpiritual Unrest# and #INA Land Filled With Hatred#", x = 11, y = 77, zone = "Azshara" },
			[7] = { str = "Go to #COORD[39,55]# and get the Markri rubbing for #DOArcane Runes#", x = 39, y = 55, zone = "Azshara" },
			[8] = { str = "Go to #COORD[36,53]# and get the Beth’Amara Rubbing for #DOArcane Runes#", x = 36, y = 53, zone = "Azshara" },
			[9] = { str = "Go to #COORD[39,50]# and get the Jin’yael rubbing for #DOArcane Runes#", x = 39, y = 50, zone = "Azshara" },
			[10] = { str = "Go to #COORD[42,42]# and turn in #INThe Hunter's Charm# accept #GETCourser Antlers# this quest and the follow up are optional to do after you turn level 53, I do them so if you don’t you’ll be behind a little on the guide. It takes about 1-2 hours to get all the pieces for this and the next quest but will put you about 20-25% into the level", x = 42, y = 42, zone = "Azshara" },
		}
	},

------------53-54 Felwood
	--[504] = {
	[5354] = {
		title = "53-54 Felwood",
		--n = "53-54 Felwood",
		--pID = 503, nID = 505,
		--itemCount = 51,
		items = {
			[1] = { str = "53-54 Felwood" },
			[2] = { str = "Stop at #COORD[54,86]# and accept #GETCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[3] = { str = "Run north a little bit to #COORD[51,81]# and accept #GETForces of Jaedenar#", x = 51, y = 81, zone = "Felwood" },
			[4] = { str = "Inside the house, accept #GETThe Corruption of the Jadefire#" },
			[5] = { str = "Under the tent accept #GETVerifying the Corruption# and #GETTo Winterspring!#" },
			[6] = { str = "Just across the road accept #GETTimbermaw Ally#" },
			[7] = { str = "Go just SW of here around #COORD[48,91]# and kill the Furlbogs until you finish #DOTimbermaw Ally# Just grind them all for rep until you’re done", x = 48, y = 91, zone = "Felwood" },
			[8] = { str = "Go back to #COORD[50,85]# and turn in #INTimbermaw Ally# accept #GETSpeak to Nefian# the other is repeatable for rep", x = 50, y = 85, zone = "Felwood" },
			[9] = { str = "Go up near the 2 lakes at #COORD[40,69]# and kill the cursed oozes for the first part of #DOA Little Slime Goes A Long Way pt.1#", x = 40, y = 69, zone = "Felwood" },
			[10] = { str = "Go to the west of here now to #COORD[37,69]# and kill the jadefire demons for #DOThe Corruption of the Jadefire# these are good to farm too.", x = 37, y = 69, zone = "Felwood" },
			[11] = { str = "Go up to #COORD[39,59]# and kill the tainted oozes for the second part of #DOA Little Slime Goes A Long Way pt.1", x = 39, y = 59, zone = "Felwood" },
			[12] = { str = "Go just west of here around #COORD[37,59]# and kill the Jaedenar for #DOForces of Jaedenar# You don’t have to go in the caves.", x = 37, y = 59, zone = "Felwood" },
			[13] = { str = "Go back to #COORD[51,82]# and turn in #INForces of Jaedenar# accept #GETCollection of the Corrupt Water#.", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "Inside the house turn in #INThe Corruption of the Jadefire# accept #GETFurther Corruption#" },
			[15] = { str = "Go back up to Jaedenar to the green pool at #COORD[35,59]# and fill the canteen for #DOCollection of the Corrupt Water#", x = 35, y = 59, zone = "Felwood" },
			[16] = { str = "Go back to #COORD[51,82]# and turn in #INCollection of the Corrupt Water# accept #GETSeeking Spiritual Aid#", x = 51, y = 82, zone = "Felwood" },
			[17] = { str = "Go up to #COORD[42,20]# and kill Entropic beasts and horrors and explore the craters for #DOVerifying the Corruption#.", x = 42, y = 20, zone = "Felwood" },
			[18] = { str = "Go up to #COORD[46,14]# and follow it to the back, killing the demons for #DOFurther Corruption# When you kill Xavaric he'll drop Flute of Xavaric which starts #GETFlute of Xavaric# kill the satyr’s to complete this.", x = 46, y = 14, zone = "Felwood" },
			[19] = { str = "Run over to Irontree Cavern at #COORD[55,17]# and kill 15 of the elementals and that should be enough for #DOCleansing Felwood#", x = 55, y = 17, zone = "Felwood" },
			[20] = { str = "Go up to #COORD[62,24]# and get the FP", x = 62, y = 24, zone = "Felwood" },
			[21] = { str = "Go north to 64,8 and turn in #INSpeak to Nefian# accept #GETDeadwood of the North#", x = 64, y = 8, zone = "Felwood" },
			[22] = { str = "Now fall off the cliff to the west and start killing for Deadwood of the North once you’re done you want to kill until you’re 150 rep from the next rank with the timbermaw (put the rep as an xp bar for ease)" },
			[23] = { str = "Go back to 64,8 and turn in #INDeadwood of the North# and you should be unfriendly now and not aggro’d any longer. Accept #GETSpeak to Salfa# and turn in any 5 sets of feathers for extra rep and 550 xp", x = 64, y = 8, zone = "Felwood" },
			[24] = { str = "Go through the cave to Winterspring and just outside the cave to the right at #COORD[27,34]# turn in #INSpeak to Salfa#", x = 27, y = 34, zone = "Winterspring" },
			[25] = { str = "Run south to #COORD[31,45]# and turn in #INThe New Springs# accept #GETStrange Sources# also turn in #INIt's A Secret to Everybody pt.3# accept #GETThe Videre Elixir# and #GETThreat of the Winterfall#", x = 31, y = 45, zone = "Winterspring" },
			[26] = { str = "Run back throug the cave and go west at the fork into Moonglade." },
			[27] = { str = "Go to #COORD[48,67]# and grab the FP", x = 48, y = 67, zone = "Moodglade" },
			[28] = { str = "You should be very close leveling now. You can grind the rest of the way. Hearth to Astranaar and fly to Feralas" },
			[29] = { str = "Go in the Inn, accept #GETJonespyre's Request#" },
			[30] = { str = "Go up to the top of the tower, turn it in, accept #GETThe Mystery of Morrowgrain# turn it back in unless you’re still making the stuff." },
			[31] = { str = "Go up to #COORD[45,25]# and buy a bait and read on how to get the videre elixir", x = 45, y = 25, zone = "Feralas" },
			[32] = { str = "At #COORD[45,16]# you can be put up to the top of the colossal tower and parachute down. Just make sure you unmount!", x = 45, y = 16, zone = "Feralas" },
			[33] = { str = "Go up to #COORD[44,10]# and place the bait on the ground then go loot an everroot", x = 44, y = 10, zone = "Felalas" },
			[34] = { str = "Go back south to #COORD[45,25]# to get your 3 videre elixir", x = 45, y = 25, zone = "Felalas" },
			[35] = { str = "Hearth to Astranaar" },
			[36] = { str = "Run back up into Felwood to #COORD[54,86]# and turn in #INCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[37] = { str = "Now she allows you to get stuff for some neat potions that are on different cooldowns than potions are." },
			[38] = { str = "Go up to #COORD[51,81]# and in the house turn in #INFurther Corruption# and #INFlute of Xavaric# accept #GETFelbound Ancients#", x = 51, y = 81, zone = "Felwood" },
			[39] = { str = "Under the tent, turn in #INVerifying the Corruption#" },
			[40] = { str = "Run up to #COORD[62,23]#", x = 62, y = 23, zone = "Felwood" },
			[41] = { str = "Go through the cave to Winterfall and just outside the cave accept #GETWinterfall Activity#" },
			[42] = { str = "Go to #COORD[31,45]# and turn in #INThe Videre Elixir# accept #GETMeet at the Grave#", x = 31, y = 45, zone = "Winterspring" },
			[43] = { str = "Go to #COORD[62,36]# and grab the FP", x = 62, y = 36, zone = "Winterspring" },
			[44] = { str = "Fly to Rachet" },
			[45] = { str = "Run west of the dock and turn in #INVolcanic Activity#" },
			[46] = { str = "Run down to #COORD[65,43]# and turn in #INSeeking Spiritual Aid# accept Cleansed Water Returns to Felwood", x = 65, y = 43, zone = "The Barrens" },
			[47] = { str = "Fly to Theramore and sail to Menethil then fly to IF" },
			[48] = { str = "Just outside the Military Ward there should be a wandering npc, one is near FP too, grab the quest #GETThe New Frontier pt.1#" },
			[49] = { str = "Go to #COORD[75,23]# and turn in #INA Little Slime Goes A Long Way pt.1# accept #GETA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[50] = { str = "Go to 31,4 and turn in #INReturn to Tymor#", x = 31, y = 4, zone = "Ironforge" },
			[51] = { str = "Fly to Menethil then sail to Theramore and fly to Gadgetzan" },
		}
	},

-----------54-54 Tanaris
	--[505] = {
	[5453] = {
		title = "54-54 Tanaris",
		--n = "54-54 Tanaris",
		--pID = 504, nID = 506,
		--itemCount = 20,
		items = {
			[1] = { str = "54-54 Tanaris" },
			[2] = { str = "Get your mithril casing out of your bank or mailbox" },
			[3] = { str = "Go east to the GY at #COORD[54,28]# and drink your videre elixir", x = 54, y = 28, zone = "Tanaris" },
			[4] = { str = "Now you’re gonna die, don’t rez just release and run north to #COORD[53,23]# and turn in #INMeet at the Grave# accept #GETA Grave Situation#", x = 53, y = 23, zone = "Tanaris" },
			[5] = { str = "Go back and rez at #COORD[54,28]# and touch the only tombstone there, turn in #INA Grave Situation# accept #GETLinken's Sword#", x = 54, y = 28, zone = "Tanaris" },
			[6] = { str = "Run into Un’Goro, I’d say fly but we have to go way SE" },
			[7] = { str = "Run up to #COORD[71,75]# and accept #GETThe Mighty U'cha#", x = 71, y = 75, zone = "Un’Goro" },
			[8] = { str = "Keep collecting dirt here if you need more morrowgrain" },
			[9] = { str = "Now all around the crater is slimes but you can find all the ones you need west of the volcano around #COORD[37,37]# for #DOA Little Slime Goes A Long Way pt.2# I think there are more on the west side of the volcano but you can look on both sides they’re scattered. If it says they’re cloning, finish them very fast or stun them. If they clone it’s a full health mob that you can’t scoop up.", x = 37, y = 37, zone = "Un’Goro" },
			[10] = { str = "Go to the cave at #COORD[64,16]# and go to the right, when you see A-Me 01 accept #GETChasing A-Me 01 pt.1# and turn it back in. Fall over the edge and to the right and up around until you see U’cha for #DOThe Mighty U'cha#", x = 64, y = 16, zone = "Un’Goro" },
			[11] = { str = "Run back to the front and go right again and accept #GETChasing A-Me 01 pt.2# now escort her out" },
			[12] = { str = "Escort A-Me to Marshal’s at #COORD[46,13]# and turn in #INChasing A-Me 01 pt.2#", x = 46, y = 13, zone = "Un’Goro" },
			[13] = { str = "Go into Marshal’s and turn in #INLinken's Sword# accept #GETA Gnome's Assistance#" },
			[14] = { str = "Go to the back of the cave and turn in #INA Gnome's Assistance# and accept #GETLinken’s Memory#" },
			[15] = { str = "Run down and let the tar monsters kill you so you’re closer to the SE" },
			[16] = { str = "Run down to #COORD[71,75]# and turn in #INThe Mighty U'cha#", x = 71, y = 75, zone = "Un’Goro" },
			[17] = { str = "You should be over half way to level 55 now" },
			[18] = { str = "Hearth back to Astranaar and fly to Darnassus" },
			[19] = { str = "Go in the Temple of the Moon at #COORD[39,84]# and fill the vial for #DOFelbound Ancients#", x = 39, y = 84, zone = "Darnassus" },
			[20] = { str = "Run into Felwood" },
		}
	},

-----------54-54 Felwood
	--[506] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 505, nID = 507,
		--itemCount = 16,
		items = {
			[1] = { str = "54-54 Felwood" },
			[2] = { str = "Go to #COORD[51,82]# and turn in #INCleansed Water Returns to Felwood# accept #GETDousing the Flames of Protection#", x = 51, y = 82, zone = "Felwood" },
			[3] = { str = "Go in the house, turn in #INFelbound Ancients# accept #GETPurified!# then turn it back in, easy 10k xp. Also turn in #INLinken’s Memory# accept #GETSilver Heart#" },
			[4] = { str = "You should be 70% through now or close to it" },
			[5] = { str = "Start killing all the bears and wolves from here north until you have 11 silvery claws for #DOSilver Heart#" },
			[6] = { str = "Go into the cave at #COORD[35,58]#", x = 35, y = 58, zone = "Felwood" },
			[7] = { str = "At the first open area with the caged npc at #COORD[36,56]# is brazier for #DODousing the Flames of Protection# the 2nd one is just up the ramp", x = 36, y = 56, zone = "Felwood" },
			[8] = { str = "Continue past the room with candles surrounding the hole to the next open room at #COORD[36,53]# for the 3rd and 4th brazier for #DODousing the Flames of Protection#", x = 36, y = 53, zone = "Felwood" },
			[9] = { str = "Don’t even bother trying to do the escort unless you get a group, I always skip it even if I find the key." },
			[10] = { str = "Run back outside and up to #COORD[51,19]# and kill the tree elementals for #DOSilver Heart#", x = 51, y = 19, zone = "Felwood" },
			[11] = { str = "If you want to do the escort with the flute I suggest getting a group you get jumped by a lot of mobs." },
			[12] = { str = "Run all the way back down to #COORD[51,82]# (I know no one wants to run back here, why the quest hub is so far from the FP is beyond me)", x = 51, y = 82, zone = "Felwood" },
			[13] = { str = "Turn in #INDousing the Flames of Protection# SKIP the next part for now" },
			[14] = { str = "In the house turn in #INSilver Heart# accept #GETAquementas#" },
			[15] = { str = "If you have skinning I’m sure you have at least 5 tainted hides, go down to #COORD[54,86]# and turn them in for #INSalve via Skinning#", x = 54, y = 86, zone = "Felwood" },
			[16] = { str = "Hearth to Astranaar and fly to Winterspring" },
		}
	},

--------------54-55 Winterspring
	--[507] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 506, nID = 508,
		--itemCount = 34,
		items = {
			[1] = { str = "54-55 Winterspring" },
			[2] = { str = "Go in Everlook accept #GETEnraged Wildkin pt.1#" },
			[3] = { str = "Go in the Inn, make it your home" },
			[4] = { str = "Accept #GETThe Everlook Report# #GETDuke Nicholas Zverenhoff# and #GETSister Pamela#" },
			[5] = { str = "On the other side of town accept #GETAre We There, Yeti? pt.1#" },
			[6] = { str = "Keep your eye out for those blue moonkin feathers to finish up #DOMoontouched Wildkin#" },
			[7] = { str = "Run all the way south to #COORD[60,73]# to complete #GETStrange Sources#", x = 60, y = 73, zone = "Winterspring" },
			[8] = { str = "Hearth back to Everlook, if it’s not up die on purpose" },
			[9] = { str = "Go to #COORD[65,45]# and kill yeti’s for #DOAre We There, Yeti? pt.1#", x = 65, y = 45, zone = "Winterspring" },
			[10] = { str = "Run back to Everlook and turn in #INAre We There, Yeti? pt.1# accept #GETAre We There, Yeti? pt.2#" },
			[11] = { str = "Go back to #COORD[65,45]# and kill matriarch’s and patriarch’s for #DOAre We There, Yeti? pt.2# there are a lot in the cave at #COORD[67,42]#", x = 67, y = 42, zone = "Winterspring" },
			[12] = { str = "Run back to Everlook and turn in #INAre We There, Yeti? pt.2# accept #GETAre We There, Yeti? pt.3#" },
			[13] = { str = "Go just east of the Inn and scare Legacki for #DOAre We There, Yeti? pt.3#" },
			[14] = { str = "Go east of Winterspring to #COORD[66,34]# and kill the furlbogs there for #DOWinterfall Activity# and part of #DOThreat of the Winterfall#", x = 66, y = 34, zone = "Winterspring" },
			[15] = { str = "Hopefully you’ll find an #NPCEmpty Firewater Flask# on one of them which starts #GETWinterfall Firewater#" },
			[16] = { str = "Run up to Starfall Village at #COORD[51,30]# and turn in #INTo Winterspring!# accept #GETThe Ruins of Kel'Theril#", x = 51, y = 30, zone = "Winterspring" },
			[17] = { str = "Turn in #INEnraged Wildkin pt.1# SKIP part 2 for now also turn in #INThe Ruins of Kel'Theril# accept #GETTroubled Spirits of Kel'Theril#" },
			[18] = { str = "Grab the relic at #COORD[55,42]# for #DOTroubled Spirits of Kel'Theril# dismiss pet before you open them then run and FD. 2nd relic is at #COORD[53,43]#. 3rd at #COORD[52,41]# 4th at #COORD[50,41]#" },
			[19] = { str = "Go west to #COORD[39,43]# and kill furlbog here for #DOThreat of the Winterfall# also make sure you have your 10 feathers for #DOMoontouched Wildkin#", x = 39, y = 43, zone = "Winterspring" },
			[20] = { str = "Go to #COORD[31,45]# and turn in #INStrange Sources# #INThreat of the Winterfall# and #INWinterfall Firewater# accept #GETFalling to Corruption#", x = 31, y = 45, zone = "Winterspring" },
			[21] = { str = "Run to #COORD[27,34]# and turn in #INWinterfall Activity#", x = 27, y = 34, zone = "Winterspring" },
			[22] = { str = "You should now be 25-30% into level 55" },
			[23] = { str = "Run through the tunnel to Felwood" },
			[24] = { str = "Go to 60,5 and touch the cauldron at the camp which turns in #INFalling to Corruption# accept #GETMystery Goo#", x = 60, y = 5, zone = "Winterspring" },
			[25] = { str = "Hearth to Everlook then fly to Darnassus" },
			[26] = { str = "In Rut’theran Village turn in #INMoontouched Wildkin# #COORD[55,92]# accept #GETFind Ranshalla#", x = 55, y = 92, zone = "Darnassus" },
			[27] = { str = "Go into Darnassus up to 34,8 in the big tower and turn in #INThe New Frontier pt.1# accept #GETThe New Frontier pt.2# go down 1 floor and turn that in, accept #GETRabine Saturna#", x = 34, y = 8, zone = "Darnassus" },
			[28] = { str = "Fly to Moonglade to #COORD[51,45]# and turn in #INRabine Saturna# accept #GETWasteland#", x = 51, y = 45, zone = "Moonglade" },
			[29] = { str = "Fly to Auberdine, sail to Menethil and fly to IF, make it your home. Make sure you have your black dragonflight molt" },
			[30] = { str = "Go to #COORD[75,23]# and turn in #INA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[31] = { str = "Go to #COORD[38,55]# in the throne room and accept #GETThe Smoldering Ruins of Thaurissan pt.1# then click on her and listen to the story and turn it back in, accept #GETThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[32] = { str = "In front of the FP accept #GETTaking Back Silithus#" },
			[33] = { str = "Fly to Lakeshire" },
			[34] = { str = "Run north to 46,6 and enter the Burning Steppes", x = 46, y = 6, zone = "Redridge Mountains" },
		}
	},

-----------55-56 Burning Steppes
	--[508] = {
	[5556] = {
		title = "55-56 Burning Steppes",
		--n = "55-56 Burning Steppes",
		--pID = 507, nID = 509,
		--itemCount = 29,
		items = {
			[1] = { str = "55-56 Burning Steppes" },
			[2] = { str = "Go to #COORD[83,63]# and follow the path up and grab the FP", x = 83, y = 63, zone = "Burning Steps" },
			[3] = { str = "Accept #GETExtinguish the Firegut# and #GETFIFTY! YEP!#" },
			[4] = { str = "In front of the broken house, accept #GETDragonkin Menace# This is the start of the Onyxia key chain" },
			[5] = { str = "Start killing ogres all over the mountain at #COORD[81,42]# for #DOExtinguish the Firegut# then run back to #COORD[84,68]# and turn it in, accept #GETGor'tesh the Brute Lord#", x = 81, y = 42, zone = "Burning Steps" },
			[6] = { str = "Go NW to around #COORD[66,40]# and collect the ruins that look like tombstones for #DOThe Smoldering Ruins of Thaurissan pt.2#", x = 66, y = 40, zone = "Burning Steps" },
			[7] = { str = "Run up to #COORD[65,24]# and go in the cave, turn in #INYuka Screwspigot# SKIP the rest", x = 65, y = 24, zone = "Burning Steps" },
			[8] = { str = "Outside accept #GETTablet of the Seven# and #GETBroodling Essence#" },
			[9] = { str = "Go to #COORD[54,40]# and touch the dwarf statue for #DOTablet of the Seven#", x = 54, y = 40, zone = "Burning Steps" },
			[10] = { str = "Go west to #COORD[43,46]# to blackrock stronghold or south to #COORD[49,55]# the pillar of ash and kill the orcs for #DOFIFTY! YEP!# they drop in large amounts", x = 43, y = 46, zone = "Burning Steps" },
			[11] = { str = "While in the pillar of ash at #COORD[40,56]# you should kill Gor’tesh for #DOGor'tesh the Brute Lord#", x = 40, y = 56, zone = "Burning Steps" },
			[12] = { str = "Get a group if you can for #DODragonkin Menace# and then kill the mobs for it just NE of the camp along the east wall. It’s soloable but cutting it Also get 8 of the broodlings for #DOBroodling Essence# by using the device on them before you attack them." },
			[13] = { str = "Go to the cave at #COORD[94,31]# and accept #GETA Taste of Flame# then give him the molt and hand the quest back in. SKIP the next part", x = 94, y = 31, zone = "Burning Steps" },
			[14] = { str = "Run back up to #COORD[65,23]# and turn in #INTablet of the Seven# and #INBroodling Essence# accept #GETFelnok Steelspring#", x = 65, y = 23, zone = "Burning Steps" },
			[15] = { str = "Ride back to #COORD[84,68]# and next to the griffin turn in #INFIFTY! YEP!# and #INGor'tesh the Brute Lord# accept #GETOgre Head On A Stick = Party#", x = 84, y = 68, zone = "Burning Steps" },
			[16] = { str = "In front of the broken house, turn in #INDragonkin Menace# accept #GETThe True Masters pt.1#" },
			[17] = { str = "Run up to the top of the mountin at #COORD[80,45]# and click the soft dirt pile for #DOOgre Head On A Stick = Party# then run back to #COORD[84,68]# and turn it in", x = 80, y = 45, zone = "Burning Steps" },
			[18] = { str = "Fly to Lakeshire and run to the town hall at #COORD[29,44]# and turn in #INThe True Masters pt.1# accept #GETThe True Masters pt.2#", x = 29, y = 44, zone = "Redridge Mountains" },
			[19] = { str = "Fly to SW" },
			[20] = { str = "Go to #COORD[78,18]# into the SW keep and turn in #INThe True Masters pt.2# accept #GETThe True Masters pt.3# then talk to the lady and then turn it back in and accept #GETThe True Masters pt.4#", x = 78, y = 18, zone = "Stormwind City" },
			[21] = { str = "Fly back to Lakeshire and go to the townhall at #COORD[29,44]# and turn in #INThe True Masters pt.4# accept #GETThe True Masters pt.5#", x = 29, y = 44, zone = "Redridge Mountains" },
			[22] = { str = "Fly to the Burning Steppes and turn in #INThe True Masters pt.5# when you land and accept #GETThe True Masters pt.6#" },
			[23] = { str = "Run up to #COORD[64,23]# and listen to ragged john then run back to #COORD[84,68]# and turn in #INThe True Masters pt.6# I SKIP the next part, do it later if you’re worried about speed leveling. That was an easy 30k xp for doing nothing and your ony key chain is started.", x = 64, y = 23, zone = "Burning Steps" },
			[24] = { str = "You should be about 10k from level 56, go grind until 5k on the orcs at #COORD[49,55]#", x = 49, y = 55, zone = "Burning Steps" },
			[25] = { str = "Hearth to IF" },
			[26] = { str = "Go to the throne room at #COORD[38,55]# and turn in #INThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[27] = { str = "You should now be level 56, get new skills" },
			[28] = { str = "Fly to Menethil and sail to Theramore" },
			[29] = { str = "Fly to Gadgetzan" },
		}
	},

-----------56-56 Tanaris
	--[509] = {
	[5655] = {
		title = "56-56 Tanaris",
		--n = "56-56 Tanaris",
		--pID = 508, nID = 510,
		--itemCount = 9,
		items = {
			[1] = { str = "56-56 Tanaris" },
			[2] = { str = "Go to the NW side of town and scare sprinkle for #DOAre We There, Yeti? pt.3#" },
			[3] = { str = "Make Gadgetzan your home" },
			[4] = { str = "To the south of lost rigger cove at #COORD[70,49]# is a bunch of stones in a circle, Loot the stuff from the blue backpack and use the book to summon Aquementas. He’s a level 54 water elemental", x = 70, y = 49, zone = "Tanaris" },
			[5] = { str = "Hearth to Gadgetzan or die if it’s not up yet." },
			[6] = { str = "Fly to Un’goro" },
			[7] = { str = "Find Quixxil and scare him for #DOAre We There, Yeti? pt.3#" },
			[8] = { str = "Go to the back of the cave and turn in #INAquementas# accept #GETLinken's Adventure# and turn it in just outside the cave by the big tree SKIP the next part" },
			[9] = { str = "Fly to Silithus" },
		}
	},

-----------56-56 Silithus
	--[510] = {
	[5656] = {
		title = "56-56 Silithus",
		--n = "56-56 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 42,
		items = {
			[1] = { str = "56-56 Silithus" },
			[2] = { str = "Near the moonwell accept #GETThe Twilight Mystery#" },
			[3] = { str = "In front of the Inn, turn in #INTaking Back Silithus# accept #GETSecuring the Supply Lines#" },
			[4] = { str = "SKIP the quest on the sign unless you get a group" },
			[5] = { str = "Make Cenarion Hold your home" },
			[6] = { str = "Upstairs accept #GETDeadly Desert Venom#" },
			[7] = { str = "There seems to be a lot of white quests because there's many AQ quests that you don’t have to worry about yet." },
			[8] = { str = "Go do #DOSecuring the Supply Lines# and #DODeadly Desert Venom# North and NE of town all around #COORD[55,24]# the dredges, scorpids, and skitterers for these 2 quests are all over this area.", x = 55, y = 24, zone = "Silithus" },
			[9] = { str = "Run up to #COORD[81,18]# and turn in #INWasteland# accept #GETThe Spirits of Southwind#", x = 81, y = 18, zone = "Silithus" },
			[10] = { str = "Run up NW to around 22.9 and pick up the twilight tablet fragments for #DOThe Twilight Mystery# They litter this spot", x = 22, y = 9, zone = "Silithus" },
			[11] = { str = "Hearth to Cenarion Hold" },
			[12] = { str = "Up stairs turn in #INDeadly Desert Venom# accept #GETNoggle's Last Hope#" },
			[13] = { str = "In front of the Inn, turn in #INSecuring the Supply Lines# accept #GETStepping Up Security#" },
			[14] = { str = "Go next to the moonwell and turn in #INThe Twilight Mystery# accept #GETThe Deserter#" },
			[15] = { str = "You should be about 30-35% into level 56" },
			[16] = { str = "Go SE to #COORD[62,53]# and kill the undead mobs here for #DOThe Spirits of Southwind# be careful when they die they spawn 1-2 bugs", x = 62, y = 53, zone = "Silithus" },
			[17] = { str = "Kill the pincers for #DONoggle's Last Hope# and drudges for #DOThe Deserter# south of here around #COORD[56,58]#", x = 56, y = 58, zone = "Silithus" },
			[18] = { str = "Go to the cave at #COORD[67,69]# and turn in #INThe Deserter# accept #GETThe Twilight Lexicon#", x = 67, y = 69, zone = "Silithus" },
			[19] = { str = "You can find flayers and stalkers outside of the cave for #DONoggle's Last Hope# they are also both around #COORD[43,72]# on the other side of the hive", x = 43, y = 72, zone = "Silithus" },
			[20] = { str = "Hearth back to Cenarion Hold or die so you end up there" },
			[21] = { str = "Go upstairs and turn in for #INNoggle's Last Hope# accept #GETNoggle's Lost Satchel#" },
			[22] = { str = "Outside the Inn, turn in #INStepping Up Security#" },
			[23] = { str = "Go to #COORD[29,35]# and kill Twilight Keeper Manya for #DOThe Twilight Lexicon# she fears a bit. She’s at the SE corner of came", x = 29, y = 35, zone = "Silithus" },
			[24] = { str = "Go to #COORD[41,41]# and kill Twilight Keeper Havanuth for #DOThe Twilight Lexicon# he’s on the east side of camp, he has a nasty aoe", x = 41, y = 41, zone = "Silithus" },
			[25] = { str = "Go all the way down south to the little camp at #COORD[42,90]# and go up the hill behind it, you’ll find Deathclasp, in the middle of the path on the wall is a pouch, grab it when deathclasp is in the back for #DONoggle's Lost Satchel#", x = 42, y = 90, zone = "Silithus" },
			[26] = { str = "Head to the SW to #COORD[16,87]# and kill Twilight Keeper Exeter for #DOThe Twilight Lexicon# he’s at the SW corner of camp", x = 16, y = 87, zone = "Silithus" },
			[27] = { str = "Go back to the cave at #COORD[67,69]# and turn in #INThe Twilight Lexicon# accept #GETA Terrible Purpose# He also offers another quest for 10 twilight texts, this is more for cen circle rep later on", x = 67, y = 69, zone = "Silithus" },
			[28] = { str = "Run up to #COORD[81,18]# and turn in #INThe Spirits of Southwind# accept #GETHive in the Tower#", x = 81, y = 18, zone = "Silithus" },
			[29] = { str = "Go to the top of the tower at #COORD[61,52]# Be careful 3 bugs spawn when you enter. Shift right click the pod because as soon as you open it some amushers spawn. Kill at least 1 and loot it for #DOHive in the Tower#", x = 61, y = 52, zone = "Silithus" },
			[30] = { str = "Go up to #COORD[81,18]# and turn in #INHive in the Tower# accept #GETUmber, Archivist#", x = 81, y = 18, zone = "Silithus" },
			[31] = { str = "Hearth to Cenarion Hold" },
			[32] = { str = "." },
			[33] = { str = "Go upstairs and turn in #INNoggle's Lost Satchel#" },
			[34] = { str = "Go into the long building and turn in #INA Terrible Purpose#" },
			[35] = { str = "Fly to Moonglade" },
			[36] = { str = "Go to #COORD[44,35]# and turn in #INUmber, Archivist# accept #GETUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[37] = { str = "Run over to #COORD[51,44]# and turn in #INUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[38] = { str = "You should now be 80-85% into leveling" },
			[39] = { str = "Fly to Auberdine and sail to Menethil then fly to IF" },
			[40] = { str = "Make IF your home, then find the wandering commander dwarf and accept #GETA Call To Arms: The Plaguelands!#" },
			[41] = { str = "Fly to Southshore" },
			[42] = { str = "Run north into Alterac Mountains and over NE to #COORD[80,34]# and run into Western Plaguelands (WPL)", x = 80, y = 34, zone = "Alterac Mountains" },
		}
	},

------------56-57 Western Plaguelands
	--[511] = {
	[5657] = {
		title = "56-57 Western Plaguelands",
		--n = "56-57 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 43,
		items = {
			[1] = { str = "56-57 Western Plaguelands" },
			[2] = { str = "Next to the shack accept #GETA Plague Upon Thee pt.1#" },
			[3] = { str = "Grab the FP" },
			[3] = { str = "Whenever you come back to camp here always check the vendor for the stormshroud pants recipe. It’s like 1.3g and you can easily sell it for 10 or 20g+ It’s a limited recipe that restocks 1 every hour." },
			[4] = { str = "Go to the tent and turn in #INA Call To Arms: The Plaguelands!#, accept #GETClear The Way#" },
			[5] = { str = "Go to the 3 Argent Dawn people near the other tent and turn in #INThe Everlook Report# and also complete #GETArgent Dawn Commission# it’s not a quest you had she just uses it to give you the trinket which you should always wear when in WPL and EPL because it gives you AD rep and allows the scourge tokens to drop, which she also has 3 new quests on those for turn ins. You most likely won’t get anything past the first quest as the rest are mainly in the instances." },
			[6] = { str = "Save the tokens until I say to hand them in" },
			[7] = { str = "Go NE to around #COORD[51,78]# and grind the ghouls here until you got enough for #DOClear The Way#", x = 51, y = 78, zone = "Western Plaguelands" },
			[8] = { str = "Go back to Chillwind Camp at #COORD[42,84]# and turn in #INClear The Way# accept #GETAll Along the Watchtowers# and #GETThe Scourge Cauldrons#", x = 42, y = 84, zone = "Western Plaguelands" },
			[9] = { str = "Turn around and turn in #INThe Scourge Cauldrons# accept #GETTarget: Felstone Field#" },
			[10] = { str = "You should now be about 5-10k from level 57" },
			[11] = { str = "Go back NE to #COORD[48,72]# and go over the bridge", x = 48, y = 72, zone = "Western Plaguelands" },
			[12] = { str = "Just in the town on the left at #COORD[47,71]# is the 4th tower for #DOAll Along the Watchtowers#, there are elites inside but you can stand out of LOS on the edge and mark the doors easily. 1st tower West of here at #COORD[40,71]#. 2nd tower NE of here at #COORD[42,66]#. 3rd tower NE of here at #COORD[44,63]#. Just behind this tower.", x = 47, y = 71, zone = "Western Plaguelands" },
			[13] = { str = "Go NW to #COORD[37,56]# to Felstone field, kill #NPCCauldron Lord Bilemaw# for his cauldron key. Then go right click the cauldron and turn in #INTarget: Felstone Field# accept #GETReturn to Chillwind Camp#", x = 37, y = 56, zone = "Western Plaguelands" },
			[14] = { str = "Theres 2 houses on the NE side of the field at #COORD[38,54]#, enter the northern house and go upstairs. Accept #GETBetter Late Than Never pt.1#", x = 38, y = 54, zone = "Western Plaguelands" },
			[15] = { str = "Go in the barn next door and grab the box on the floor and turn in #INBetter Late Than Never pt.1# accept #GETBetter Late Than Never pt.2#" },
			[16] = { str = "Run back to Chillwind Camp at #COORD[42,84]# and turn in #INAll Along the Watchtowers#, accept #GETScholomance# SKIP the other unless you get about 10-20 people.", x = 42, y = 84, zone = "Western Plaguelands" },
			[17] = { str = "Turn in #INScholomance# just behind him, accept #GETSkeletal Fragments Bones# for this will take a while and drop off any skeletons." },
			[18] = { str = "Near the FP turn in #INReturn to Chillwind Camp# accept #GETTarget: Dalson's Tears#" },
			[19] = { str = "Go up to #COORD[46,52]# to Dalson’Tears, kill #NPCCauldron Lord Malvinious# for his cauldron key. Then go right click the cauldron and turn in #INTarget: Dalson's Tears# accept #GETReturn to Chillwind Camp#", x = 46, y = 52, zone = "Western Plaguelands" },
			[20] = { str = "Enter the barn here at #COORD[47,50]# and touch the diary on the floor and complete it, another quest that isn’t a quest.", x = 47, y = 50, zone = "Western Plaguelands" },
			[21] = { str = "Go behind the barn and look for a Wandering Skeleton and get Dalson Outhouse Key off of him. Use this to open the outhouse back here and kill Farmer Dalson and get his Dalson Cabinet Key. Use the key on the locked cabinet upsairs in the house now at #COORD[47,49]# next to the barn and complete the quest #INLocked Away#", x = 47, y = 49, zone = "Western Plaguelands" },
			[22] = { str = "Go back to Chillwind Camp at #COORD[42,84]# and turn in #INReturn to Chillwind Camp# accept #GETTarget: Writhing Haunt#", x = 42, y = 84, zone = "Western Plaguelands" },
			[23] = { str = "Hearth to IF then fly to SW" },
			[24] = { str = "Go to the building at #COORD[48,30]# on the 2nd floor of the cathedral area and turn in #INBetter Late Than Never pt.2# accept #GETGood Natured Emma#", x = 48, y = 30, zone = "Stormwind" },
			[25] = { str = "Emma travels between the cathedral and the trade district, find her and turn in #INGood Natured Emma# accept #GETGood Luck Charm#" },
			[26] = { str = "Go into the keep at #COORD[78,17]# and accept #GETThe First and the Last#", x = 78, y = 17, zone = "Stormwind" },
			[27] = { str = "Go to #COORD[75,79]# and turn in #INThe First and the Last# accept #GETHonor the Dead# then turn it right back in, accept #GETFlint Shadowmore#", x = 75, y = 79, zone = "Stormwind" },
			[28] = { str = "Fly back to WPL" },
			[29] = { str = "In front of the house turn in #INFlint Shadowmore# accept #GETThe Eastern Plagues#" },
			[30] = { str = "Go back to Felstone field to the house upstairs at #COORD[38,54]# and turn in #INGood Luck Charm# accept #GETTwo Halves Become One# Go outside and look for a jabbering ghoul. You can’t miss him he carry’s a pitchfork. Keep clearing in front of the house until you find him. This will give you a good time to get those skeletal fragments", x = 38, y = 54, zone = "Western Plaguelands" },
			[31] = { str = "Combine the halves and go back upstairs and turn in #INTwo Halves Become One#" },
			[32] = { str = "Go SE to #COORD[53,65]# to Writhing Haunt, kill #NPCCauldron Lord Razarch# for his cauldron key. Then go right click the cauldron and turn in #INTarget: Writhing Haunt# accept #GETReturn to Chillwind Camp#", x = 53, y = 65, zone = "Western Plaguelands" },
			[33] = { str = "In the house at #COORD[54,65]# accept #GETThe Wildlife Suffers Too pt.1# now go north of the haunt and kill the diseased wolves. Don’t go any farther east to find these just go North, maybe NW some.", x = 54, y = 65, zone = "Western Plaguelands" },
			[34] = { str = "Go back to #COORD[54,65]# and turn in #INThe Wildlife Suffers Too pt.1# accept #GETThe Wildlife Suffers Too pt.2#", x = 54, y = 65, zone = "Western Plaguelands" },
			[35] = { str = "Go back to Chillwind Camp at #COORD[42,84]# and turn in #INReturn to Chillwind Camp# accept #GETTarget: Gahrron's Withering#", x = 42, y = 84, zone = "Western Plaguelands" },
			[36] = { str = "Go just north of the Writhing Haunt between the mountains on the map at, #COORD[52,56]# and kill diseased grizzleys on your way down to #COORD[62,58]# for #DOThe Wildlife Suffers Too pt.2#", x = 52, y = 56, zone = "Western Plaguelands" },
			[37] = { str = "Go NE to #COORD[62,58]# to Gahrron’s Withering, kill #NPCCauldron Lord Soulwrath# for his cauldron key. Then go right click the cauldron and turn in #INTarget: Gahrron's Withering# accept #GETReturn to Chillwind Camp#", x = 62, y = 58, zone = "Western Plaguelands" },
			[38] = { str = "Go back to #COORD[54,65]# and turn in #INThe Wildlife Suffers Too pt.2# accept #GETGlyphed Oaken Branch#", x = 54, y = 65, zone = "Western Plaguelands" },
			[39] = { str = "If you haven’t finished Skeletal Fragments yet go to the crypt at #COORD[54,79]# and kill the skeletons until you have 15 fragments", x = 54, y = 79, zone = "Western Plaguelands" },
			[40] = { str = "Go back to Chillwind Camp at #COORD[42,84]# and turn in #INReturn to Chillwind Camp#", x = 42, y = 84, zone = "Western Plaguelands" },
			[41] = { str = "Turn around to the guy in front of the tent, and complete the quest #INMission Accomplished!# no link for it cuz it’s not a quest again lol. Now see that running back and forth seemed out of the way but there was a huge xp boost at the end, and nice xp throughout." },
			[42] = { str = "To your right turn in #INSkeletal Fragments# SKIP the next part unless you want to start on your scholo key." },
			[43] = { str = "Run east to #COORD[70,50]# and enter the Eastern Plaguelands (EPL)", x = 70, y = 50, zone = "Western Plaguelands" },
		}
	},

-----------57-58 Eastern Plaguelands
	--[512] = {
	[5758] = {
		title = "57-58 Eastern Plaguelands",
		--n = "57-58 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 19,
		items = {
			[1] = { str = "57-58 Eastern Plaguelands" },
			[2] = { str = "Run up the west coast to 67,4 and accept the 3 quests #GETDemon Dogs# #GETBlood Tinged Skies# and #GETCarrion Grubbage#", x = 67, y = 4, zone = "Eastern Plaguelands" },
			[3] = { str = "These are annoying quests that can take a while. Anytime from now until these are done, kill any plaguehound runts, carrion worms, or plaguebats." },
			[4] = { str = "From here on down to the bigger area, kill any dogs, worms, and bats. Focus on them while you head to the next step" },
			[5] = { str = "Keep killing the dogs and bats and head over to the skeleton at #COORD[28,74]# open it and grab the insignia for #DOThe Eastern Plagues# then run up a bit further to the next skeleton at #COORD[27,74]# and grab the insignia, it’s practically right in front of him and you will also get the blightcaller found complete message. Now go down near the road to #COORD[28,79]# and loot the last insignia off the skeleton", x = 28, y = 74, zone = "Eastern Plaguelands" },
			[6] = { str = "Focus on the dogs and bats while you head to Darrowshire at #COORD[36,90]# in the broken down house. Turn in #INSister Pamela# accept #GETPamela's Doll# then head towards the houses here, in any of the houses can be any of the 3 doll parts. They are random. Ghosts spawn when you get near the parts so be aware. Once you have all 3 parts combine them and go back to #COORD[36,90]# and turn in #INPamela's Doll# accept #GETAuntie Marlene# and #GETUncle Carlin#", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[7] = { str = "Look on your map at #COORD[48,76]# This lines up with that middle ridge mountain. Don’t go past this spot east until you have your plaguehound runt kills for #DODemon Dogs# and plaguebats for #DOBlood Tinged Skies# because there is none past that point.", x = 48, y = 76, zone = "Eastern Plaguelands" },
			[8] = { str = "Don’t forget to kill the grubs along the way too for #DOCarrion Grubbage#, they’re not as important because they’re all over." },
			[9] = { str = "Kill Plaguehounds for Demon Dogs all around #COORD[56,57]# this is north of the scar and south of blackwood lake. Don’t forget the grubs", x = 56, y = 57, zone = "Eastern Plaguelands" },
			[10] = { str = "Kill Frenzied Plaguehounds for #DODemon Dogs# all around #COORD[61,41]# this is north of blackwood lake but now west of it.", x = 61, y = 41, zone = "Eastern Plaguelands" },
			[11] = { str = "Head to lights hope chapel at #COORD[81,58]# if you still need grub meat for #DOCarrion Grubbage#, then kill them as you", x = 81, y = 58, zone = "Eastern Plaguelands" },
			[12] = { str = "Get the FP" },
			[13] = { str = "Turn in #INUncle Carlin# accept #GETDefenders of Darrowshire#" },
			[14] = { str = "Turn around and turn in #INDuke Nicholas Zverenhoff#" },
			[15] = { str = "Run SW to #COORD[79,63]# and accept #GETZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[16] = { str = "Fly back to EPL" },
			[17] = { str = "In front of the house turn in #INThe Eastern Plagues# accept #GETThe Blightcaller Cometh#" },
			[18] = { str = "If you’re within 6,600 to level then Hearth to IF and fly to SW, if not then grind until you’re within range." },
			[19] = { str = "Go to #COORD[78,18]# in the keep and turn in #INThe Blightcaller Cometh# now I SKIP the next part but it’s a good quest to do at 60", x = 78, y = 18, zone = "Eastern Plaguelands" },
			[18] = { str = "Go get new skills" },
			[19] = { str = "Fly back to WPL" },
		}
	},

-----------58-58 Western Plaguelands
	--[513] = {
	[5857] = {
		title = "58-58 Western Plaguelands",
		--n = "58-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 9,
		items = {
			[1] = { str = "58-58 Western Plaguelands" },
			[2] = { str = "Go NE to the house at #COORD[49,78]# and go upstairs. Turn in #INPamela's Doll# accept #GETA Strange Historian#", x = 49, y = 78, zone = "Western Plaguelands" },
			[3] = { str = "Just north of the house at #COORD[49,76]# you’ll see an off color gravestone. Loot it and get the wedding ring for #DOA Strange Historian#", x = 49, y = 76, zone = "Western Plaguelands" },
			[4] = { str = "Go in the west entrance to Andorhal at #COORD[39,71]#and you should see the only full building, looks like an Inn at #COORD[39,68]#. Go upstairs and turn in #INA Strange Historian# accept #GETThe Annals of Darrowshire# also accept #GETA Matter of Time#", x = 39, y = 68, zone = "Western Plaguelands" },
			[5] = { str = "Now look all around the city here for busted up silo’s with a blue light coming out of them. Use the silo horn to summon the worms, it spawns 1-3 mobs for #DOA Matter of Time#. Once you kill the last one they have a tendency to spawn another. They’re more on the East side of town" },
			[6] = { str = "Go to the Town Hall near all the mobs in the middle of town, you can sneak in from the SW side. Grab the books on the floor until you get the #GETThe Annals of Darrowshire# Some will spawn mobs" },
			[7] = { str = "Go back to the Inn at #COORD[39,68]# and to the top floor, turn in #INA Matter of Time# accept #GETCounting Out Time# also turn in #INThe Annals of Darrowshire# accept #GETBrother Carlin#", x = 39, y = 68, zone = "Western Plaguelands" },
			[8] = { str = "Go outside and look around the busted houses for little metal lunchboxes for #DOCounting Out Time#" },
			[9] = { str = "Go back to the Inn at #COORD[39,68]# and turn in #INCounting Out Time# you can now repeat this quest for a dampener. This is used vs the 61 elite", x = 39, y = 68, zone = "Western Plaguelands" },
		}
	},

-----------58-58 Eastern Plaguelands
	--[514] = {
	[5858] = {
		title = "58-58 Eastern Plaguelands",
		--n = "58-58 Eastern Plaguelands",
		--pID = 513, nID = 515,
		--itemCount = 18,
		items = {
			[1] = { str = "58-58 Eastern Plaguelands" },
			[2] = { str = "Run out of here and into EPL up to the NW at 7,43 and turn in the 3 quests #INDemon Dogs# #INBlood Tinged Skies# and #INCarrion Grubbage# accept #GETRedemption# then listen to him and turn it back in. Then accept #GETOf Forgotten Memories#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "Go to the Undercroft at #COORD[28,86]# and run behind it. Touch the dirt pile to summon Mercutio and 3 guards. Easiest way to do this is to kite him away from his buddies or get a group. Loot his body for the hammer for #DOOf Forgotten Memories#", x = 28, y = 86, zone = "Eastern Plaguelands" },
			[4] = { str = "Now go to the bottom of the crypt and kill the very big troll for #DOZaeldarr the Outcast# Only grab the scroll on the floor if u want" },
			[5] = { str = "Go back to 7,43 and turn in #INOf Forgotten Memories# accept #GETOf Lost Honor#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[6] = { str = "Either Run to Light’s Hope Chapel or back to Chillwind and fly there" },
			[7] = { str = "Turn in #INBrother Carlin# accept #GETVillains of Darrowshire#" },
			[8] = { str = "Go down to #COORD[79,63]# and turn in #INZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[9] = { str = "Go down just North of Corin’s Crossing to #COORD[53,65]# and grab the sword for #DOVillains of Darrowshire# It’s down in the scar. Don’t forget to do some of #DODefenders of Darrowshire# at Corin’s Just get what you can", x = 53, y = 65, zone = "Eastern Plaguelands" },
			[10] = { str = "Go north to Blackwood Lake at #COORD[51,49]# and grab the skull under the water for #DOVillains of Darrowshire#", x = 51, y = 49, zone = "Eastern Plaguelands" },
			[11] = { str = "Go NE to around #COORD[65,41]# and kill the zombies for part of #DODefenders of Darrowshire# there are quite a lot here you could probably finish", x = 65, y = 41, zone = "Eastern Plaguelands" },
			[12] = { str = "Go to the lake at #COORD[71,33]# and grab the flag next to the cage, it’s hard to see and is laying flat for #DOOf Lost Honor#", x = 71, y = 33, zone = "Eastern Plaguelands" },
			[13] = { str = "Go NW to the tower at #COORD[56,24]# and turn in #INTroubled Spirits of Kel'Theril# SKIP the next part", x = 56, y = 24, zone = "Eastern Plaguelands" },
			[14] = { str = "Run West to #COORD[45,34]# and loot the termite mounds here for #DOA Plague Upon Thee pt.1# until you get 100 termites, also kill ghouls to finish up #DODefenders of Darrowshire#", x = 45, y = 34, zone = "Eastern Plaguelands" },
			[15] = { str = "Run to Lights Hope Chapel now" },
			[16] = { str = "Go by the tent and turn in #INDefenders of Darrowshire# and #INVillains of Darrowshire#" },
			[17] = { str = "Fly to WPL" },
			[18] = { str = "Next to the house turn in #INA Plague Upon Thee pt.1# accept #GETA Plague Upon Thee pt.2#" },
		}
	},

------------58-59 Western Plaguelands
	--[515] = {
	[5859] = {
		title = "58-59 Western Plaguelands",
		--n = "58-59 Western Plaguelands",
		--pID = 514, nID = 516,
		--itemCount = 19,
		items = {
			[1] = { str = "58-59 Western Plaguelands" },
			[2] = { str = "Run up to #COORD[51,28]# and accept #GETUnfinished Business pt.1#", x = 52, y = 30, zone = "Western Plaguelands" },
			[3] = { str = "Start heading back SW around #COORD[47,32]# and clear your way into the mill. Right click the box and place the termintes, then click the barrel and turn in #INA Plague Upon Thee pt.2# accept #GETA Plague Upon Thee pt.3#", x = 47, y = 32, zone = "Western Plaguelands" },
			[4] = { str = "Go just south of #COORD[49,42]# and kill 2 knights and mages for #DOUnfinished Business pt.1# then #COORD[51,43]# for the hunters and medics", x = 49, y = 42, zone = "Western Plaguelands" },
			[5] = { str = "Go to #COORD[51,28]# and turn in #INUnfinished Business pt.1# accept #GETUnfinished Business pt.2#", x = 51, y = 28, zone = "Western Plaguelands" },
			[6] = { str = "Go to #COORD[57,36]# and kill Huntsman Radly for #DOUnfinished Business pt.2# then north to the tower at #COORD[55,23]# and kill Cavalier Durgen at the top", x = 57, y = 36, zone = "Western Plaguelands" },
			[7] = { str = "Go straight out of the tower over the mountains to #COORD[51,28]# and turn in #INUnfinished Business pt.2# doing the 3rd part #DOUnfinished Business pt.3# is optional. Some classes can do it easier than others. You have to run north to hearthglen and run up into the big tower in the center of town at #COORD[45,18]# and look over the edge until it says complete.", x = 45, y = 18, zone = "Western Plaguelands" },
			[8] = { str = "Run back straight south over the mountains to #COORD[51,28]# and turn in #INUnfinished Business pt.3#", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "Run into EPL and up to 7,43 and turn in #INOf Lost Honor# accept #GETOf Love and Family pt.1#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[10] = { str = "Go back to WPL and run/swim to the island Scholo is on at #COORD[65,75]# and turn in #INOf Love and Family pt.1# SKIP the rest until you do strat", x = 65, y = 75, zone = "Western Plaguelands" },
			[11] = { str = "Go back to Chillwind Camp at #COORD[43,84]# and turn in #INA Plague Upon Thee pt.3#", x = 43, y = 84, zone = "Western Plaguelands" },
			[12] = { str = "Now you want to do 2 things here. Get friendly with Argent Dawn and get 8-8.5k from leveling. You can do #DOAlas, Andorhal# if you can find a group, it’s not that hard but can take 5-10 people. This will give you an easy 8300 xp instead of grinding." },
			[13] = { str = "Now you want to go up to andorhal and just grind until you’re friendly, once you’re friendly go back to Chillwind Camp and turn in all your scourge tokens. This allows you to buy mana biscuits which restore mana and health and more than food can. If you still need to level then go grind on mobs in andorhal again until you’re 8-8.5k from level 59" },
			[14] = { str = "Once you’re 8k-8.5k from leveling, fly to Hinterlands and run all the way NE to the waterfall at #COORD[80,46]# and jump off. Under the water loot the chest and finish #DOCortello’s Riddle pt.3#", x = 80, y = 46, zone = "The Hinterlands" },
			[15] = { str = "Hearth to IF" },
			[16] = { str = "Go to the throne room at #COORD[43,52]# and accept #GETAn Earnest Proposition# (pick your class from the list) You have to have your classes tier 0 bracers in order to do this quest. You can buy it on AH", x = 43, y = 52, zone = "Ironforge" },
			[17] = { str = "Fly to Menethil and sail to Auberdine, fly to Darnassus" },
			[18] = { str = "Go to 35,8 on the 2nd floor and turn in #INGlyphed Oaken Branch#", x = 35, y = 8, zone = "Darnassus" },
			[19] = { str = "You should be level 59, fly to Winterspring" },
		}
	},

------------59-60 Winterspring
	--[516] = {
	[5960] = {
		title = "59-60 Winterspring",
		--n = "59-60 Winterspring",
		--pID = 515, nID = 516,
		--itemCount = 31,
		items = {
			[1] = { str = "59-60 Winterspring" },
			[2] = { str = "On your left after entering turn in #INAre We There, Yeti? pt.3#" },
			[3] = { str = "Near the back are 2 horde, accept #GETLuck Be With You#" },
			[4] = { str = "Turn around and turn in #INFelnok Steelspring# accept #GETChillwind Horns#" },
			[5] = { str = "Do #DOAn Earnest Proposition# just kill the sabers until you have 15 blood" },
			[6] = { str = "Go just SE of here around #COORD[55,18]# and kill the chimera’s for #DOChillwind Horns#", x = 55, y = 18, zone = "Winterspring" },
			[7] = { str = "Run to Starfall Village at #COORD[52,30]# and accept #GETEnraged Wildkin pt.1#", x = 52, y = 30, zone = "Winterspring" },
			[8] = { str = "Turn in #INChillwind Horns# SKIP the other unless you want to go there" },
			[9] = { str = "Go south to #COORD[59,59]# and touch the crate and turn in #INEnraged Wildkin pt.1# accept #GETEnraged Wildkin pt.2#", x = 59, y = 59, zone = "Winterspring" },
			[10] = { str = "Go back to the roat at #COORD[61,60]# and touch the wagon, turn in #INEnraged Wildkin pt.2# accept #GETEnraged Wildkin pt.3# grab the box in the snow", x = 61, y = 60, zone = "Winterspring" },
			[11] = { str = "Run east again to #COORD[63,59]# and turn in #INFind Ranshalla# accept #GETGuardians of the Altar#", x = 63, y = 59, zone = "Winterspring" },
			[12] = { str = "Now protect her while she does her thing. Make sure you get the feather off an owl for #DOEnraged Wildkin pt.3# When she stops in a cave, light the torch for her. If you don’t get the feather before you’re done keep killing until you got it." },
			[13] = { str = "Go south to #COORD[62,69]# and loot the gems for #DOLuck Be With You# hunters and locks can use pet to distract mobs while you loot, other classes will have to group.", x = 62, y = 69, zone = "Winterspring" },
			[14] = { str = "Hearth to Everlook" },
			[15] = { str = "Turn in #INLuck Be With You# at the 2 horde near the back of everlook" },
			[16] = { str = "You should be about 25% into level 59 now." },
			[17] = { str = "Accept #GETCache of Mau'Ari# if you want to. This just gives you an item which allows the mobs here to drop stuff which you can turn in for buffs" },
			[18] = { str = "Go up to Starfall Village at #COORD[52,30]# and turn in #INEnraged Wildkin pt.3#", x = 52, y = 30, zone = "Winterspring" },
			[19] = { str = "Run to #COORD[31,45]# and turn in #INMystery Goo# accept #GETToxic Horrors#", x = 31, y = 45, zone = "Winterspring" },
			[20] = { str = "Run into Felwood and go to #COORD[48,24]# and kill toxic horrors for #DOToxic Horrors# these also drop essence of waters", x = 48, y = 24, zone = "Felwood" },
			[21] = { str = "Fly to Rut’theran Village and go to the house at #COORD[55,92]# and turn in #INGuardians of the Altar# accept #GETWildkin of Elune#", x = 55, y = 92, zone = "Teldrassil" },
			[22] = { str = "Go in Darnassus and up to the top of the tower at 34,8 and turn in #INWildkin of Elune#", x = 34, y = 8, zone = "Darnassus" },
			[23] = { str = "Fly back to Felwood" },
			[24] = { str = "Run back up into Winterspring and over to #COORD[31,45]# turn in #INToxic Horrors# accept #GETWinterfall Runners#", x = 31, y = 45, zone = "Winterspring" },
			[25] = { str = "Now to find the runners. They travel anywhere from the Timbermaw Cave east to #COORD[53,34]# then up around the mountains north of everlook over to Winterfall Village. If you didn’t see them from the cave to here, head east. You don’t have to kill all 3", x = 53, y = 34, zone = "Winterspring" },
			[26] = { str = "Once you get the crate run back to #COORD[31,45]# Turn in Winterfall Runners an ambush will come from the lake, if you don’t move from the tent they won’t aggro you. SKIP the next part unless you get a group", x = 31, y = 45, zone = "Winterspring" },
			[27] = { str = "Hearth to Everlook" },
			[28] = { str = "You should be 45-50% through level 59. Now I make sure I got my mana bisquits and I start grinding until im 6600 to level 60. Anywhere is fine where there is a lot of mobs It’s all a matter of preference. I choose the owl wing thicket at #COORD[64,62]# or anything north of everlook. I like to kill the furlbogs for timbermaw rep also.", x = 64, y = 62, zone = "Winterspring" },
			[29] = { str = "If you don’t want to grind this large amount then do BRD, scholo, or strat. You have a lot of quests in those spots to do" },
			[30] = { str = "Once you’re 6600 to 60 go to IF and turn in #INAn Earnest Proposition#" },
			[31] = { str = "Grats on 60!" },
		}
	},
}
