local L = AceLibrary("AceLocale-2.0"):new("NotGrid")

L:RegisterTranslations("enUS", function() return {
["Dead"] = true,
["Ghost"] = true,
["Spirit of Redemption"] = true,
["%s of %s"] = true,
["Default Friendly"] = true,
["(Rank "] = true,

["Rejuvenation"] = true,
["Magic"] = true,
["Poison"] = true,
["Curse"] = true,
["Disease"] = true,
["Mortal Strike"] = true,

["Unit Width"] = true,
["Unit Height"] = true,
["Unit Border"] = true,
["Unit Padding"] = true,
["Font"] = true,
["Texture"] = true,
["Orientation"] = true,
["Name"] = true,
["Name Length"] = true,
["Health"] = true,
["Highlight Target"] = true,
["Aggro Warning"] = true,
["Mana Warning"] = true,
["Healcomm"] = true,
["Healcomm Text"] = true,
["Top Left Icon"] = true,
["Top Icon"] = true,
["Top Right Icon"] = true,
["Right Icon"] = true,
["Bottom Right Icon"] = true,
["Bottom Icon"] = true,
["Bottom Left Icon"] = true,
["Left Icon"] = true,
["Proximity Leeway"] = true,
["Use Map Proximity"] = true,
["Smart Center"] = true,
["Show While Solo"] = true,
["Show In Party"] = true,
["Right To Left"] = true,
["Show Blizz Frames"] = true,
["Locked"] = true,
} end)

L:RegisterTranslations("ruRU", function() return {
["Dead"] = "Мертв",
["Ghost"] = "Призрак",
["Spirit of Redemption"] = "Дух воздаяния",
["%s of %s"] = "%s из %s",
["Default Friendly"] = "Дружелюбная",
["(Rank "] = "(Уровень ",

["Rejuvenation"] = "Омоложение",
["Magic"] = "Магия",
["Poison"] = "Яд",
["Curse"] = "Проклятье",
["Disease"] = "Болезнь",
["Mortal Strike"] = "Смертельный удар",

["Unit Width"] = "Ширина рамок",
["Unit Height"] = "Высота рамок",
["Unit Border"] = "Бордюр рамок",
["Unit Padding"] = "Интервал рамок",
["Font"] = "Шрифт",
["Texture"] = "Текстура",
["Orientation"] = "Ориентация",
["Name"] = "Имя по цвету класса",
["Name Length"] = "Длина имени",
["Health"] = "Здоровье по цвету класса",
["Highlight Target"] = "Выделение цели",
["Aggro Warning"] = "Предупреждение аггро",
["Mana Warning"] = "Предупреждение маны",
["Healcomm"] = "Входящее исцеление",
["Healcomm Text"] = "Текст входящего исцеления",
["Top Left Icon"] = "Иконка сверху слева",
["Top Icon"] = "Иконка сверху",
["Top Right Icon"] = "Иконка сверху справа",
["Right Icon"] = "Иконка справа",
["Bottom Right Icon"] = "Иконка снизу справа",
["Bottom Icon"] = "Иконка снизу",
["Bottom Left Icon"] = "Иконка снизу слева",
["Left Icon"] = "Иконка слева",
["Proximity Leeway"] = "Proximity Leeway", --
["Use Map Proximity"] = "Use Map Proximity", --
["Smart Center"] = "Smart Center", --
["Show While Solo"] = "Показать вне группы",
["Show In Party"] = "Показать в группе",
["Right To Left"] = "Справо на лево",
["Show Blizz Frames"] = "Показывать стандартные фреймы",
["Locked"] = "Заблокировать",
} end)